CommunityToolkit/WindowsCommunityToolkit

Microsoft.Toolkit.Uwp.SampleApp/Controls/CodeRenderer/CodeRenderer.Properties.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Blur.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/CompositionBehaviorBase.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Fade.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Offset.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Rotate.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Scale.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Options.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Members.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Placeholder.cs
Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs

Since C#6 has this amazing feature that prevent future hidden bugs, let's use it. This commit replaces hard-coded property strings by compile-time strings.

Use C#6 nameof() instead of hard-coded strings

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.cs

Rationale: we don't always have the Text property set (I'm thinking of scenarios
involving incomplete translation strings)

HeaderedTextBlock: if Text is empty, hide its TextBlock

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/BladeControl/BladePage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/Blade.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.cs
Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.Properties.cs

Noticed BladeID naming in the PR (but after merge), while cleaning up I noticed a few more code warnings that got through the PRs

Cleaning up warnings

---

Microsoft.Toolkit.Uwp/Helpers/StorageFileHelper.cs

Adding async comes at a price. Async/await keywords are not necessary on the updated calls.
Also clearly shows these are actually extension methods.

Removed unnecessary async/await keywords

---

Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
Microsoft.Toolkit.Uwp.UI.Controls/RotatorTile/RotatorTile.cs
UnitTests.Notifications.Shared/TestMail.cs
UnitTests.Notifications.Shared/TestWeather.cs
UnitTests/Helpers/Test_ColorHelper.cs
UnitTests/Helpers/Test_StorageFileHelper.cs
UnitTests/Helpers/Test_StreamHelper.cs
UnitTests/Services/Test_BingService.cs

Nr 12: We use PascalCasing to name all our constant local variables and fields. The only exception is for interop code where the constant value should exactly match the name and value of the code you are calling via interop.

Consistent naming for const variables

---

build/default.ps1

The build script was manually updating AppVeyor build number, but seems this isn't required as GitVersion does the same automatically.

GitVersion is updating AppVeyor build number so we don't need to do it manually

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Blur.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/CompositionBehaviorBase.cs

In some cases AutomaticallyStart set in the XAML code does not work.
That is because for some reason, the _frameworkElement property is null if StartAnimation() is called too early. 
Repro case here : 
[App1.zip](https://github.com/Microsoft/UWPCommunityToolkit/files/434631/App1.zip)
Or you can just create a new UWP app project in the UWP Toolkit solution, copy the Blur sample in mainpage.

Fix blur animation auto start

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Blur.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Offset.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Rotate.cs

Currently, animation behaviours set translation offsets of 1, rotation angle of 1, and blur radius of 1 by default. This changes them all to be 0 which most users would expect.

Better animation behavior defaults

---

build/default.ps1

GitVersion is causing builds to fail, so I'm adding `/nofetch` following @onovotny recomendation.

Ensures GitVersion does not attempt to make a "git fetch"

---

Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs

When drawing the background scale, the RadialGauge assumed it to be a large arc (> 180°). Since MinimumAngle and MaximumAngle are now dependency properties, this assumption became false. So the calculation is adjusted.

Correctly draw RadialGauge scale when arc < 180°.

---

Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj.DotSettings
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/MicrosoftGraphAuthenticationHelper.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/MicrosoftGraphCoreService.cs
Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj.DotSettings
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj.DotSettings
Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj.DotSettings
Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj.DotSettings

Probably quite a few of us use ReSharper (seeing the .dotSettings file in the project root). Added settings files to the projects which have non-default namepace-folder behavior (to prevent accidental mass refactoring namespaces in the future).
Also fixed namespace of MicrosoftGraphAuthenticationHelper to bring in sync with all other types in that subtree.

Added ReSharper dotsettings

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugeCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugePage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs

RadialGauge scale and trail are now correctly drawn when MinAngle and MaxAngle describe a full circle  (e.g. -180° to +180°) like in a 'percentage ring' layout.
Reason for the code change: ArcSegment can not draw a full circle.

RadialGauge full 360° support.

---

Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.xaml
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SwipeStatus.cs

This PR solves #329 (SlidableListItem is not transparent). Almost all changes are in ContentGrid_ManipulationDelta that was rewritten from scratch. When testing this on a mobile I haven’t seen any major performance impact.
One thing I haven’t figure out to do is animate the opacity of _commandContainer to 0 when swiping is completed (**update**: clipping on should be animated, not opacity). Now it just immediately disappears, which is not that bad, but I assume an animation would be better. I tried to do something similar like _contentAnimation but it didn’t work :-/. Some guidance here would be great because I’m sure it’s trivial :-)
If swiping is disabled in one direction the user will still be able to swipe but just a tiny bit. Very similar to pulling down on a list that is scrolled to …

Issue329 and343

---

Microsoft.Toolkit.Uwp.Notifications.NETStandard/project.json

NETStandard 1.6.0 is not currently supported by .NET Framework as outlined [here](https://docs.microsoft.com/en-us/dotnet/articles/standard/library).
This cause the build to fail when using MSBuild.
It works correctly when building with Visual Studio, because VS seem to be overriding this to use 1.0 (not really sure about that).
Changing the dependency to 1.5 to fix this issue.
More info on this issue:
https://github.com/dotnet/corefx/issues/10213
https://github.com/dotnet/roslyn/issues/12918

Downgrade NETStandard.Library to 1.5.0

---

readme.md

Added the AppVeyor build status badge to the readme.md file

Added AppVeyor build status badge to readme.md file

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs

Adding a check to ensure progress ring is not null before checking the width

Addressing #388 NullReference if ProgressRing isn't part of template

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SlidableListItem/SlidableListItemCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SlidableListItem/SlidableListItemPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs

and added
```csharp
Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () => { SwipeStatus = SwipeStatus.Idle; }).AsTask();
```
to delay SwipeStatus changing to after PointerPressed firing
ref #316

Added IsPointerReleasedOnSwipingHandled Property

---

Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.xaml

This changes the default value of ExtraSwipeThreshold (which is not in the release version). This affects how much the user can slide the SlidableListItem. I think it looks better to have the same margin on both sides.

Changes default value of ExtraSwipeThreshold.

---

Microsoft.Toolkit.Uwp.UI.Animations/AnimationSet.cs

Stop now has the same behavior for composition and storyboards (pauses the animation).
Completed event was not firing when storyboards were used.
ref #392

Fixed stop and completed event on AnimationSet

---

Microsoft.Toolkit.Uwp.UI/Converters/BoolNegationConverter.cs
Microsoft.Toolkit.Uwp.UI/Converters/DateTimeToStringConverter.cs
Microsoft.Toolkit.Uwp.UI/Converters/FormatStringConverter.cs
Microsoft.Toolkit.Uwp.UI/Converters/ResourceNameToResourceStringConverter.cs

Added BoolNegationConverter, DateTimeToStringConverter and ResourceNameToResourceStringConverter.
I use very often these converters during my UWA development,, so I though that may be useful to have them in the community toolkit.
Names and XML summaries should be enough self-explainatory on what they do.
Let me know what do you think.

Added new Converters.

---

Microsoft.Toolkit.Uwp/Helpers/ConnectionHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ConnectionType.cs
Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj

Expose ConnectionType property
Rework IsInternetAvailable property
Work on #455

Connection Helper

---

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/IObjectStorageHelper.cs

To reduce the overhead, we should improve these two async tasks as well. @ScottIsAFool trained my eye to spot such things 👍

Remove useless awaits of BaseObjectStorageHelper

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Addresses issue #479 
Set the `ItemHeight`, `ItemWidth` and `DesiredWidth` default values to double.NaN to allow the control to be used without setting those values. This will cause all the elements to align in a vertical fashion.
This allows the `AdaptiveGrid` control to be used without setting the above properties as such:
```
<controls:AdaptiveGrid ItemsSource="{Binding Items}" ItemTemplate="{StaticResource ItemTemplate}"/>
```

Allow AdaptiveGrid to be used without setting ItemHeight, ItemWidth, or DesiredWidth properties.

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs

Set default values for ItemHeight, ItemWidth, and DesiredWidth to double.NaN which allows the control to be used without setting these.
Final fixes for #479

Set default values for ItemHeight, ItemWidth, and DesiredWidth

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs

Added RemoveExpiredAsync
Use RemoveExpiredAsync when ClearAsync is called with Duration
Used Timespan rather than converting to DateTime. Pass TimeSpan all the way to IsFileOutOfDate method
Add optional parameter to IsFileOutOfDate method indicating how to treat null files.
Addresses #482

CacheBase tweaks

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs

When a valid file exists in cache, the CacheBase should use the InitializeTypeAsync overload that takes StorageFile. It currently forces the use of Stream version and that does not work when FileCache is used.

Use correct InitializeTypeAsync overload in GetFromCacheOrDownloadAsync

---

docs/helpers/DeepLinkParsers.md

Provides a way to create, from `IActivatedEventArgs` or `string`, a `Dictionary<string,string>`-inheriting object that provides an additional `.Root` property to pull the base path of the URI (eg: in `MainPage/Options?option1=value1`, `.Root` would be `MainPage/Options`.
Once you have an instance, simply saying `instance["optionName"]` will pull the value from the querystring for that option.
in OnLaunched of App.xaml.cs:
```
if (e.PrelaunchActivated == false)
{
if (rootFrame.Content == null)
{
var parser = DeepLinkParser.Create(args);
if (parser["username"] == "John Doe")
{
// do work here
}
if (parser.Root == "Signup")
{
rootFrame.Navigate(typeof(Signup));
}
...
```
Some consumers want to be able to do something like `?pref=this&pref=that&pref=theOther` and have a pull of `pref` come …

Documentation for Deep Link Parsers Helper

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PullToRefreshListView/PullToRefreshListViewPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PullToRefreshListView/PullToRefreshListViewPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.xaml

This PR allows the developer to use custom objects instead of string for `Rull/ReleaseToRefreshLabel`. It extends the control by adding `PullToRefreshContent`, `ReleaseToRefreshContent`.
What has changed
---
- Add Property `PullToRefreshContent`, `ReleaseToRefreshContent`. 
- Add Obsolete to `PullToRefreshLabel`, `ReleaseToRefreshLabel`
- If a value is set to `PullToRefreshLabel` or `ReleaseToRefreshLabel` then the value is set to `PullToRefreshContent`, `ReleaseToRefreshContent` respectively
Compatability
----
It is possible to have either `PartDefaultIndicatorContent` (backward compatibility) or `PullAndReleaseIndicatorContent` as pull-down indicator.
For further versions `PartDefaultIndicatorContent` can be removed.
Because TextBlock is is still existing there should be no breaking …

PullToRefreshListView: Allow object content as pull/release-ToRefreshLabel

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/BladeControl/BladeCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/BladeControl/BladePage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/Blade.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/Blade.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.xaml
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeItem.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeItem.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeItem.cs
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
docs/controls/BladeControl.md

Addresses first three tasks for Issue #508
Additional Items addressed:

Blade changes to bring BladeControl to control "standards"

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookPage.xaml.cs
Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj
Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookPost.cs
Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookRequestSource.cs
Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
Microsoft.Toolkit.Uwp.Services/project.json
build/Microsoft.Toolkit.Uwp.Services.nuspec
docs/services/Facebook.md

https://github.com/Microsoft/UWPCommunityToolkit/issues/366
The service calls to Facebook are now paged - defaulting to a page size 20 and a maximum of 5 pages, which can be easily overridden.
Key changes - 
```
▪ Update to winsdkfb nuget with paging fix
▪ (Potential) breaking changes
FacebookService.Instance.GetUserAlbumsAsync(); now returns 
Task<IncrementalLoadingCollection<FacebookAlbumSource, FacebookAlbum>>
Not
Task<List<FacebookAlbum>>
FacebookService.Instance.GetUserPhotosByAlbumIdAsync(); now returns 
Task<IncrementalLoadingCollection<FacebookPhotoSource, FacebookPhoto>> 
Not
Task<List<FacebookPhoto>> 
FacebookService.Instance.RequestAsync(); now returns
Task<IncrementalLoadingCollection<FacebookRequestSource<T>, T>>
Not
Task<List<T>>
```
These generally will not require changes …

enabled paging support for fb service requests

---

Microsoft.Toolkit.Uwp.UI/Converters/EmptyCollectionToObjectConverter.cs
Microsoft.Toolkit.Uwp.UI/Converters/EmptyObjectToObjectConverter.cs
Microsoft.Toolkit.Uwp.UI/Helpers/BindableValueHolder.cs
Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
docs/helpers/BindableValueHolder.md

I extended converters the way we use them at work.
Also BindableValueHolder is very helpful thing when you use VisualState.Setters.

Improve the converters.

---

Microsoft.Toolkit.Uwp.UI/Converters/BoolToObjectConverter.cs
UnitTests/Converters/Test_BoolToObjectConverter.cs

* `targetType` in a `ConvertBack` operation of this class will always be something like `bool`, so `TrueValue` cannot be converted to that, it should be converted to the same type as the `value` parameter, since
they should match.
* Fix unit tests for BoolToObjectConverter

Fix BoolToObjectConverter.ConvertBack

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs
Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
docs/helpers/ImageCache.md

Reverting to using hash function to create filename.
This addresses issue #546

Revert to using Hash for Cached item file name without extension.

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/BladeControl/BladePage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/Blade.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeItem.Properties.cs

Ignore warnings for deprecated Blade properties. 
Move the BladeId property to the Blade class and mark as Deprecated

Blade warnings

---

Microsoft.Toolkit.Uwp.SampleApp/App.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DispatcherHelper/DispatcherHelperPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PullToRefreshListView/PullToRefreshListViewPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
docs/controls/PullToRefreshListview.md

Obsolete is actually not required. I updated the doc to explain the inner behavior
Control can then be use really simply with a simple string or with a more consistent control using the content control.

Remove obsolete from PullToRefreshListview

---

Microsoft.Toolkit.Uwp/Helpers/DispatcherHelper.cs

Fixing Dispatcher.AwaitableRunAsync Null problem
await function().ConfigureAwait(false) was throwing a null reference exception.
#608

Fixing Dispatcher.AwaitableRunAsync Null problem

---

Microsoft.Toolkit.Uwp/Helpers/DispatcherHelper.cs
docs/helpers/DispatcherHelper.md

This addresses two issues mentioned in #617.
1. Use fail fast strategy if the Func<Task> or Func<Task<T>> returns null instead of a task.
2. Also check for null in other occurances of the same problem.

Fix DispatcherHelper open issues

---

Microsoft.Toolkit.Uwp/Helpers/HttpHelper/HttpHelper.cs

Addressing #602
Expose the default constructor
Create additional constructor that allows passing pool size and http filter
Tested on ImageCache and Bing Search service to ensure that existing functionality hasn't changed

HttpHelper expose constructor

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs
Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsViewState.cs
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
docs/controls/MasterDetailsView.md

This adds a readonly property to the MasterDetailsView to allow an easy way to query whether or not the MasterDetailsView is in the open state. 
Fixes #660

Add IsDetailsOpen property to MasterDetailsView

---

Microsoft.Toolkit.Uwp.UI/Extensions/WebViewExtensions.cs
docs/helpers/WebViewExtensions.md

- WebViewExtensions was not working as it did not navigate to the new string when it was not empty.
- Fixed wrong heading in Documentation for WebViewExtensions

Fixed WebViewExtensions bug & documentation

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Bing Service/BingCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Bing Service/BingPage.xaml.cs
Microsoft.Toolkit.Uwp.Services/Core/DataProviderBase.cs
Microsoft.Toolkit.Uwp.Services/Core/DataProviderBase{TConfig,TSchema}.cs
Microsoft.Toolkit.Uwp.Services/Core/IDataService{T,U,V}.cs
Microsoft.Toolkit.Uwp.Services/Services/Bing/BingDataProvider.cs
Microsoft.Toolkit.Uwp.Services/Services/Bing/BingService.cs
Microsoft.Toolkit.Uwp.Services/Services/Twitter/TwitterDataProvider.cs
Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs

BingService now has the ability either to get all the requested data with a single call, or to incrementally load search results as the view requests them.
If this approach is OK, it can be extended also to TwitterService.

Add Incremental Loading supporto for BingService

---

build/Microsoft.Toolkit.Uwp.UI.Animations.nuspec

The normal map asset wasn't getting added to the nuget package. I've updated the nuspec to pull the file from the binary folder and place it in the expected location for it to compile and work.

Fixing issues with the normal map not being found via Nuget

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection/IncrementalLoadingCollectionCode.bind

The app displays code for copy/paste for developer. There is just a typo error for the "_people" list used in the IIncrementalSource

Minor fix for displayed code IIncrementalSource

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Twitter Service/TwitterPage.xaml
Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj
Microsoft.Toolkit.Uwp.Services/Services/Twitter/Tweet.cs
Microsoft.Toolkit.Uwp.Services/Services/Twitter/TwitterGeoData.cs
Microsoft.Toolkit.Uwp.Services/Services/Twitter/TwitterStatus.cs
docs/services/Twitter.md

The TwitterGeoData is deserialized if the "geo" element is populated on the response JSON.  I added the DisplayCoordinates to the TwitterGeoData since I didn't see a TwitterModel for the UI.  After I put in the double conversion I felt that it wasn't really needed, but I was just following the pattern for the CreationDate.  The TwitterGeoData could just expose the string data.

Added Latitude and Longitude to a returning Tweet if available.

---

Microsoft.Toolkit.Uwp.UI.Controls/BladeView/Blade.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeMode.cs
Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExFailedEventArgs.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExOpenedEventArgs.cs
Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsViewState.cs
Microsoft.Toolkit.Uwp.UI.Controls/MosaicControl/MosaicControl.cs
Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs
Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs

CS1591 rule has been disabled for this project, which means we are not validating if all public types and members have xmldoc in them.
Unfortunately at the moment we can't enable this rule as it will break the build given that some compiler generated types don't have proper xmldoc (thanks a lot Microsoft... not!)
I've enabled the rule temporarily and noticed that these are the types with missing documentation, so I'm now adding them back.

Adds missing documentation to public items

---

Microsoft.Toolkit.Uwp.UI.Animations/EasingType.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Fade.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Offset.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Rotate.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Scale.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.cs
Microsoft.Toolkit.Uwp.UI.Animations/InterpolationType.cs
Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj
docs/animations/Fade.md
docs/animations/Offset.md
docs/animations/Rotate.md
docs/animations/Scale.md

This commit adds a way to modify the easing function used in animations using an optional enum type which is named "InterpolationType" (See issue #500). I tried to document the things right but I don't have much experience in documenting. So please be considerate. I only documented in code with the xml-tags. I hope that someone else can make the proper documentation in (https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/docs) and modify the UWP Toolkit Samples app to show off the different easing functions.
Info: https://msdn.microsoft.com/en-us/windows/uwp/graphics/composition-animation#easing-functions

Added a way to modify the Easing Function used in animations (issue #500)

---

Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs

fixes #647 
BREAKING CHANGE: changed default behavior to be false for mouse
disabled mouse interaction when mouse is over scrollbar to prevent content scrolling in both directions
disabled mouse interaction if scrollviwer is not already on top to prevent unintended refreshing and fix issue with grouping

fixed pulltorefreshlistview refresh with mouse re: #647

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml
Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.xaml

This sets the `IsTabStop=False` property on some elements that were included in the tab sequence but which have no purpose being there.
Fixes #793

Fix tab navigation

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs

Should help to minimize header jumping while list is scrolling

removed round from expression animation

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

Fixes #877 by allowing the SelectedItem property to be set before the control has been loaded.

Allow SelectedItem to be set before control is loaded

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs
Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/SortDescription.cs
UnitTests/UI/Person.cs
UnitTests/UI/Test_AdvancedCollectionView.cs

This adds support to AdvancedCollectionView to sort on the object itself and also provides a way to add customer comparers if desired. This is done by adding three new overloads to `SortDescription`
- `SortDescription(SortDirection)` will use the IComparable that the object itself defines (if available)
- `SortDescription(SortDirection, IComparer)` provides a custom comparer for the object itself
- `SortDescription(string propertyName, SortDirection, IComparer)` provides a custom comparer for the property indicated
*Edit*
If this goes in 1.3, we can just use an optional parameter (if it were to go in 1.4, that's a breaking binary change), and have two overloads for the constructor:
- `SortDescription(SortDirection, IComparer = null)` will sort on the object itself
- …

Allow AdvancedCollectionView to sort on object itself and custom comparers

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs

Expose a way to request item from in-memory cache.
Possible solution for #910

Check if item exists in the in-memory storage

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Microsoft.Toolkit.Uwp.UI/Cache/InMemoryStorage.cs
Microsoft.Toolkit.Uwp.UI/Cache/InMemoryStorageItem.cs

Use ConcurrentDictionary instead of Dictionary in CacheBase
Use ConcurrentDictionary instead of OrderedDictionary in InMemoryStorage

CacheBase / InMemory Storage concurrency

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Members.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs
Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Microsoft.Toolkit.Uwp.UI/Cache/FileCache.cs
Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs

Add DecodePixelHeight, DecodePixelType and DecodePixelWidth properties to ImageEx
Modify CacheBase GetItemAsync to pass list of KeyValuePair objects to pass to generic type instantiation

ImageEx: DecodePixelHeight, DecodePixelType and DecodePixelWidth properties

---

Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveService.cs
Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageFile.cs
Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageFolder.cs

#883 - I've added two methods creating background download - one in *OneDriveStorageFile* and one in *OneDriveService*. I've also added cancellation in method responsible for getting items.
@EricVernie The *GetItemsAsync(...)* method of *OneDriveStorageFolder* allows to download up to 1000 items, due to SDK limit, otherwise it will throw exception. Another problem is that the request doesn't accept *Skip()*. In that case if you start with index 2 and want to download 1000 items - it will also throw exception. Do you have any ideas for that?

Added background download creation.

---

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs

Removed the UpdateRootGridMinWidth method from Shell.xaml.cs. This minimum width calculation for the RootGrid columns was messing things up, not only for the AdaptiveGridView page. It was causing a "cropping" effect on the left side of every page in smaller width screen resolutions, by setting minimum width for the Grid larger than the actual width. Removed it because the adaptive triggers on XAML page are doing the job.

Fixed #905

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml

This pull request corrects the behavior outlined in #954 where `OptionsListView` overlaps `ButtonsListView` when the view becomes too small to house both.  Additionally, it moves the scroll bar for the HamburgerMenu `PaneGrid` to the left side to ensure visibility when the menu is in its compact state.  `VerticalScrollBarVisibility` has also been set to `Auto` to only allow it to be visible when needed and to avoid cluttering the view unnecessarily.

Corrects scroll behavior for HamburgerMenu (#954)

---

docs/controls/HamburgerMenu.md

If you don't explicitly set a different foreground color for the children of HamburgerMenu, they'll inherit from their parent, which in this example is "white." If this can be confusing in basic cases (like a page that displays a text box) because if the page background is *also* white (which by default, it is) it'll seem like the children aren't rendering. 
Setting "foreground" fixes this.

Update HamburgerMenu docs

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RangeSelector/RangeSelectorPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.xaml

The RangeSlider on a touchscreen (mobile/tablet) was extremely difficult to use, because you had to drag the two thumbs who were very small for touch. I added a grid containing the thumb border in the thumb template, a bit bigger with a transparent background. Now it is a lot easier to manipulate the thumbs using touch. 
Also I modified the slider's sample page a bit because now the control requires more height and I had to adjust the alignment of the min/max indicators.

ux improvement for range selector

---

Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/AzureAuthToken.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/ErrorResponse.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/ITranslatorService.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/TranslatorService.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/TranslatorServiceException.cs

TranslatorServiceException is thrown when an error occurs while obtaining the service access token. Its Message property contains the error reason retrieved from the service.
The documentation has been updated removing some typos and providing better explanation of exceptions.

Add TranslatorServiceException and better documentation

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/HamburgerMenu/HamburgerMenuCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/HamburgerMenu/HamburgerMenuPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.HamburgerButton.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml

Added the HamburgerVisibility property as discussed in #1019.

Add HamburgerVisibility property

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MarkdownTextBlock/MarkdownTextBlockPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Display/XamlRenderer.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.xaml

I thought it would be cool to allow changing the foreground brush for the headers inside the markdown textblock.

Add foreground for markdown textblock header 1 through 6

---

Microsoft.Toolkit.Uwp/Helpers/ColorHelper.cs
UnitTests/Helpers/Test_ColorHelper.cs

When using `ColorHelper` to convert colors to HSL, I noticed that the lightness value returned wasn't exactly right. I read through the conversion code and found a small error in the lightness calculation. Since I was close, I took a glance at the HSV conversion code and noticed that the saturation was calculated using the HSL method rather than the HSV method, so I fixed that as well.
I've updated the unit tests so that they cover the errors they weren't catching before. If you want to double-check my changes, this Wikipedia page is pretty helpful: https://en.wikipedia.org/wiki/HSL_and_HSV

Fix ColorHelper HSL and HSV calculations

---

Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastActivationOptions.cs
Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastContent.cs
Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastHeader.cs
UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs

Windows does not support this, hence the property does nothing. Adding obsolete tag (and adding pragmas to ignore the obsolete warnings within our own code when we use the property)

Deprecate toast AfterActivationBehavior

---

Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Adaptive/AdaptiveProgressBar.cs
Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Adaptive/Elements/Element_AdaptiveProgressBar.cs
UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs

The toast progress bar -> XML code had a few mistakes due to us adding this element early before things were finalized for the Creators Update :)
* XML element should be <progress> rather than <progressBar>
* Status is a required property
I've made these changes to the code and the tests, and also validated that you can successfully send a progress bar toast on the latest Insider build using the Notifications DLL with these changes.

Fix toast progress bar

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/BehaviorBase.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Blur.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/CompositionBehaviorBase.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/CompositionBehaviorBase.nongeneric.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Fade.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/FadeHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Light.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Offset.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Rotate.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Scale.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj

Introduce BehaviorBase and let FadeHeaderBehavior derive from this base

---

Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeView.cs

Not sure if this is the supposed proper fix, but I've tried in my app and it works fine.
Without the ```UpdateLayout();``` it only works randomly, I guess it takes time for the UI to refresh before we can scroll?

[BladeView] proper scroll for Data binding; fixing #801

---

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml

The content of the Hamburger Menu does not look well on mobile. So, I changed the display mode to CompactOverlay instead of CompactInline in small window screen.

design(sample): change display mode of hamburger menu based on window width

---

Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastContent.cs
UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs

Limit it to 3 decimal places, otherwise the toast breaks when sent to the notification platform.
#1073

Fix toast displayTimestamp from including too many decimals

---

Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs

This is a suggestion, because I noticed that the native slider supports this functionality, when you tap/click somewhere inside the slider area the thumb is moved to this position. I added a tap event handler, it moves the closest thumb to the tap position.

add tap handler for rangeselector and move the closest thumb to position

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Account for the padding when calculating the width of the panel.
Addresses #1078

Remove AdaptiveGridView padding from width for layout calculation

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Expander/ExpanderPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Expander/ExpanderXaml.bind
Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml
docs/controls/Expander.md

Linked to #924 
I set the Background so it is used by the entire control. I updated the sample page and the docs too.
So, here is the new behavior of the Background color : 
* cover the entire control (both Header and Content)
* the Content background can be changed if the root UIElement of the Content has a Background
* of course the Header background changed based on VisualStates because it acts as a "button"
I did not updated the VisualStates of the control and I don't know if I have to.

fix(Expander): set Background to the entire control

---

Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastButtonDismiss.cs
Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastButtonSnooze.cs
UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs

Action Center displays the images on these system activation buttons
now, so devs need to be able to assign them!
Fixes #1121

Add ImageUri to ToastSnooze/ToastDismiss buttons

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GridSplitter/GridSplitter.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GridSplitter/GridSplitterPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Helper.cs

Fixes the issue as described in #1156.
Broken behavior:
Fixed behavior:

Fix GridSplitter behavior when using MaxWidth on ColumnDefinition

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

Changes to when the MasterDetailsView updates the back button visibility. It will now only update the visibility if in the ViewState is MasterDetailsViewState.Details, or if it is changing from MasterDetailsViewState.Details. 
The control also will keep track if the back button was visible before it changes it when going into the Details state. If the MasterDetailsView is going from MasterDetailsViewState.Details, it will set the back button visibility to whatever is was previously. 
Fixes ##939 and possibly #906. Tested #906 after fixing this and I cannot reproduce

Only show back button when changing from collapsed details view

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ImageEx/ImageExPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.Members.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.xaml

Use Rectangle instead of Border for RoundImageEx
This should simplify support for DropShadowPanel as shape supports GetAlphaMask
Issue #1178

Use Rectangle instead of Border for RoundImageEx

---

Microsoft.Toolkit.Uwp.UI.Controls/TextBoxRegex/TextBoxRegex.cs

Changing max RegexTextbox Email Validation from 3 Character domain name to unlimited.

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

When initial visibility of MasterDetailsView is collapsed, Loaded gets called before template is applied, and an exception is thrown. This fix should resolve the issue.

MasterDetailsView: fixed loaded bug

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

Fixes https://github.com/Microsoft/UWPCommunityToolkit/issues/1197
(and likely https://github.com/Microsoft/UWPCommunityToolkit/issues/745 as well)

Always set _detailsPresenter.Content even if SelectedItem is null

---

Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/WrapPanel.Data.cs
Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/WrapPanel.cs

Use `int` as backing field of `U` and `V`, see #1085

Fix bug of arrange for WrapPanel

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml

Using Foreground to set the hamburger button color blocks theme inheritance in the content frame. This PR adds a PaneForeground property that targets the button but not the content frame, and defaults to the Foreground value so it won't break current Foreground usage.

Added HamburgerMenu.PaneForeground to address theming problem

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml

This allows the HamburgerMenu to act more closer to the new [NavigationView](https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/navigationview) in the Fall Creators Update.

HamburgerMenu: update template to keep options visible

---

Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs
Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.xaml

ScrollHeader: Removed tabstop from ScrollHeader

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs

Previous AdvancedCollectionView compare implementation ignored inherited properties.  
Consider the source code below.  Creating an AdvancedCollectionView based on Employee and creating a SortDescription for "Name" would generate a null exception since Employee does not declare Name, it inherits it from Person.
public class Person
{
public string Name { get; set; }
}
public class Employee : Person
{
}
// Set up the original list with a few sample items
var oc = new ObservableCollection<Employee>
{
new Employee { Name = "Staff" },
new Employee { Name = "42" },
new Employee { Name = "Swan" },
new Employee { Name = "Orchid" },
new Employee { Name = "15" },
new Employee { Name = "Flame" },
new Employee { Name = "16" },
new Employee { Name = "Arrow" },
new Employee { Name = "Tempest" },
new …

Fixed issue where Compare ignored inherited properties.

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Display/IImageResolver.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Display/XamlRenderer.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/ResolveMarkdownImageEventArgs.cs
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Microsoft.Toolkit.Uwp.UI.Controls/project.json
docs/controls/MarkdownTextBlock.md

Hi, this is the PR for issue #1092  
There are still 2 things we might change here:
- The name of the event is **ResolveImage**. Is this fine or can we find something that fits better?
- Whether this event should be called for all images, or just for the ones that fail with ```new BitmapImage(new Uri(url));```
Oh, and I just remember another thing:  
Previously it would not try to create the image if the URL started with something else than ```http``` or ```ms-app```.
Right now I have removed that line.  
But that might lead to some errors if you try to load a markdown document with a image that cannot be resolved with ```new BitmapImage(new Uri(url))```.

Add MarkdownTextBlock.ResolveImage event

---

Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs

Don't propagate the PointerReleased event when the control is in Interactive mode. This makes the control behave like other XAML input controls (like TextBox) after manipulating the value. Releasing the mouse pointer will just set the value and will e.g. NOT trigger row selection when the RadialGauge is used inside a ListView data template.

RadialGauge PointerReleased handling

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Translator Service/MicrosoftTranslatorPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Translator Service/MicrosoftTranslatorPage.xaml.cs
Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/ITranslatorService.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/ServiceLanguage.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/TranslatorService.cs
Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/TranslatorServiceException.cs

TranslatorService now contains a new method that can be used to automatically get friendly language names.

Add method to get translation language names

---

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExBase.cs
Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs
Microsoft.Toolkit.Uwp/Helpers/Network/NetworkHelper.cs
UnitTests/Helpers/Test_WeakEventListener.cs

Using EventArgs.Empty instead of creating new EventArgs empty instances.

---

Microsoft.Toolkit.Uwp.UI.Controls/Menu/MenuItem.cs

Show the menu directly below the button and align the left edges
Fixes #1258 and #1259

Fix menu alignment

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.cs

Addressing #1273 
Removed Stretch defaults set in constructor

Remove Stretch overrides in RoundImageEx constructor

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Menu/Menu.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Menu/MenuPage.xaml
Microsoft.Toolkit.Uwp.UI.Controls/Menu/Menu.xaml
Microsoft.Toolkit.Uwp.UI.Controls/Menu/MenuItem.cs

re #1293, allows having other content than string inside a MenuItem

Menu: changed MenuItem Header to type object

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Properties.cs

`<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
<toolkit:HamburgerMenu x:Name="HamburgerMenu"/>
</Grid>`
`public MainPage()
{
this.InitializeComponent();
var m = HamburgerMenu.OpenPaneLength;
}`
This code in empty project with toolkit 1.5 will throw an exception.
System.InvalidCastException: 'Unable to cast object of type 'System.Int32' to type 'System.Double'.'

Crash in getter HamburgerMenu.OpenPaneLength with default value

---

Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs

Wire up DropShadowPanel Content's size change to ensure that shadow is updated correctly.
Address #1111 and #1299

DropShadowPanel Content wireup size changed

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs
Microsoft.Toolkit.Uwp/Helpers/StorageFileHelper.cs
Microsoft.Toolkit.Uwp/Helpers/StreamHelper.cs

If a method is `IAsync*`, one should not do `.AsTask()` just to call `.ConfigureAwait(false)` on it.
Platform calls are async by nature and will (might?) run on a separate thread that will return to the calling thread, no matter whats the configuration of the await.

Removes all .AsTask().ConfigureAwait(false) calls

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Inlines/HyperlinkInline.cs
UnitTests/UnitTests.MarkdownTextBlock/Parse/MarkdownLinkTests.cs

Markdown Hyperlink Inline parser respects SIP formatted Schema links.

Add SIP Schema support for MarkDownLink

---

Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastActivationOptions.cs
Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastContent.cs
Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastHeader.cs
UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs

Toast AfterActivationBehavior is now available in Insider builds 16251 and higher for the Fall Creators Update! You can use AfterActivationBehavior to keep your toast around in a "pending update" state while a background task gets fired off, and then your background task should update the toast when the operation is complete. Great for things like Pause/Resume buttons on toast download progress.
This pull request simply removes the Obsolete tags we had to add. We previously accidentally added this API before it was available, hence we added Obsolete tags previously.

Re-enable toast AfterActivationBehavior

---

docs/animations/Expressions.md

Doc(Expression): Adding all info from original doc  

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.cs

Noticed that in the sample app if you changed the HeaderedTextBox to Horizontal and then switched back to the same page it wouldn't re-initialize the margin from the Visual State when the control was retemplated:
This fix calls the Visual State Manager update function to adjust to the current orientation on templating.

Ensure HeaderedTextBox Visual State Orientation is set to Initial Orientation

---

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.cs

The carousel control raised an exception when :
* Changing the itemsSource to NULL
* Changing the itemsSource to a smaller list, when an item with a high
index was selected
* Setting SelectedIndex to -1
The behaviour was incorcect when setting SelectedItem to null.
These scenarios now work properly.

Fixed multiple issues in the Carousel control

---

Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs
Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs

We already had checks for the Visual Studio Designer, but it turns out, they didn't work. Moving the checks up one level to wrap the methods calling the Composition APIs seems to work.

Fixes for DropShadowPanel and RadialGuage in the VS designer

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs

Use HttpClient GetStreamAsync instead of GetAsync to fix issue with artefacts on images when caching is enabled with ImageEx

CacheBase tweak

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs
docs/controls/InAppNotification.md

fix #1415 
@bkaankose I tried to use CancellationToken but it added so much code and it is seemed a little messy to me. The unique id do the trick but yes the Task.Delay is not cancelled immediately...

fix(InAppNotifications): use timer to detect notification dismiss event after timeout

---

Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs

ImageCache - mark _instance field as ThreadStatic
**Underlying issue.**
0 | kernelbase | RaiseFailFastException | 0x74
-- | -- | -- | --
1 | dcomp | Microsoft::WRL2::FailFast::Do | 0x2E
2 | dcomp | Microsoft::WRL2::FailFast::ForHR | 0x6A
3 | dcomp | Windows::UI::Composition::SurfaceBindPoint::AttachSurface | 0x28D37
4 | dcomp | Windows::UI::Composition::CompositionSurfaceBrush::Api::put_Surface | 0x15A
5 | windows_ui_xaml | WUCBrushManager::GetSurfaceBrush | 0x152
6 | windows_ui_xaml | VisualContentRenderer::RenderPrimitive | 0x335
7 | windows_ui_xaml | VisualContentRenderer::GeneralImageRenderContent | 0x236
8 | windows_ui_xaml | BaseContentRenderer::ImageRenderContent | 0xCD
_ACCESSDENIED_FAIL_FAST_EXCEPTION_80070005_dcomp.dll!Windows::UI::Composition::CompositionSurfaceBrush::Api::put_S …

ImageCache - mark _instance field as ThreadStatic

---

Microsoft.Toolkit.Uwp.UI.Animations/ReorderGridAnimation.cs

Due to the way XAML handles item container recycling in virtualized lists, simply setting the ImplicitAnimations property on the backing visual to null in the recycled case produces undesirable behavior when adding and removing items. Without getting too into XAML implementation details, containers that will be recycled are stored off screen and when they are reused for a new item the item will fly into their new position from the upper left. The solution is to force XAML to disable the implicit animations for that commit by poking the UIElement's Z-Index. We planned to fix the sample in the WindowUIDevLabs that also has this issue but that hasn't made it to the repo yet.

Poke UIElement Z-Index when a container is being recycled in ReorderGridAnimation

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs
Microsoft.Toolkit.Uwp/Helpers/StorageFileHelper.cs
Microsoft.Toolkit.Uwp/Helpers/StreamHelper.cs

This reverts commit 4413914f554c6c68224515c6b834c330f8770b7b.
I was wrong when I made this change in the first place, so I'm now reverting these changes. Please check [here](https://github.com/Microsoft/UWPCommunityToolkit/pull/1327#issuecomment-326114913) for more information.
These changes are based on the `staging` branch.

Revert "Removes all .AsTask().ConfigureAwait(false) calls"

---

Microsoft.Toolkit.Uwp.DeveloperTools/Microsoft.Toolkit.Uwp.DeveloperTools.csproj
Microsoft.Toolkit.Uwp.DeveloperTools/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Microsoft.Toolkit.Uwp.UI.Controls/VisualStudioToolsManifest.xml

Added VSToolsManifest so controls will show up in the toolbox 

---

Directory.Build.props
Directory.Build.targets

The legacy project system (IDE and Design Time builds), always includes items that have a false condition. The workaround is to use a Choose/When construct.
This updates the directory.build.props/targets to use the Choose/When construct so the legacy projects don't get confused.

Move conditionals into Choose When for better legacy project system support

---

build/build.cake

Switched to Correct DotNet Alias, built Arguments with Argument Builder.
If this doesn't work,
switch out lines 191-200 for:
```C#
var arguments = new ProcessArgumentBuilder()
.AppendQuoted(signClientAppPath)
.Append("sign")
.AppendSwitchQuoted("-s", signClientSecret)
.AppendSwitchQuoted("-c", signClientSettings)
.AppendSwitchQuoted("-n", name)
.AppendSwitchQuoted("-d", name)
.AppendSwitchQuoted("-u", address);
var result = StartProcess("dotnet", new ProcessSettings {  Arguments = arguments });
if(result != 0)
{
throw new InvalidOperationException("Signing failed!");
}
```

Fix for Sign Client in Cake Build

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Carousel/CarouselCode.bind

Issue: #1541
```
[ ] Bugfix
[ ] Feature
```
Currently the sliders for Margin and Rotation X,Y and Z only support positive values. See #1541 for more info.
I added support for negative values in Margin and Rotation sliders.
```
[ ] Yes
[x] No
```

Carousel Sample - Allow negative values for margin and rotation

---

Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Options.cs

This fixes #1501. 
If the control is unloaded and then loaded again (e.g. when using page caching), a second cursor handler was created although one already existed. This is fixed now.

GridSplitter: Fix broken cursor handling after unload+reload of control

---

readme.md

```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Link to [PrinterHelper](http://docs.uwpcommunitytoolkit.com/en/master/helpers/PrinterHelper/) was obviously wrong, resulting in 404 and should be [PrintHelper](http://docs.uwpcommunitytoolkit.com/en/master/helpers/PrintHelper/).
However, other links to www.uwpcommunitytoolkit.com were randomly (sometimes, not always) giving me 404, while there is no such problem with docs.uwpcommunitytoolkit.com.
- [ x ] Docs have been added / updated (for bug …

Fixed broken links in readme

---

Microsoft.Toolkit.Uwp.UI/Extensions/Tree/LogicalTree.cs

Issue: #
```
[x] Bugfix
[ ] Feature
```
When GetContentControl extension method returns null, FindChildren<T> throws NRE trying to iterate null in foreach loop.
No NullReferenceException.
```
[ ] Yes
[x] No
```

Fixes NullReferenceException when GetContentControl method returns null.

---

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml

This feature does allow any header like in [HeaderedContentControl.Header](https://msdn.microsoft.com/en-us/library/system.windows.controls.headeredcontentcontrol.header(v=vs.110).aspx) by changing `Expander.Header` from `string` to `object`
~~~
<controls:Expander x:Name="Expander1" VerticalAlignment="Top" Margin="0,0,0,10" 
Foreground="White"
Background="Gray"
IsExpanded="False"
ExpandDirection="Down">
<controls:Expander.Header>
<StackPanel Orientation="Horizontal" >
<Image Source="ms-appx:///Assets/People/shen.png" Height="24" Width="24"></Image>
<TextBlock Text="Shen" VerticalAlignment="Center"></TextBlock>
</StackPanel>
</controls:Expander.Header>
<Grid Height="250">
<TextBlock HorizontalAlignment="Center"
TextWrapping="Wrap"
Text="This is the content"
VerticalAlignment="Center" …

Change Expander.Header from string to object

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs
Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/IAdvancedCollectionView.cs
UnitTests/UI/Person.cs
UnitTests/UI/Test_AdvancedCollectionView.cs
docs/helpers/AdvancedCollectionView.md

Issue: https://github.com/Microsoft/UWPCommunityToolkit/issues/1128
(this is not meant to tackle the grouping that is also requested in the above issue)
I guess this is only a feature, feel free to correct me.
```
[ ] Bugfix
[x] Feature
```
With the current behavior you need to call `Refresh` if you change any references that are relied on by the Filter.  Also, if properties that are sorted/filtered on are changed, you need to call `Refresh` manually.  `Refresh` is also very heavy handed and basically acts as if the source has been reset. …

Add LiveShaping to AdvancedCollectionView

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.cs
Microsoft.Toolkit.Uwp.UI.Controls/InlineCollectionWrapper.cs

As in WPF, UWP `HeadededTextBlock` should have the same behavior as `TextBlock`.
This is because as I saw the `HeaderedTextBlock` control I wanted to use it with `Run` immediately. But I saw that it does not exist. As `HeaderedTextBlock` has the name `TextBlock` inside I expected the same behavior. With this pull request it has.
~~~
<HeaderedTextBlock Header="Header>
<Run Text="Normal"/>
<Italic>
<Run Text="Italic"/>
</Italic>
<Bold>
<Run Text="Bold"/>
</Bold>
<Run Text="Red" Foreground="Red"/>
</HeaderedTextBlock />
~~~
**NONE**

HeaderedTextBlock does now support Inlines as TextBlock

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs

Issue: #1553 
```
[X] Bugfix
[ ] Feature
```
See #1553 
When an item is focused near the header, the ScrollViewer will  scroll to make sure item is not hidden by the header.
```
[ ] Yes
[X] No
```

ScrollHeader fix for hidden focused elements

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Issue: #1551 
```
[X] Bugfix
[ ] Feature
```
ItemWidth on AdaptiveGridView can be a fraction too big and cause the panel to overflow elements to next row on certain panel widths
Made sure ItemWidth does not cause the item DesiredSize to overflow the panel
```
[ ] Yes
[x] No
```

ItemWidth fix for AdaptiveGridView

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.xaml

Issue: #1328
Setting Visibility of ProgressRing to Collapsed by default.
Modify VisualState to make ProgressRing Visible when Loading.
Removed un-necessary modification in Loaded state.
```
[x] Bugfix
[ ] Feature
```
The ProgressRing is always visible with only IsActive being toggled.
If large number of ImageEx controls are used, LayoutCycleException is encountered
- [x ] Tested code with current [supported SDKs](../readme.md#supported)
Setting Visibility of ProgressRing to Collapsed by default.
Modify VisualState to make …

ImageEx ProgressRing Visibility toggled through VisualState

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Blocks/TableBlock.cs
docs/animations/Scale.md

Considering Carriage Return and Line Feed instead of only Linefeed when parsing MarkdownTable Data.
Issue: #1516
```
```
Currently it ignores Carriage Return if they are coupled as `\r\n`
Now it will not ignore when Carriage Return and Line Feed are coupled like `\r\n`
```
```

Fixing `MarkdownTextBlock` Parsing Table Issue

---

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml

Issue: #1583
```
[x] Bugfix
[ ] Feature
```
Fixes issue where the Expander control does not respect the Border* properties 
The Expander control will now honor the Border* properties
```
[ ] Yes
[x] No
```
This PR changes the Style of the Expander by replacing a Grid with a Border

Change the style of the Expander to respect the border properties

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ImageEx/ImageExCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ImageEx/ImageExPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.xaml
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExBase.Members.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.Members.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.cs
docs/controls/ImageEx.md

Issue: #1391 
```
[ x ] Bugfix
[ x ] Feature
[ x ] Refactoring (no functional changes, no api changes)
[ x ] Documentation content changes
[ x ] Other... Please describe:  Deprecation
```
Round Image uses its own custom brush and behaves differently than Image/ImageEx in layout (Issue #1391)
- [ x ] Tested code with current [supported SDKs](../readme.md#supported)
- [ x ] Docs have been added / updated (for bug fixes / features)
- [ x ] Sample in sample app has been added / updated (for bug fixes / features)
- [ x ] Tests for the changes have been added (for bug fixes / features) (if applicable) …

ImageEx CornerRadius RS3 Support and RoundImageEx Obsolete Notice

---

Microsoft.Toolkit.Uwp.UI.Animations/Effects/AnimationEffect.cs

Issue: #1410 
Bug Fix
```
[x ] Bugfix
[ ] Feature
```
stops saturation overriding itself incorrectly #1410 
- [x ] Tested code with current [supported SDKs](../readme.md#supported)
Fixes the issue
```
[ ] Yes
[x] No
```

Fixing bug with saturation being overriden

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs

Issue: #1605 
Only remove items that were selected for removal from the cache
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
I found this issue while using the Cache in our app. Unfortunately, I was not yet able to run, adjust or fix any of the UWP-toolkit tests, because I ran out of time at the moment. Sorry 4 that!

Fix for #1605, only remove items that were selected for removal from the cache

---

Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs

Issue: #1034 #1380 #887
```
[X] Bugfix
[ ] Feature
```
See #1034 #1380 #887 
* Mouse and touch have the same behavior now when pulling down
* When *IsPullToRefreshWithMouseEnabled* set to true, the mouse will scroll the listview
* System manipulations (such as swiping on a pivot) works even when mouse pull to refresh is enabled
```
[ ] Yes
[X] No
```

Tweaked touch and mouse pull to refresh behavior to match, can now scroll with mouse

---

Microsoft.Toolkit.Uwp.UI.Controls/RotatorTile/RotatorTile.cs
docs/controls/RotatorTile.md

Issue: #1597 and #1411 
```
[x] Bugfix
[ ] Feature
```
See issues #1597 and #1411
The RotatorTile no longer flickers
```
[ ] Yes
[x] No
```

RotatorTile fix for flickering

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/BladeView/BladeCode.bind
Microsoft.Toolkit.Uwp.UI.Controls.Design/BladeItemMetadata.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeItem.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeView.xaml
docs/controls/BladeView.md

Issue: #1218
Add default foreground properties to the default style
```
[x] Bugfix
[ ] Feature
```
Weird bug by the style not defining the foregrounds
Foregrounds are now part of the dele
```
[ ] Yes
[x] No
```
Marked the `Title` property as obsolete in favor of the `Header` property from the Expander

BladeItem fix for #1218

---

Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionNodes/ExpressionNode.cs

Issue: #1622
```
[x] Bugfix
[ ] Feature
```
ExpressionNode creates the wrong types
ExpressionNode now creates the proper type
```
[ ] Yes
[x] No
```

Fix types being created

---

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
UnitTests/Helpers/Test_StorageHelper.cs
UnitTests/UnitTests.csproj

Issue: #1598
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Tweak to ensure that primitive / string types aren't processed through Json Serialiser.
```
Every value stored by StorageHelper is serialised to / deserialised from Json. This is not needed for primitive / string types.
```
[ ] Yes
[ ] No
```

Ensure that primitive / string types aren't serialised to / deserialised from Json.

---

Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs

Issue: #
```
[x] Bugfix
[ ] Feature
```
Possible NRE when AppUptime does not have value stored in local app settings
No NRE
```
[ ] Yes
[x] No
```
Possible fix for https://github.com/Microsoft/UWPCommunityToolkit/issues/1598

Fix NRE when there's no value for AppUptime in local settings

---

Microsoft.Toolkit.Uwp.UI.Controls/Menu/MenuItem.cs

Change MenuItem to inherit from HeaderedItemsControl instead of ItemsControl. Remove the Header and HeaderTemplate properties from MenuItem
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
MenuItem inherits from ItemsControl and has a local Header and HeaderTemplate property
MenuItem now inherits from HeaderedItemsControl and takes advantage of it's Header and HeaderTemplate properties
```
[ ] Yes
[x] No
```

Change MenuItem to inherit from HeaderedItemsControl

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs
UnitTests/UI/Test_AdvancedCollectionView.cs

Fix exception caused by filtering back in removed items using RefreshFilter and Live shaping. Also fix incorrect ordering bug when inserting new items to ACV.
Issue: #
https://github.com/Microsoft/UWPCommunityToolkit/issues/1626
```
[x] Bugfix
[ ] Feature
```
https://github.com/Microsoft/UWPCommunityToolkit/issues/1626
No exception get's thrown and view respects the ordering of the source when there is no sort applied.
```
[ ] Yes
[x] No
```

Fix some ACV bugs

---

Microsoft.Toolkit.Uwp.SampleApp/Models/PropertyDescriptor/ValueHolder.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Carousel/CarouselPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ParallaxService/ParallaxPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Toast/ToastPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WeatherLiveTileAndToast/WeatherLiveTileAndToastCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WeatherLiveTileAndToast/WeatherLiveTileAndToastPage.xaml.cs

Issue: #1656
```
[x] Bugfix
[ ] Feature
```
PropertyChange notifications were firing for values that were the same.
Only fire changes on value changes (not ref change).
Clean-up dead code.
```
[ ] Yes
[x] No
```
The DataContext is set automatically by the sample engine now, so removed code from samples which did it manually from before.

Sample App value fixes for #1656

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/FadeHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.Constants.cs
Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs

Issue: #1659
```
[x] Bugfix
[ ] Feature
```
Panels using the behaviors without the ScrollHeader will have the correct z-ordering
```
[ ] Yes
[x] No
```

Moved zindex ordering for ScrollHeader to the behaviors

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollHeader/ScrollHeaderCode.bind
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/FadeHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs
Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs

Issue: #1659 
ScrollHeader and Behaviors tweak
```
[] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
ScrollHeader requires TargetListView to be set. It should not be mandatory as ScrollHeader is set to ListView / GridView header.
Make TargetListViewBase in ScrollHeader optional
Mark TargetListViewBase as obsolete
Tweak FadeHeaderBehavior, QuickReturnHeaderBehavior and StickyHeaderBehavior
```
[ ] Yes
[x] No
```

ScrollHeader and Behaviors tweak

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Menu/MenuPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/Menu/MenuItem.cs

Issue: #1680
```
[X] Bugfix
[ ] Feature
[X] Sample app changes
```
If a MenuItem has been already initialized, inserting a new element in its Items collection by using Insert instead of Add doesn't respect the specified index; the new item gets added at the end instead.
The new menu item gets added at the specified index, and not at the last position.
```
[ ] Yes
[X] No
```
Sample app has been updated so MenuItem page now has two buttons - one for adding new items at the end of the menu and another one …

Fix for MenuItem items not being inserted in the proper order when using Items.Insert instead of Items.Add

---

Microsoft.Toolkit.Uwp.Connectivity/Network/ConnectionInformation.cs
Microsoft.Toolkit.Uwp.Connectivity/Network/NetworkHelper.cs

Issue: #1645
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
There are no exception handlers and passing null when initialising the NetworkHelper isn't ideal.
Add UpdateConnectionInformation method to NetworkHelper
Add try catch to UpdateConnectionInformation
Lock NetworkHelper.ConnectionInformation before calling update.
Add Reset method to ConnectionInformation
Tweaks to ConnectionInformation.UpdateConnectionInformation method
```
[ ] Yes
[x] No
```

NetworkHelper updates to fix crashes logged

---

Microsoft.Toolkit.Uwp.UI.Controls/Menu/Menu.xaml

Issue: #1694 
- Bugfix
Changing the `Padding` property of a `MenuItem` does nothing - the padding of the control reverts to default.
Changing the `Padding` propery of a `MenuItem` properly reflects the change to the control style.
```
[ ] Yes
[X] No
```

MenuItem padding

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenuNavViewTemplate.xaml

Issue: #1644
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Added empty HeaderTemplate to NavigationView

---

Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionNodes/ScalarNode.cs

More info in #1707 .
Summarized it means there is a major bug in the animation expression compositor on cultures that don't use a `.` as decimal separator.

Use explicit invariant culture to ensure correct float notation when creating animation expressions

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Light/LightBehaviorCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Light/LightBehaviorPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Light/LightBehaviorXaml.bind
Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Light.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Light.cs
docs/animations/Light.md

Issue: #
#1673 
```
[ ] Bugfix
[X] Feature
```
Defaults to white
A new Color property which allows you to change the color of the light.
```
[ ] Yes
[X] No
```

#1673 Adding a Color property to Light

---

Microsoft.Toolkit.Uwp.SampleApp/App.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/HamburgerMenu/HamburgerMenuPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenuItemInvokedEventArgs.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenuTemplate.xaml

Issue: #
```
[x] Bugfix
[ ] Feature
```
Even though the `HamburgetMenuItemInvokedEventArgs` is marked as obsolete, it should not have this typo.
The fixed typos
- `HamburgetMenuItemInvokedEventArgs -> HamburgerMenuItemInvokedEventArgs`
- `HambugerMenuItemStyle` -> `HamburgerMenuItemStyle`
```
[x] Yes
[ ] No
```
This is a breaking change if someone uses the `ItemInvoked` event.

Fix typo in HamburgetMenuItemInvokedEventArgs

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Menu/Menu.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Menu/MenuPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/Menu/Menu.xaml
Microsoft.Toolkit.Uwp.UI.Controls/Menu/MenuItem.cs

Issue: #1696
```
[ ] Bugfix
[X] Feature
```
When setting `IsEnabled` to false on a `MenuItem`, the underlying `Button` uses default values for styling.
`MenuItem` has a new `Disabled` state that can be styled.
```
[ ] Yes
[X] No
```

MenuItem disabled state

---

Microsoft.Toolkit.Uwp.UI.Controls/TextToolbar/TextToolbarStrings.cs
Microsoft.Toolkit.Uwp.UI.Controls/TextToolbar/ToolbarItems/Common/CommonButtons.Events.cs

Issue: #1736
```
[x] Bugfix
[ ] Feature
```
App crashed if we create a hyperlink with empty label or url in TextToolbar control
App crash issue fixed and will show warning validation dialog for the empty label and url.
```
[ ] Yes
[x] No
```

Issue fix #1736, Empty Hyperlink validation in TextToolbar

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs
UnitTests/UI/Test_AdvancedCollectionView.cs

Fix null reference exception caused by assuming a filter is always set. Now when we evaluate an item's property changed event, we do not assume that a filter has been set.
Issue: #
https://github.com/Microsoft/UWPCommunityToolkit/issues/1686
```
[x] Bugfix
[ ] Feature
```
https://github.com/Microsoft/UWPCommunityToolkit/issues/1686
No exception is thrown.
```
[ ] Yes
[x] No
```

Fix live shaping null ref bug when no filter is set

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.cs
Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenuTemplate.xaml

Issue: #1730
```
[x] Bugfix
```
See Issue: #1730
The initial item is selected when the control loads.
For the non-NavView template. No idea why the SelectionMode was causing the selectedItem to be set to null on loading. I verified the issue with a minimal repro (templated control with an empty listview), seems like a platform bug, especially since the default value for SelectionMode is the same.
For the NavView template, the control was attempting to set the value of SelectedItem before OnApplyTemplate.
```
[ ] Yes
[x] No
```

Fix for HamburgerMenu SelectedItem on control loading

---

docs/helpers/BackgroundTaskHelper.md

Issue: Fixes a small typo in doc for `Background Task` where it refers `Single-Process Model` as `MPM` instead of `SPM`
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
The doc says `Using MPM (Single-Process Model) is the new and simple way of using Background Task` instead of `Using SPM (Single-Process Model) is the new and simple way of using Background Task`
- [] Tested code with current [supported SDKs](../readme.md#supported)
- [] Docs have been added/updated which fit [documentation …

Fix typo where doc refers Single-Process Model as MPM instead of SPM

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveHeightValueConverter.cs
UnitTests/Converters/Test_AdaptiveHeightValueConverter.cs
UnitTests/UnitTests.csproj

Issue: #1613
```
[x] Bugfix
[ ] Feature
```
Height of the items does not match the requested height
Height of items should now match the requested height
```
[ ] Yes
[x] No
```

Fix AdaptiveGridView OneRowMode height

---

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.cs
Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.xaml
Microsoft.Toolkit.Uwp.UI.Controls/Carousel/CarouselItem.cs

Issue: #1233
```
[x] Bugfix
[x] Feature
```
The Carousel currently creates ContentControl elements to host content which makes it hard to change the style of the items. In particular are selection and pointer visual state
Carousel now creates a CarouselItem control for each item. The CarouselItem has visual states for pointer and selection. These states are empty to provide the same functionality that is currently in place.
```
[ ] Yes
[x] No
```

Add CarouselItem control

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Issue: #1737
```
[x] Bugfix
```
Application will crash when HorizontalAlignment is set to anything but stretch
Do not subtract one from the new width. This causes the SizeChanged event to endlessly fire when the HorizontalAlignment is not Stretch because the width is continually shrinking.
```
[ ] Yes
[x] No
```
Related to and caused by #1552

AdaptiveGridView fix when HorizontalAlignment is not stretch

---

Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.xaml

Issue: #1769
```
[x] Bugfix
[x] Feature
```
Style of the RangeSelector is not consistent with the style of the Slider control
Style now is consistent with that of the Slider. Thumbs match theme color and will rest in the same position
```
[ ] Yes
[x] No
```

Update style of RangeSelector to match the style of Slider

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveHeightValueConverter.cs

Issue: #1739
```
[x] Bugfix
[x] Feature
```
If you define an ItemContainerStyle for the AdaptiveGridView and do not define a Margin, or if the Margin is different from what is defined by the AdaptiveGridView then items will not span the entire width of the control.
You can now define an ItemContainerStyle that does not define a Margin or a Margin different from the default and items will still layout properly
```
[ ] Yes
[x] No
```
NOTE: This change has an added benefit that the AdaptiveGridView can now take advantage of an implicit style defined for a GridViewItem. This change removes the hard coded ItemContainerStyle which was preventing implicit styles to be used.

Fix layout when Margin of GridViewItem is not zero

---

Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/Connected.cs
Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/ConnectedAnimationHelper.cs

Issue: #1716
```
[x] Bugfix
```
The Connected animations extension will now work as expected when caching is turned on for pages
```
[ ] Yes
[x] No
```

Connected animations fix for cached pages

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection/IncrementalLoadingCollectionPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection/IncrementalLoadingCollectionPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection/PeopleSource.cs
Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs

- Added Refresh Button to sample application
- Added additional delay for first page in PeopleSource.cs to verify the order of items returned is correct regardless.
- Removed unnecessary call to LoadMoreItemsAsync()
- Renamed RefreshAsync() to Refresh()
Issue: #
https://github.com/Microsoft/UWPCommunityToolkit/issues/1664
```
[x] Bugfix
[ ] Feature
```
When refreshing an IncrementalLoadingCollection there's an unnecessary call to LoadMoreItemsAsync() potentially resulting in an unordered list since the second request might finish before …

IncrementalLoadingCollection Refresh Fix

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationPage.xaml.cs
Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs
docs/helpers/SystemInformation.md

Issue: #1741 
```
[ ] Bugfix
[x] Feature
```
I added some code based on the discussion on #1741 : 
* the `TotalLaunchCount` which is the total of launch count, obviously
* `LaunchCount` property still exists and can be reset
* a `ResetLaunchCount()` method to reset the current launch count
* the `LaunchResetTime` stores the last time the property `LaunchCount` is reset
```
[ ] Yes
[x] No
```
@michael-hawker I know this was your idea. I hope you are not mad at me for doing the PR. …

Reset launch count

---

Directory.Build.props
stylecop.json

Issue: #1042 
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting)
```
When reordering using statements with Visual Studio, they are moved inside the namespace
When reordering using statements with Visual Studio, they are kept outside the namespace
```
[ ] Yes
[x] No
```

Added stylecop.json to prevent usings from moving inside namespace

---

Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs

Issue: #1789 
```
[ ] Bugfix
[ ] Feature
```
Show basic Intellisense info on SystemInformation.DeviceFamily property.
Add list of possible values of SystemInformation.DeviceFamily property in XML docs so devs can see them when using the property.
```
[ ] Yes
[x] No
```
@XamlBrewer Not sure what to do about the link to Microsoft docs.

docs(SystemInformation): add list of possible DeviceFamily

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Issue: #1321
- Bugfix
When AdaptiveGridView's parent has infinite available size, the control throws an exceptions
The AdaptiveGridView no longer crashes and sets the desired width of the items to the width of the Window

Added check to prevent exceptions when AdaptiveGridView parent availalbe size is Inf

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Menu/Menu.bind
Microsoft.Toolkit.Uwp.UI.Controls/Menu/Menu.Events.cs

Issue: #1822
- Feature
This PR solves issue produced when menu is used with a textbox or textarea
When press any Alt+ anycharacter not registered the focus says on the main control and doesn't go to the menu
- [X ] Tested code with current [supported SDKs](../readme.md#supported)
- [ X] Docs have been added/updated which fit [documentation template](https://github.com/Microsoft/UWPCommunityToolkit/blob/master/docs/.template.md). (for bug fixes / features)

Menu focus on press on textbox

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RangeSelector/RangeSelectorCode.bind
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs
docs/controls/RangeSelector.md

Issue: #1356 
Improvement on RangeSelector
```
[ ] Bugfix
[x ] Feature
[x ] Documentation content changes
[x ] Sample app changes
```
the rangeselector max and min values change according to the thumb position
- [ x] Tested code with current [supported SDKs](../readme.md#supported)
There is a DP called StepValue, and if it is set then the values and the thumbs move to the corresponding position of the next stepvalue.
```
[ ] Yes
[x ] No
```

add StepFrequency to RangeSelector

---

Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/Connected.cs
Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/ConnectedAnimationHelper.cs
Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/ConnectedAnimationListProperty.cs

Issue: #1774
```
[x] Bugfix
[ ] Feature
```
#1774
The scenario now is supported. You can use the same key for any ListViewBase and it will animate to the correct one.
```
[ ] Yes
[x] No
```

Added support for connected animations from multiple ListViewBases.

---

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/LinkClickedEventArgs.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/LinkReturnType.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Methods.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/ILinkRegister.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/MarkdownRenderer.Inlines.cs
docs/controls/MarkdownTextBlock.md

Issue: #1091
```
[ ] Bugfix
[x] Feature
```
Images cannot be clicked with current implementation
Images can be tapped and will work as regular Hyperlink giving user option to Handle them in `LinkClicked` event
```
[ ] Yes
[x] No
```

Implementing Tapped on Images in MarkdownTextBlock

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Issue: #1803
- Bugfix
When DPI is set to 125% the AdaptiveGridView will flicker as its resizing.
No flicker when resizing.
Not the best fix, but it works.  There seems to be some conflict between our resizing calculations and the internal panel layout.

Fixes #1803 for AdaptiveGridView flicker on 125% DPI.

---

Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveService.cs
docs/services/OneDrive.md

Issue: #1815 
Feature
Microsoft.Graph.ServiceException thrown when trying to login with OnlineId from a background task.
Login (OnlineId) is successful when initialized with DoNotPrompt.

OnlineId support added for background tasks

---

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs

Issue: #1844
- Bugfix
Padding is added to the right as more columns are added
Padding remains the same
Related to #1803

Adjust layout for higher DPI

---

Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Events.cs

Issue: #1835
- Bugfix
Adjusting the splitter will violate min width of the first column whensecond column is not star sized.
Splitter respects the min width

Fix GridSplitter violating min width of columns

---

Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs

Issue: #1356
Bugfix
When manipulating the thumbs using arrow keys the value is changed, but they thumbs don't move to the value position
The thumbs move to the correct position when manipulating the slider using keyboard
- [x ] Tested code with current [supported SDKs](../readme.md#supported)
- [ x] Contains **NO** breaking changes

sync thumbs on left/right arrow keys

---

Microsoft.Toolkit.Uwp.Services/Services/Twitter/TwitterDataProvider.cs

Issue: #1872 
- Bugfix 
#1872 
Calling the RequestAsync method of the TwitterService like the following snippet
```
var twitterDataConfig = new TwitterDataConfig()
{
QueryType = TwitterQueryType.Home
};
await TwitterService.Instance.RequestAsync(twitterDataConfig, 5);
```
returns the tweets from the logged user's home timeline.

Fixed Twitter home query

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs

Do not use MaintainContext property.
Execute Bitmap rendering code on Dispatcher thread.
Issue: #1870
Bugfix
ImageCache maintains the thread context across async tasks to ensure that Bitmap is rendered without issues

Disable context continuation for ImageCache

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PrintHelper/PrintHelperCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PrintHelper/PrintHelperPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PrintHelper/PrintHelperPage.xaml.cs
Microsoft.Toolkit.Uwp/Helpers/PrintHelper/PrintHelper.cs
Microsoft.Toolkit.Uwp/Helpers/PrintHelper/PrintHelperOptions.cs
docs/helpers/PrintHelper.md

Issue: #1152 PrintHelper Horizontal Orientation
- Feature
There's no way to set up from code the print orientation, along with several other configurations.
You can setup from code which options will be shown in the print dialog, along with their default values, using the `PrintHelperOptions` class. To use the specified options, you can send them to the `PrintHelper` constructor to be used in every print job of that instance, or send them to the `PrintHelper.ShowPrintUIAsync` method to use them only for that print job. Note that the previous behavior is untouched.
The options to display on the print dialog are stored in the `DisplayedOptions` property. To add or remove an option, you have to …

PrintHelper Print Settings Customization

---

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.cs

Issue: #1615
- Bugfix
- Feature
The Header property only accepts string which limits what can be shown
The Expander now inherits from HeaderedContentControl which brings along the ability to set content to any object
This changes the return type of Header from string to object. This breaks the following if someone was doing it
```
string header = expander.Header;
```

Change Expander to Inherit from HeaderedContentControl

---

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml

Issue: #1904
- Bugfix
- Feature 
You can only place content for the header to the left because the alignment of the header is to the left
The header now stretches allowing you to place content to the left and right easily
This doesn't directly address the issue in #1904, which is requesting multiple header properties, but it does allow for content to be placed to the left and right on the header by styling your template
```
<control:Expander Header="Expand Me!">
<controls:Expander.HeaderTemplate>
<DataTemplate>
<Grid>
<Grid.ColumnDefinitions>
<ColumnDefinition Width="*">
<ColumnDefinition Width="Auto">
</Grid.ColumnDefinitions>
</Grid>
<TextBlock Text="{Binding}"/>
<Button …
```

Strectch the content of the expander header to allow for other content

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.xaml

ItemContainerStyleSelector allows for code to change the ItemContainerStyle on the fly
Issue: #1901 
- Bugfix (see issue)
- [n/a] Docs have been added/updated which fit [documentation template](https://github.com/Microsoft/UWPCommunityToolkit/blob/master/docs/.template.md). (for bug fixes / features)
- [n/a] Sample in sample app has been added / updated (for bug fixes / features)
- [n/a] Tests for the changes have been added (for bug fixes / features) (if applicable)

Added ItemContainerStyleSelector to the MasterDetailsView ListView

---

Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.cs

Issue: #1837
- Bugfix 
When an item is added or removed from a list, the item itself gets the correct color but items below it do not update
When an item is inserted or removed the background color will update for that item and all items below it
Change also unsubscribes from all events for the ListViewBase control.

Alternate color of items when items are added or removed

---

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml
docs/controls/Expander.md

Issue: #1904 
- Feature
Modifying the Header for the Expander requires restyling the entire control.
Add `HeaderStyle` property for ToggleButton Header Style to allow for restyling header of expander much more easily.
Thoughts on updating the sample?  I may do that with multi-sample later for these advanced scenarios.

Add HeaderStyle Property for Expander

---

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.cs

Issue: #1935 
Bugfix
code 'compositeTransform.CenterY = 0.5;' with line 515 in Carousel class file is duplicate.
removed the duplicate code.
Just remove one line in Carousel class of duplicate code.

Remove duplicate compositeTransform.CenterY

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs

When setting a filter, then resetting it to null,
an exception occured. This has been fixed.
Issue:   https://github.com/Microsoft/UWPCommunityToolkit/issues/1938
- Bugfix
- [ x ] Tested code with current [supported SDKs](../readme.md#supported)
- [ x ] Contains **NO** breaking changes

Fixed a NullReferenceException in AdvancedCollectionView Filter

---

Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/ConnectedAnimationHelper.cs

Issue: #1913 
- Bugfix
The app crashes if there are two lists with the same instance of an object on one page and you add the xaml connected animations that animates the view to a different page.
This simple catch, avoids the app from crashing, if the item instances are the same.
No crash.

Fix XAML Connected Animation crash (fixes #1913).

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection/IncrementalLoadingCollectionPage.xaml.cs
Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs

Issue: #1859 #1886 
- Bugfix
In a previous version, the collection was triggering several unnecessary loads (issue #1664). The fix for that (removing the forced reload when refreshing) caused that, when the collection is empty, calling refresh does nothing.
The collection refreshes, even if it was previously empty, while not triggering several unnecessary page loads.
The Refresh method was removed in favor of RefreshAsync, as the bugfix requires a call to an asynchronous method (LoadMoreItemsAsync).

IncrementalLoadingCollection Fixes

---

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs

Issue: #1940 
- Bugfix
Using `IEnumerable` with `AdvancedCollectionView` causes unexpected behaviors
`AdvancedCollectionView` now takes `IList` parameters.
This PR contains a breaking change. Every project using AdvancedCollectionView with IEnumerables will stop compiling, and will have to change their collection to implement IList.

Changed AdvancedCollectionView _source to IList

---

Microsoft.Toolkit.Uwp.UI.Controls.Design/RangeSelectorMetadata.cs
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.xaml

Issue: #1615
- Other... Please describe: Removing functionality
The IsTouchOptimized property would allow the developer to make the thumbs really big
Removed the IsTouchOptimized property and added a bigger FocusVisualMargin. 
Removes a property. 
Should the property remain and be marked as deprecated but have no functionality? So if you set the IsTouchOptimized property it would do nothing, but wouldn't completely break your build?

Remove is touch optimized

---

Microsoft.Toolkit.Parsers/Rss/Rss2Parser.cs
Microsoft.Toolkit.Parsers/Rss/RssHelper.cs
Microsoft.Toolkit.Parsers/Rss/RssSchema.cs

Added parsing for optional category element in the RSS 2.0 specification.
Issue: #1883 
Feature
Added parsing for optional `<category>` element in RssSchema
When the rss parser parses the feed into RssSchemas,  a category list is also parsed (if present).

feat: Parsing categories in rss Item

---

Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs
Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.xaml

Issue: #
https://github.com/Microsoft/UWPCommunityToolkit/issues/1923
- Bugfix
LeftBackground & WhiteBackground Brushes are only created in Code behind - because these are DependencyObjects they can't actually be shared between different `CoreDispatcher`s so when used in multiple Windows whilst using the default brushes, thread marshalling errors occur as the brush is trying to set itself on a Dispatcher thread that did not create it.
Specify LeftBackground and RightBackground properties in default XAML style. 

Fix SlidableListItem multi-window crash: Specify brushes in XAML

---

Microsoft.Toolkit.Uwp.UI/Extensions/NavigationView/NavigationViewExtensions.cs

Issue: #1949 
- Bugfix
On the new windows release, the NavigationView prevents setting `SelectedItem` back to null, this breaks the `CollapseOnClick` feature added in the Toolkit.
This fix introduces a hidden menu item which is used to emulate deselecting all other menu items.
It also fixes another selection issue that was happening with the Settings menu.
I've tested on RS4, but need to find an RS3 machine to test on.  There shouldn't be a problem, it's just a bit more overhead.
I may add some unit tests for the initial parsing/value selections, but not sure how that'll work without a visual test.

Fix NavigationViewExtensions for build 17134

---

Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebViewControlProcessExtensions.cs
Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebViewControlProcessExtensions.cs

Issue: #
- Feature
Users will see samples and guidance for UWP version of `WebViewControl` and are not able to translate that into something actionable in their WPF or Windows Forms application.
For example, users may see usage syntax like the following
```csharp
private async void button1_Click(object sender, EventArgs e)
{
var rect = new Rect(0, 0, panel1.Width, panel1.Height);
var wvcp = new WebViewControlProcess();
var wvc = await wvcp.CreateWebViewControlAsync(panel1.Handle.ToInt64(), rect);
wvc.Navigate(new Uri("https://www.microsoft.com"));
}
```
Similar methods required to achieve this syntax for Windows Forms and WPF are not available.
Change the visibility of extension methods for `WebViewControlProcess` proxy making it easy to adapt …

Expose WPF / WinForms extension methods for WebViewControlProcess

---

Directory.Build.props
Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs
version.json

Resolves Issue: #2075
- Bugfix
When control layout is updated, the position of the HWND RECT is incorrect, creating a gap in the layout of the sample application.
The layout passed the raw Bounds of the control that was not corrected for the offset of the Client RECT.

Fix issue with Windows Forms WebView control RECT on resize

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.xaml
docs/controls/ImageEx.md

Issue: #1963
<- Bugfix >
The ImageEx xaml template contains Progress Indicator control. That is causing Layout cycle detected when large number of controls are used.
The Progress indicator has been removed but the control still supports it if the consumer adds it to template

Remove Progress indicator from ImageEx.xaml

---

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs

Issue: #
<- Bugfix >
The cache instead of overwriting an existing file, recreates the file and then downloads the data. This would mean that in case of data / network failure, the cached copy has been destroyed and there is no newer copy to return to the consumer
The cache does not overwrite existing file. Instead existing file if expired is passed to download method which overwrites it if successful. 

Do not recreate expired files - overwrite existing files

---

Microsoft.Toolkit.Uwp.SampleApp/App.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs

Issue: #2045 
- Other... Please describe:
~Microsoft Docs Repo needs https://github.com/MicrosoftDocs/UWPCommunityToolkitDocs/pull/54 to go through for this to work.~
Checks SHA instead.
Sample app will show outdated docs if the docs are cached in an older release, and then a new version of the Toolkit gets released.
If the docsversion file in MicrosoftDocs/UWPCommunityToolkitDocs has a different Commit SHA than the Cached SHA, the Cache Folder gets wiped.

Sample App Cache version checker

---

Microsoft.Toolkit.Uwp.Services/Services/Twitter/Tweet.cs
Microsoft.Toolkit.Uwp.Services/Services/Twitter/TwitterDataProvider.cs
docs/services/Twitter.md

- Feature
Non streaming api calls do not include the full 280 characters of tweets
All api calls now include the full 280 characters
Reference twitter docs: https://developer.twitter.com/en/docs/tweets/tweet-updates

[Twitter service] support for 280 characters on non streaming api calls

---

build/build.cake

Issue: #2147
inheritdoc task used the latest version of the NuGet package. In the latest version, a breaking change was made to not require a license key which caused the task to fail, but build execution continued.
The implementation has been changed to indicate a specific package version to avoid unexpected breaking changes in the future. The process invocation has also been updated to ensure the documentation step completes successfully before continuing on to the next step during build.

Update InheritDoc Cake task

---

Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer.csproj

VB specific analyser folder was not created and analyzer was not being copied to project when installing from nuget.
This PR fixes that issue.
Issue: #
<- Bugfix >
When adding platform specific analyzer to VB project, the PSA is added a normal nuget package and not as an analyzer as vb specific folder was not found.
vb specific folder has been added and now the analyzer is loaded correctly

Platform Specific Analyser nupkg structure is correctly

---

Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.Events.cs

Issue: #2183 
- Bugfix
`InfiniteCanvas` was not handled tail eraser of Pen (ex Surface Pen).
`InfiniteCanvas` erase stroke with tail eraser of Pen.

Fix could not use tail eraser of Pen

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Properties.cs

Bugfix
I just fixed a tiny bug: In the MarkdownTextBlock, the `SchemeList` dependency property (`SchemeListProperty`) had it's `name` parameter incorrectly set to `nameof(UriPrefix)` (from copy-pasting the previous property, I assume). I simply changed it to the correct `nameof(SchemeList)`

Fix name parameter for the SchemeListProperty in MarkdownTextBlock

---

Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.cpp
Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.h
Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cpp
Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.h
Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeSettingsHelper.cpp
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GazeInteraction/GazeInteractionPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GazeInteraction/GazeInteractionPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GazeInteraction/GazeInteractionXaml.bind
docs/gaze/GazeInteractionLibrary.md

Issue: #2269
- Feature
Gaze plus switch is not available.
Gaze plus switch is now available

Add gaze plus switch support

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

Issue: #
https://github.com/Microsoft/WindowsCommunityToolkit/issues/2279
- Bugfix
If MasterDetailsView doesn't have a Visual ancestor that is a Frame, it throws an error whilst hooking navigation events.
Check for null, skip navigation hook.

Null check on frame in MasterDetailsView

---

docs/controls/WebView-known-issues.md

Issue: #
MicrosoftDocs/UWPCommunityToolkitDocs#72
The known issues does not include information about a missing WinRT API `AddWebAllowedObjects(String, Object)` which is not supported.
Documentation includes the unsupported API next to information of the related `ObjectForScripting`
CC: @normesta @ericlaw1979

Add `AddWebAllowedObject` to unsupported API list

---

Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointerProxy.cpp

Found an actual testable case where Load/Unload events do not occur in the expected manner, so modified code to be robust to the unexpected!

Made GazePointerProxy robust to out-of-sequence unexpected Load/Unload events

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
Microsoft.Toolkit.Uwp.UI/Helpers/ThemeListener.cs

Issue: #2258 
Bugfix 
Refactoring (no functional changes, no api changes)
When the MarkDownTextBlock it's initialized, it subscribes to many events, but after rendering it doesn't unsubscribe from them. This causes a memory leaking problem because the object is still linked to unnecessary actions. 
To avoid this, I've implemented the Loading and Unloading method in order to handle properly this flow. However, this doesn't solve entirely the memory leaking problem but, regardless of that, it's a good practice to do this.  

[Partial Fix]MarkdownTextBlock Memory leak: Subscribe/Unsubscribe event handler 

---

.vsts-ci.yml
.vsts-pr.yml
build/Install-WindowsSdkISO.ps1

Issue: #
Can't download or use ISO image to install Windows SDK
Script will download the ISO image from a URI, write out the cache information and use HTTP features for cache. If the file is out of date, a new file is downloaded in its place. If the file does not exist, is out of date, or it cannot be determined from the HTTP header, a new file is downloaded.  After the file is downloaded the ISO image is mounted, and the installation proceeds. Once finished the ISO is dismounted.

Add script for installing Windows SDK from ISO

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/Interop/WinRT/WebViewControlPermissionType.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/Microsoft.Toolkit.Win32.UI.Controls.csproj
build/vsts-build.yml

Issue: #
- Feature
Missing API for WebView (ImmersiveView permission)
Updating SDK to latest Insiders released version

Update Win32 project to use Insiders SDK 17713

---

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenuTemplate.xaml

Issue: #1306 
- Bugfix 
When navigating the menu with the keyboard, the selected index / current page indicator follow the focus, but the page only changes when clicking the enter/space key.
The selected index / current page indicator and the page only change after clicking the enter/space key.

HamburgerMenu focus indicator for keyboard navigation fix

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookPage.xaml.cs
Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
docs/services/Facebook.md

Issue: #2273 
Other... Please describe: Feature deprecation
See 2273
Facebook deprecated the publish_actions permission - the toolkit Facebook service and Facebook app fail to login/post actions.
Deprecated the methods that depend on publish_actions, removed features from the sample app that leveraged the publish_actions feature.
The FacebookService methods affected have been marked deprecated - they should fail silently if called.  Apps consuming the service will need to explicitly stop initializing with the PublishActions permission otherwise login will eventually fail.  Posts will now need to be leveraged via the supported PostToFeedWithDialogAsync method - this will likely not …

deprecated publish_actions and dependencies

---

Directory.Build.props
Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphService.cs
Microsoft.Toolkit.Services/Services/OneDrive/OneDriveStorageItem.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.cs
Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj
Microsoft.Toolkit.Uwp.UI.Controls.Graph/AadLogin/AadLogin.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/CameraPreview/CameraPreview.cs
Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/JsonConverters/SerializableStroke.cs
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs

Style warnings should stop the build when building in Release but currently they do not
Style warnings will not break the build when building in release. This will ensure we do not merge code with warnings as part of pull requests

Enabling "TreatWarningsAsErrors" on release builds 

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs

Issue: #2346, #2347
- Bugfix
ScriptNotify is not raised as expected due to a timing issue during initialization
An issue may occur where methods, such as InvokeScript/InvokeScriptAsync, are permitted to be invoked prior to the WebView completing initialization. As such, properties may not yet be set for permitting JavaScript or ScriptNotify, causing inconsistencies with application behavior.
Additionally, the Source property is set, causing an immediate navigation before other properties are also set. The code has been updated for WPF to follow a similar order for WinForms.
See issue #2346 for details. Separate PR #2347 created to backport change to 3.0.0

Protect actions and delay navigation until last moment

---

Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs

Issue: #2346 
An issue may occur where methods, such as InvokeScript/InvokeScriptAsync, are permitted to be invoked prior to the WebView completing initialization. As such, properties may not yet be set for permitting JavaScript or ScriptNotify, causing inconsistencies with application behavior.
Additionally, the Source property is set, causing an immediate navigation before other properties are also set. The code has been updated for WPF to follow a similar order for WinForms.
Execution cannot continue until the control is verified to be completely loaded. Additionally, navigation (setting `Source` property), is the last property set during initialization to ensure all other behaviors are set prior to initiating any such navigation.
Please …

WPF WebView: Protect actions and delay navigation until last moment 3.0.x

---

Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs

Issue: #2356
- Bugfix
When the WWAHost.exe and Win32WebViewProcess.exe are created, they need to read information such as the networking permissions and enterprise ID. However, when those items are data bound they are done on the dispatcher thread (priority 8); however, the process is initialized prior to flushing the dispatcher queue. This then did not read the proper values during initialization (as they had not yet been changed by the dispatcher queue), even though they were set once the dispatcher had popped our frame to create the view.
This change moves the process creation code from outside the dispatcher frame into the same location as the remainder of the initialization code. This will permit any mutations to properties through the …

Move WWAHost process creation into dispatcher 3.0.x

---

Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs

Issue: #2337 
- Bugfix
During the disposal process the HWND for the control is destroyed, leaving an orphaned HWND core window. In RS4 this could case a lock up since it was expected that the Close method on WebViewControl would always be closed. During RS5 this was updated to ensure that Close is always called, even if the hosting process crashes or one of the supporting processes is terminated unexpectedly.
This change intercepts the DestoryHandle and OnHandleDestoryed methods of the Windows Forms WebView control to first call Close method. This starts a synchronous shutdown of all processes and unparents the HWNDs. By the time the actual disposal comes around, the control and its processes are already cleaned up and the UI remains responsive. …

Add Close before HWND destroyed (3.0.x)

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs

Issue: #2337
- Bugfix
During the disposal process the HWND for the control is destroyed, leaving an orphaned HWND core window. In RS4 this could case a lock up since it was expected that the Close method on WebViewControl would always be closed. During RS5 this was updated to ensure that Close is always called, even if the hosting process crashes or one of the supporting processes is terminated unexpectedly.
This change intercepts the DestoryHandle and OnHandleDestoryed methods of the Windows Forms WebView control to first call Close method. This starts a synchronous shutdown of all processes and unparents the HWNDs. By the time the actual disposal comes around, the control and its processes are already cleaned up and the UI remains responsive. …

Add Close before HWND destroyed (4.0.0)

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs

Issue: #2356
- Bugfix
When the WWAHost.exe and Win32WebViewProcess.exe are created, they need to read information such as the networking permissions and enterprise ID. However, when those items are data bound they are done on the dispatcher thread (priority 8); however, the process is initialized prior to flushing the dispatcher queue. This then did not read the proper values during initialization (as they had not yet been changed by the dispatcher queue), even though they were set once the dispatcher had popped our frame to create the view.
This change moves the process creation code from outside the dispatcher frame into the same location as the remainder of the initialization code. This will permit any mutations to properties through the …

Move WWAHost process creation into dispatcher 4.0.0

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
Microsoft.Toolkit.Uwp.UI/Extensions/NavigationView/NavigationViewExtensions.cs
docs/extensions/NavigationView.md

Issue: #2242 
Added the deprecated warning to NavigationView extension

Deprecate NavigationView extension

---

Microsoft.Toolkit.Win32.UI.Controls/Interop/WinRT/WebViewControlHost.cs
Microsoft.Toolkit.Win32.UI.Controls/WPF/TaskExtensions.WPF.cs
Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs
Microsoft.Toolkit.Win32.UI.Controls/WinForms/TaskExtensions.WinForms.cs
Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs

Issue: #2367
When calling WebView.InvokeScript from the UI thread, a deadlock may occur when the asynchronous task is captured within the UI context. Since each thread is waiting for the each other, the deadlock occurs.
An attempt to move the thread execution to the thread pool causes a similar issue, so the task is moved to a message loop to keep the UI responsive while the task is completed.
CC @PoulBak

Fix deadlock on InvokeScript (3.0.x)

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/Interop/WinRT/WebViewControlHost.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/TaskExtensions.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/TaskExtensions.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs
Microsoft.Toolkit.Win32/Tests/UnitTests.WebView.WinForms/FunctionalTests/InvokeScript/InvokeScriptTests.cs

Issue: #2367
- Bugfix
When calling WebView.InvokeScript from the UI thread, a deadlock may occur when the asynchronous task is captured within the UI context. Since each thread is waiting for the each other, the deadlock occurs.
An attempt to move the thread execution to the thread pool causes a similar issue, so the task is moved to a message loop to keep the UI responsive while the task is completed.
CC @PoulBak
Resolves #2367

Fix deadlock on InvokeScript (4.0.0)

---

Microsoft.Toolkit.Win32/Tests/UnitTests.WebView.WinForms/FunctionalTests/Navigation/NavigateWithHttpMessageTests.cs
Microsoft.Toolkit.Win32/Tests/UnitTests.WebView.WinForms/FunctionalTests/WebViewFormContextSpecification.cs

Issue: #
- Other... Please describe: functional tests
There are currently no tests to cover new `Navigate` methods that use `NavigateWithHttpMessage` in Win32 WebView.
Add navigation tests for HTTP GET and POST

Add tests for NavigateWithHttpMessage

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.Init.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs
Microsoft.Toolkit.Win32/Tests/UnitTests.WebView.WinForms/FunctionalTests/Cookies/CookieTests.cs
docs/controls/WebView-known-issues.md
docs/controls/WebView.md

Issue: #2375
- Feature
With the traditional API, invoking `new WebView()` would always create a web view in a new WWAHost and Win32WebViewHost process. In some cases, state needs to be shared between individual views, such as for single sign on scenarios, to avoid having each web view authenticate.  Edge does not persist session state to disk to both maintain performance and provide a safe way to remove session state in the event of a crash. When a new web view process is created, Edge internally copies all the session state it can to the new process. With the default .ctor each web view was created in its own WWAHost process, and each was treated as a new session, failing to inherit any of the ephemeral session state. However, any state that …

Add support for creating web views in the same WWAHost process

---

Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.xaml

Change color from *BaseHigh* to *BaseMediumHigh* when in pressed state.
Closes #2380.
- Bugfix
GridSplitter goes completely white when pressed in Dark Theme
When pressed color is now light grey in Dark Theme and dark grey in Light Theme

Change GridSplitter color when pressed.

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/IWebView.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/Interop/WinRT/WebViewControlHost.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/Microsoft.Toolkit.Win32.UI.Controls.csproj
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs
Microsoft.Toolkit.Win32/Tests/UnitTests.WebView.WinForms/FunctionalTests/PreLoad/PreLoadTests.cs
build/vsts-build.yml

Issue: #2378
- Bugfix
- Build is on 17713
- Depending on Windows SDK and OS version, method to invoke script prior to other script on web view navigation may not exist. This was due to a name change around build 17723
- Move build to use Windows SDK 17733
- Update Win32 controls to use 17733
- Add new method for script execution called `AddInitializeScript` to match Windows SDK
- Redirect existing method `AddPreLoadedScript` to `AddInitializeScript` and mark it obsolete with directions to use the new method.
CC @purani
Resolves #2378

Windows sdk 17733

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/DispatcherExtensions.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.Dispatch.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs

Issue: #2374
- Bugfix
If a caller invokes a property or method that requires the web view to be initialized, it is common to have code to push empty frames onto the dispatcher queue until the web view initialization completed. However, depending on where the caller's code invoke the web view property or method, initialization may never occur and the control continues to dispatch empty frames to the queue.
This change modifies the initialization wait behavior for the following items:
- Properties
- IsVisible
- Process
- Methods
- AddPreLoadedScript
- GetDeferredPermissionRequestById
- GoBack
- GoForward
- InvokeScript
- InvokeScriptAsync
- MoveFocus
- Navigate
- NavigateToLocal
- NavigateToLocalStreamUri
- NavigateToString
- Refresh
- Stop …

Remove UI hang for some WPF WebView properties and methods

---

Directory.Build.props
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls.WebView/WebViewCompatible.cs
azure-pipelines.yml

Issue: Fixes #2477
- Bugfix 
Throws on Win7
Works on Win7

Use WebViewControlHost.IsSupported to avoid loading APIs on downlevel OS

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls.WebView/VisualStudioToolsManifest.xml

Issue: #2482
- Bugfix
When referencing the WebView NuGet, only WebView is shown in the toolbox despite also having another UI control WebViewCompatible also available. XAML entry could be made by hand, but not by dragging off the toolbox.
Update adds an entry for WebViewCompatible which permits it to show in the toolbox. 
Resolves #2482

Add entry for WebViewCompatible in manifest

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/IWebView.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/Interop/WinRT/WebViewControlHost.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WPF/WebView/WebView.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.Controls/WinForms/WebView/WebView.cs
Microsoft.Toolkit.Win32/Tests/UnitTests.WebView.WinForms/FunctionalTests/PreLoad/PreLoadTests.cs

Issue: #
- Bugfix
4.x build broken due to change in SDK.
Cherry picked from 08b9b1453511350852f08e445a9aae20455ccb17 to fix build break
Update Win32 WebView API due to change in 17723
New to 17723 is a change of name for the AddPreLoadedScript. It is now named AddInitializeScript. The existing method has been marked obsolete with directions to use the new method name. The old method will be removed in a future release of the toolkit.

Add `AddPreLoadedScript(string)` to WebView

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.XamlHost/WindowsXamlHostBase.WndProc.cs

Issue: #2491
- Bugfix
In certain cases focus set on a Windows Forms XamlHost unnecessarily may cause the application to quit.
When `WM_SETFOCUS` is encountered and focus is not required, temporarily drop the message to prevent calling Focus on Focused element.
Fixes #2491

Temporary workaround for internal aggressive FAILFAST 

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ImageEx/ImageExCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ImageEx/ImageExPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MasterDetailsView/MasterDetailsView.bind

Issue: #2557
- Bugfix
Samples uses deprecated RoundedImageEx
No longer uses the RoundedImageEx
toolkit/WindowsCommunityToolkit/blob/master/docs/.template.md). (for bug fixes / features)

Remove RoundedImageEx from sample app

---

Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.xaml

Issue: #2276
- Bugfix 
GridSplitter fails to adopt correct High Contrast White theme colors when user interacts with the splitter
Adopts colors correctly from the White theme

Fixed GridSplitter default to follow Rel-4.0.0 release

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.XamlHost/WindowsXamlHostBase.Layout.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.XamlHost/WindowsXamlHostBase.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Sample.Forms.App/app.manifest
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Sample.Wpf.App/app.manifest

Issue: #
Bugfix
Starting in one of the recent windows insider builds, the XAML island content is now automatically dpi scaled. Therefore, enabling the dpiScalingRenderTransformEnabled property of the windows forms XAML host (to enable scaling with Windows 1809) would result in double scaling.
If running on a Windows 19H1 insider build, the additional scaling will not be applied. Some code has been added to transform the layout from pixels (winforms) to effective pixels (UWP) in this case to size elements with AutoSize=true correctly. The WPF and winforms sample app are also now declared to be per monitor V2 dpi aware. This enables dynamic rescaling for both apps. However, in the winforms app this only applies to the UWP content.
One additional …

Take into account XAML islands dpi scaling in the winforms XAML host

---

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbar.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarCustomPenButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarCustomToolButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarMenuButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarPenButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarStencilButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarToggleButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/InkToolbar/InkToolbarToolButton.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.XamlHost/WindowsXamlHost.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.XamlHost/WindowsXamlHostBase.cs
Microsoft.Toolkit.Win32/Microsoft.Toolkit.Sample.Forms.App/Form1.Designer.cs

Issue: #
Bugfix
As can be seen in the winforms sample app, custom buttons are not added correctly to the ink toolbar.
Some code changes to align with the WPF code to add the button XAML element directly to the inktoolbar XAML Control.

Fix adding additional buttons to the winforms inktoolbar control

---

Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cpp

Changed implementation of RequestCalibrationAsync to return false when it cannot be done because there is no device or is ambiguous because there is more than one device.

Make eye tracking RequestCalibrationAsync friendlier

---

Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/Connected.cs

The SetListDataItemForNextConnectedAnimation is misspelled
The method is spelled correctly

[SetListDataItemForNextConnectedAnimation] Deprecated misspelled method and added correct spelling

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Methods.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/MarkdownRenderer.Blocks.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/MarkdownRenderer.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/MarkdownRenderer.cs

Issue: #2642
- Bugfix
The MarkdownTextBlock does not support the `FlowDirection` property.
Added support for FlowDirection in the MarkdownTextBlock. Setting the FlowDirection of the MarkdownTextBlock will set the FlowDirection of the underling TextBlocks used

Add support for FlowDirection in the MarkdownTextBlock

---

azure-pipelines.yml
build/Install-WindowsSdkISO.ps1

Builds often get a OutOfMemoryException due to Invoke-WebRequest trying to download the SDK ISO (800+mb) in memory before saving to disk
Replaced Invoke-WebRequest with WebClient to avoid the issue
This new implementation does not handle smart caching because WebClient does not expose the headers of the request (easily). Caching is not strictly necessary as the script always runs on a clean vm which will always need to the sdk downloaded and installed

Replaced Invoke-WebRequest with WebClient in SDK Installation script

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedContentControl/HeaderedContentControl.cs
Microsoft.Toolkit.Uwp.UI.Controls/HeaderedContentControl/HeaderedContentControl.xaml

Issue: #2661
- Bugfix
The Header shows the Content property if the Header is null and the Content is text
The Header is not visible if the Header property is null

Hide Header for HeaderedContentControl when Header is null

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs

Issue: #2442 
- Bugfix
InAppNotification does not replace the content from the current notification options to the next one in either `StackInFront` or `QueueBehind` mode.
Well, now it works.
It was due to the fact that the `dismissTimer` that need to be used was always stopped after the first replacement of content but we need it to continue to tick until the final dismiss.

Fix behavior on queue behind and stack in front modes

---

Microsoft.Toolkit.Uwp.UI/Extensions/Mouse/Mouse.cs

Related Issue: #2017 
- Bugfix
Sometimes when using Mouse Extensions the cursor doesn't change back properly.
Now cursor should be properly restored.
Pointer Exit is sometimes called originating from the element itself, which in turn causes it to set the pointer to the changed cursor instead of back to something else.  This checks that the source is not the item we've attached the property to.
Unfortunately, the original issue filed with GridSplitter is entirely different as there's a lot more logic there.  We should refactor GridSplitter for 6.0 to use Mouse Extensions instead, I have some of this done already as part of another more general 'ContentSplitter' control I've written.

Fix Mouse Cursor Extensions not changing cursor back

---

Microsoft.Toolkit.Parsers/Markdown/Inlines/HyperlinkInline.cs

Issue: #2749
- Bugfix
See #2749 
No exceptions when parsing a link

Markdown parses fix for ArgumentOutOfRangeException when parsing urls

---

Microsoft.Toolkit.Uwp/Helpers/RemoteDeviceHelper/RemoteDeviceHelper.cs

Related to PR #2126
- Bugfix
IRemoteSystemWatcher2 interface doesn't exist on RS3 so we can't use EnumerationCompleted event there.
Create a timer to stop the watcher after a couple of seconds when that event is missing.
We can remove this guard in 6.0 when we up the min version.

Add Guard and Timer to supplement EnumerationCompleted event which is missing on RS3

---

Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
Microsoft.Toolkit.Uwp.SampleApp/Models/Samples.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs
Microsoft.Toolkit.Uwp.SampleApp/Shell.Search.cs
Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml

Issue: #2688 
1. Sample app has many categories (12):
2. Controls category is pretty large (and gets bigger with condensing step done as part of this review):
3. Search only worked by name:
1. Condense categories to 8:
2. Add Subcategories to certain categories to allow for more ordered grouping to aid in searching:
3. Search looks at name, description and subcategory:
Adds a new property to the `Sample` object and modifies `samples.json` to add it and condense some categories.  Adds a `CollectionViewSource` and grouping step in the method which retrieves the samples when the menu is opened.  Modifies search to look at more fields.
Named most of Control categories …

Condense Sample App Categories + Add Subcategories

---

readme.md

Issue: #2811 
Readme is missing the document link for ImageCropper.
Add the ImageCropper document link to readme.md.

Add the ImageCropper document link to readme.md

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs

Issue: #2805 
- Bugfix 
When creating a notification without setting the content (e.g. using a ContentTemplate), the app crashes.
The app no longer crashes.

Add null check for Content property before applying automation peer

---

Microsoft.Toolkit.Uwp.UI/Extensions/TextBoxRegEx/TextBoxRegex.Properties.cs

Issue: #2840
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2840
Bugfix
TextBoxRegex 'IsValid' property cannot be bound, as it's 'Set' method attempts to set the wrong DependencyProperty.
TextBoxRegex 'IsValid' property's 'Set' method targets the correct property.
- [N/A] Pull Request has been submitted to the documentation repository [instructions](..\contributing.md#docs). Link: 
- [N/A] Sample in sample app has been added / updated (for bug fixes / features)
- [N/A] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)
- [N/A] Tests for the changes have …

Corrected TextBoxRegex IsValid Set() to update the correct DependencyProperty

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedContentControl/HeaderedContentControl.cs

Issue: #2822
Bugfix
Hide HeaderPresenter when Header is null.
Hide headerPresenter when Header is null or an empty string.

Fix HeaderedContentControl throws ArgumentException

---

Microsoft.Toolkit.Uwp.UI/Converters/StringFormatConverter.cs
UnitTests/Converters/Test_StringFormatConverter.cs
UnitTests/UnitTests.csproj

Issue: #2744 
Bugfix
An exception is thrown when parameter of `StringFormatConverter` is invalid
Return the value by catching exception
(https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)

fix: add unit tests to fix StringFormatConverter

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedContentControl/HeaderedContentControl.cs
Microsoft.Toolkit.Uwp.UI.Controls/StaggeredPanel/StaggeredPanel.cs

Issue: #
#2825
- Bugfix 
See #2825
The alignment of the children of StaggeredPanel will changed based on the HorizontalContentAlignment property set in the child.

Make StaggeredPanel sensitive to HorizontalContentAlignment of children

---

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedContentControl/HeaderedContentControl.cs

Issue: #2865
- Bugfix 
HeaderedContentControl does not respond to orientation set before applying control template (for example, in XAML markup).
The control now correctly reflects the orientation set before applying template.

Fix HeaderedContentControl orientation bug.

---

Microsoft.Toolkit.Uwp/Helpers/PrintHelper/PrintHelper.cs

Issue: #2835 
- Bugfix
When trying to print without using direct print, the print task fails.
Now the direct print works as well the preview pages visualization and the PDF printing.
This PR also fixes issue #2773

Fix preview pages on direct printing using PrintHelper

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DropShadowPanel/DropShadowPanelXaml.bind
Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs

Allows opting-in to non-alpha masks and more performant shadows for rectangular geometries.
Issue: #2862
- Bugfix
- Feature
When using rectangular geometries with DropShadowPanel the performance can be pretty bad with hundreds of elements, as by default we always use an alpha mask:
Allow turning off Alpha Masking (see new `IsMasked` option in sample) to use more performant rectangular shadows in composition layer.  Default is still `true` for backwards compatibility and more reasonable assumed behavior for infrequent uses.
Default is still `True` so non-breaking change.

Add `IsMasked` property to DropShadowPanel

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.xaml

Issue: #2823 
Bugfix 
If run on version 1803 build 17134 the InAppNotification threw a XamlParseException caused by the IXamlType2 being not found at runtime by the conditional on the XAML code of the control. 
Now it runs in all supported versions. 
Changed the UniversalApiContract in the XAML conditional to 7 where the IXamlType2 was already added. 
I Refactored the namespaces to indicate the version of the UniversalApiContract version used.

Fix compatibility of InAppNotification with build 17134

---

Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs

Issue: #2888
- Bugfix 
RangeSelector will crash when the tooltip is removed from the template.
Fixed this bug.

Fix RangeSelector crash when the tooltip is removed from the template.

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageCropper/ImageCropper.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls/ImageCropper/ImageCropper.cs

Issue: #2845 
The ImageCropper control doesn't allow to set the CroppedRegion
The ImageCropper allows to set the CroppedRegion, so the app can  specify a default crop region.

Allow to set CroppedRegion in ImageCropper

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs

fix: use lock on timer to prevent concurrent access

---

Microsoft.Toolkit/Helpers/Singleton.cs

Issue: #2989 (Related to Graph Controls)
- Feature
Common Helper for using Singleton Pattern based off common established method.  Also used by [Windows Template Studio](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/templates/Uwp/_comp/_shared/Project.AddCoreProject/Param_ProjectName.Core/Helpers/Singleton.cs).

Add Singleton Pattern Helper to Microsoft.Toolkit

---

Microsoft.Toolkit.Uwp.UI/Extensions/DispatcherTimerExtensions.cs

For rate-limiting UI events (like triggering on typing)
For use in Graph Controls later
Issue: #2989 
- Feature
It's hard to know when the user is typing when to execute a search query.
By wrapping typed event callback in debounce method, it's easy to only query a remote server after the user has delayed in their typing.

Add a Debounce Extension to DispatcherTimer 

---

Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/StretchChild.cs
Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/WrapPanel.cs

Issue: #
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/195
Adding an extra property and matching enum: StretchChild. This is needed to support the design of the upcoming TokenizingTextBox control.
Set StretchChild to StretchChild.Last to cause the last child of the wrap panel to fill any remaining space.

Adding StretchChild property to WrapPanel control

---

Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridColumns.cs

Issue: #3010  -  Resize DataGrid cause NullReferenceException
Bugfix
Assertion failure in DataGrid.ComputeDisplayedColumns
Debug.Assert(dataGridColumn != null, "Expected non-null dataGridColumn.");
followed by NullReferenceException while trying to use that null dataGridColumn.
NullReferenceException avoided and app continues to run as expected.

Fix for DataGrid Issue #3010 - NullReferenceException in DataGrid.ComputeDisplayedColumns

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

Issue: #2901
- Bugfix
The NoSelectionPresenter is visible after changing the state from narrow to wide. This is most noticeable when the background of the MasterDetailsView is set to Transparent 
The states will be set to the narrow/wide states before setting the selection states which control the visibility. The default visibility for the NoSelectionPresenter is Visible which it gets when going to the Wide state (which was being set after selection state).

Fix Visibility of the No Selection 

---

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs

Issue: #2650
- Bugfix
If the user sets the SelectedItem before the template is applied OR if the inline button is styled out it button can be null
Check for null on the button

Check for MasterDetails inline button not being null

---

Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj

Fixes #3012
- Bugfix
Cannot build in VS 2019 without additional steps outside of VS
Can now clone project in VS 2019 and build/run sample app without trouble
Tested with VS 2019 16.5 Preview 1

Fixes #3012 working around NuGet/Home#8388

---

Microsoft.Toolkit.Uwp.UI/Cache/FileCache.cs

FileCache.InitializeTypeAsync(Stream...) should not return null. It should return `Task.FromResult<StorageFile>(null)`. Otherwise, CacheBase attempts to dereference the Task to call ConfigureAwait(false) which results in a NullReferenceException.
Fixes #3104
- Bugfix
If the Uri has not already been cached, calling the following throws a NullReferenceException
```
StorageFile file = await FileCache.Instance.GetFromCacheAsync(new Uri("https://www.bing.com"));
```
No NullReferenceException is thrown.
I also updated the what the InitializeTypeAsync(StorageFile...) return to be consistent with the other InitializeTypeAsync(Stream...) return. In the end, Task.FromResult is the more …

FileCache throws NullReferenceException

---

Microsoft.Toolkit.Uwp/Deferred/EventHandlerExtensions.cs
Microsoft.Toolkit.Uwp/Deferred/TypedEventHandlerExtensions.cs

The community toolkit code is using `Task.FromResult(0)` to create completed task. This is not needed since we can directly use `Task.CompletedTask` and spare a few allocations.
The `Task.CompletedTask` instance will now be used for async methods returning a completed task.

Replace Task.FromResult by Task.CompletedTask

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugeCode.bind
Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs
Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.xaml

Bugfix
Changing the `RadialGauge.ValueStringFormat` does not have an effect on the displayed value.
This update fixes the `RadialGauge` value text formatting that was overridden by a template binding on the `Value` property.
Here's the appropriate text update location:
https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/ef6527227539362125a0617d9b9821b2c009e11e/Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs#L537

Fix RadialGauge default template value formatting

---

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/IObjectSerializer.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/JsonObjectSerializer.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/LocalObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/RoamingObjectStorageHelper.cs

Fixes #3175
- Feature
JsonConvert calls in BaseObjectStorageHelper always use default JsonSerializerSettings, and a caller cannot provide custom ones.
A JsonSerializerSettings object can be provided to Local/RoamingObjectStorageHelper, and will then be used in all serialization and deserialization calls.

Let BaseObjectStorageHelper use custom JsonSerializerOptions

---

Microsoft.Toolkit.Uwp/Helpers/DispatcherHelper.cs
UnitTests/Helpers/Test_DispatcherHelper.cs
UnitTests/UnitTests.csproj

This PR is part of the group being tracked in #3108.
- Optimization
Currently, APIs in the `DispatcherHelper` class will always result in a callback dispatch on the target `CoreDispatcher` instance, and a `Task` or `Task<T>` allocation, even when the caller is already running on that same `CoreDispatcher` instance, therefore not needing the dispatching at all.
There are just 2 changes being introduced by this PR:
- When scheduling an `Action` or `Func<T>` on the UI thread, if the target `CoreDispatcher` already has thread access, the delegates will be invoked directly, skipping the dispatcher scheduling entirely.
- When running an `Action` on the same UI thread, `Task.CompletedTask` is used, to avoid the unnecessary allocation of a new `Task` …

Dispatcher helper optimizations

---

.runsettings
UnitTests/UnitTests.Notifications.NetCore/UnitTests.Notifications.NetCore.csproj
azure-pipelines.yml
build/build.cake

Only UWP tests are running on build.
.Net Core projects run tests as well as UWP ones.

Enabled .NetCore tests.

---

Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
Microsoft.Toolkit.Uwp.SampleApp/Models/Samples.cs
Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json

We were loading all the .bind files for ALL the samples when we loaded `samples.json` in order to read in the property slider info to generate the properties panel.
This change now moves that workload to when the sample is requested/loaded in the UI. This should improve the start-up time of the sample app.
Load all sample descriptors at the start of the app.
Load specific sample descriptor when sample is requested.
I also added support for Morten's PR #3030 to be able to put multiple samples in one folder by supporting Absolute paths for Code Files in samples.json.
Also, this cleans-up a missing sub-category in the Helpers category.

Optimize Sample App Sample Loading

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs

Fixed callbacks unregistering in MarkdownTextBlock
Bugfix
This PR is pretty much self-explained.

Fixed callbacks unregistering in MarkdownTextBlock

---

Directory.Build.props
Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.csproj
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj

Builds are not deterministic (https://github.com/clairernovotny/DeterministicBuilds)
Builds are deterministic.

Enabled deterministic builds.

---

Directory.Build.targets
Microsoft.Toolkit.HighPerformance/Microsoft.Toolkit.HighPerformance.csproj
Microsoft.Toolkit.Parsers/Microsoft.Toolkit.Parsers.csproj
Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj
Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer.csproj
Microsoft.Toolkit/Microsoft.Toolkit.csproj

- Bugfix 
PDBs are not automatically loaded, which makes debugging much harder.
PDBs are now the portable kind, since VS now handles that beautifully.

Removed full pdb workaround, switching to portable pdbs.

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs

- Bugfix 
Crash if in app notification is shows and the control is not being shown on the current page.
No more exception, it just gracefully checks for null on this one property.

Fix for #2899.

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs
Microsoft.Toolkit.Uwp.SampleApp/Styles/Generic.xaml
Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj
Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.xaml

Updates/Consolidates NuGet dependencies (not sure if I got all of them?), also updates to WinUI 2.4 which required Sample App Changes.
- Refactoring

Update to WinUI 2.4

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
Microsoft.Toolkit.Uwp.UI.Controls/TabView/TabView.cs
Microsoft.Toolkit.Uwp.UI.Media/Brushes/RadialGradientBrush.cs
Microsoft.Toolkit/Helpers/Singleton.cs

Marking things that will be removed in 7.0. Both TabView and RadialGradientBrush have graduated 🎉🎉🎉. There's one element missing from the WinUI RadialGradientBrush, but we'll see if we can get it in their 2.5, it should be a simple add. (@chingucoding were you looking at https://github.com/microsoft/microsoft-ui-xaml/issues/2385 or the MenuBar one or both?)

Deprecate TabView, RadialGradientBrush, Singleton, FacebookService

---

Microsoft.Toolkit/Diagnostics/Generated/Guard.Collection.g.cs
Microsoft.Toolkit/Diagnostics/Generated/Guard.Collection.tt
Microsoft.Toolkit/Diagnostics/Generated/Guard.Comparable.Numeric.g.cs
Microsoft.Toolkit/Diagnostics/Generated/Guard.Comparable.Numeric.tt
Microsoft.Toolkit/Diagnostics/Guard.Comparable.Generic.cs
Microsoft.Toolkit/Diagnostics/Guard.Comparable.Numeric.cs
Microsoft.Toolkit/Diagnostics/Guard.IO.cs
Microsoft.Toolkit/Diagnostics/Guard.String.cs
Microsoft.Toolkit/Diagnostics/Guard.Tasks.cs
Microsoft.Toolkit/Diagnostics/Guard.cs
Microsoft.Toolkit/Diagnostics/ThrowHelper.ThrowExceptions.cs

- Speed improvement
The JIT compiler always assumes that forward branches are taken, unless it can see that the branch always throws. This doesn't happen in our throw methods, as we have a secondary `ThrowHelper.Throw...` method that actually creates the exceptions to throw in the correct format.
To work around this, all the `Guard` conditions have been inverted to guarantee that the forward branch considered taken is the one corresponding to the successful path for the check being done. This also improves code readability, as the conditions in each `Guard` API are no longer inverted.

Improved codegen in Guard APIs

---

Directory.Build.targets

- Bugfix 
Sample app was not building on Release mode due to wrong logic to enable strong name.
Fixed.

Fix Sample app in release mode

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj

- Bugfix 
Release build of ARM64 version of the sample app fails to build.
Now it builds fine.

Fix Sample app ARM64 Release compilation.

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayoutPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayout.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayoutPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayoutPage.xaml.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/WrapLayout.cs

Also add some new stuff to the sample for easier manipulation.
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3327
- Bugfix 
WrapLayout throws when contained in a control with an infinite size in the axis opposite to the WrapLayout.
It doesnt crash now. And there are some neat controls on the sample to help swap axis.

Fix crash with unbounded sizing for WrapLayout.

---

Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Prebuilt.cs

- Bugfix
The `AcrylicBrush` and the various `PipelineBuilder` APIs to create acrylic brushes are using the incorrect placement for the blend effect adding the noise texture at the end of the pipeline. THis bug was introduced in #3298, as I forgot to update the code there after swapping the way the placement property worked 🤦‍♂️
Fixed the blend effects for acrylic brushes, now the noise texture will correctly be displayed on top.

Fix acrylic brush noise texture placement

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GridSplitter/GridSplitter.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Loading/LoadingCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredPanel/StaggeredPanel.bind

Need to remove the enum binding for now so that it's not misleading, need to investigate why this is happening only with the system based enum.

Workaround for #3343

---

UnitTests/UnitTests.HighPerformance.Shared/Extensions/Test_ReadOnlySpanExtensions.Count.cs

`UnitTests.HighPerformance.Extensions.Test_ReadOnlySpanExtensions.Test_ReadOnlySpanExtensions_RandomCountManaged` is sometimes failing with an out of memory exception.
Disabled the most expensive test case there (see comments) to try to avoid this issue.

Reduce memory pressure in CI tests for HP package

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/MSEdgeNotificationStyle.xaml

In dark theme, the contrast ratio is not following the [minimum requirements](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) of 4.5:1.
- Bugfix
In dark theme, the dismiss button from the `MSEdgeNotificationStyle` is not meeting the accessibility criteria. This can be checked using *Accessibility Insights for Windows*:
I've changed the colors to use `SystemBaseMediumColor` for the hover color and `SystemBaseHighColor` for the pressed color.
They provides a contrast ratio that meet the minimum value both in dark and light theme

Improve contrast ratio for dismiss button in MSEdgeNotificationStyle

---

Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.cs
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridCell.cs
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridColumnHeader.cs
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridRowHeader.cs
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Utilities/KeyboardHelper.cs

A few changes for the WinUI branch so that the DataGrid control can be used in a WinUI 3 app:
- addressed some compilation warnings (casting event args to Control/ContentControl/FrameworkElement as recommended by compiler)
- removed all usages of Window.Current which is null in WinUI3:
* replaced usage of Window.Current.CoreWindow.PointerCursor with CoreWindow.GetForCurrentThread().PointerCursor
* replaced usage of Window.Current.CoreWindow.GetKeyState with CoreWindow.GetForCurrentThread().GetKeyState
- Bugfix
Application crashes because Window.Current == null causes null ref exceptions as soon as user tries to interact with the DataGrid.
No more exception, as in regular UWP.

DataGrid fixes for WinUI 3 usage

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationXaml.bind
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Constants.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.xaml
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/MSEdgeNotificationStyle.xaml
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/VSCodeNotificationStyle.xaml

Remove the `lock` statements used in `InAppNotification` as well as all the timers used to detect when the animation ends.
- Feature
The current `InAppNotification` implementation is using a lot of `lock` which are not needed since all the code lives in the UI thread. 
The control is no longer using any `lock`. All the notifications are now pushed to `_stackedNotificationOptions` which will control when the notification is displayed. This change allow us to set the appropriate content on the `ContentPresenter` when the control template is applied.
WE can also now push directly an `object` content as the notification payload. To make it …

Remove `lock` statements from `InAppNotification` control

---

Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj
Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
UnitTests/UnitTests.UWP/Helpers/Test_StorageFileHelper.cs
UnitTests/UnitTests.UWP/Helpers/Test_StreamHelper.cs
azure-pipelines.yml

- Bugfix 
Microsoft.Toolkit.Uwp.Notifications targets an end of life SDK (netcoreapp3.0). We should upgrade it to netcoreapp3.1.
Microsoft.Toolkit.Uwp.Notifications targets netcoreapp3.1.
I've also fixed a small race condition on the tests, since they run on parallel, per class, and two classes/tests were writing to the same file, which would eventually fail.

Updated TFM of Notifications package from netcoreapp3.0 to netcoreapp3.1.

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/MSEdgeNotificationStyle.xaml

Adjusting some style properties of `InAppNotification` like the margin between the dismiss button and the content requires a full retemplate. We can avoid this by using named resources and allow a "light" templating by adjusting only the resources we want.
- Feature
The default style of `InAppNotification` contains fixed values that are not easily customizable like the margin for the dismiss button:
```xaml
<Button x:Name="PART_DismissButton"
Margin="24,0,0,0" />
```
`InAppNotification` default style will now use named resources for some key layout properties.
This will allow us to only redefine those property to adjust the layout instead of going through a full retemplate.
```xaml
<Button x:Name="PART_DismissButton"
Margin="{StaticResource …
```

Enable light templating in InAppNotification

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.xaml
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/MSEdgeNotificationStyle.xaml
Microsoft.Toolkit.Uwp.UI.Controls/Strings/en-US/Resources.resw

The `InAppNotification` control is not fully accessible. It sends an automation event only when it contains text content and cannot easily be reached.
- Bugfix
`InAppNotification` is sending automation notification only when it contains text content.
The generated narrator strings are not properly localizable since they are concatenating a resource string with the content string but this may not be the appropriate way to do it in all cultures.
The code is also forcing the focus on the notification control which may break the user flow.
I've changed the automation integration:
- The automation event has been changed to `LiveRegionChanged`. It will be sent for any kind of content.
- The control has now a custom landmark so it can easily be reached …

Improve accessibility in InAppNotification

---

Microsoft.Toolkit.Parsers/Markdown/Blocks/YamlHeaderBlock.cs
UnitTests/UnitTests.UWP/Markdown/Parse/HorizontalRuleTests.cs

fix a problem when parsing with ---\n---\n

---

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.xaml
Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/MarkdownRenderer.Inlines.cs

- Bugfix
The `MarkdownTextBlock` fails to render text when a link contains inline code.
Links with inline code work fine, and use the same foreground color as inline code blocks.

Fixed rendering of markdown links with inline code

---

UnitTests/UnitTests.HighPerformance.Shared/Buffers/Internals/UnmanagedSpanOwner.cs
UnitTests/UnitTests.HighPerformance.Shared/Extensions/Test_ReadOnlySpanExtensions.Count.cs
UnitTests/UnitTests.HighPerformance.Shared/Extensions/Test_ReadOnlySpanExtensions.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_HashCode{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.For.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.For2D.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.ForEach.In.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.ForEach.Ref.cs
UnitTests/UnitTests.HighPerformance.Shared/UnitTests.HighPerformance.Shared.projitems

The CI will randomly fail with an out of memory error.
The error should be gone now. All the `Count` tests for the `HighPerformance` package are now reusing arrays from the same `ArrayPool<byte>` instance (since they use unmanaged types, so they can just be reinterpret-cast-ed to the necessary type every time). This should greatly reduce the total number of allocated arrays.

Reduced memory usage in HighPerformance tests

---

Microsoft.Toolkit/Extensions/TaskExtensions.cs
UnitTests/UnitTests.Shared/Extensions/Test_TaskExtensions.cs

- Bugfix
The `Task.GetResultOrDefault` can return `null` on some runtimes, if the input `Task` (`Task<T>`) instance is actually a subclass.
Eg. on UWP that type is sometimes some internal `AsyncValueBox<T>` type, which fails with that method (it returns `null`).
The extension is now more reliable and works with `Task<T>`-inherited type.

Improved reliability of Task.GetResultOrDefault

---

Microsoft.Toolkit.Mvvm/ComponentModel/ObservableObject.cs
Microsoft.Toolkit.Mvvm/ComponentModel/ObservableRecipient.cs
Microsoft.Toolkit.Mvvm/DependencyInjection/Ioc.cs
Microsoft.Toolkit.Mvvm/Messaging/Messenger.cs
Microsoft.Toolkit.Mvvm/Messaging/MessengerExtensions.cs
Microsoft.Toolkit.Mvvm/Microsoft.Toolkit.Mvvm.csproj

Marking this not as a draft so that the CI will run, but added the "DO NOT MERGE ⚠" tag as we might come up with further improvements to add to this PR before actually deciding to merge this and finalize the package.
- Bugfix 
- Feature
This PR includes some refinements and tweaks to the `Microsoft.Toolkit.Mvvm` package, like:
- Added new `ObservableRecipient.SetProperty` overloads with `Expression<Func<T>>` and `bool broadcast` params
- Fixed a possible bug in `Messenger.Type2.Equals` (just to be extra sure)
- Improved codegen for `ObservableRecipient.Set<T>(ref T, T, string)` (missing `EqualityComparer<T>.Default.Equals` inlining)
Please check if your PR fulfills the following …

Microsoft.Toolkit.Mvvm package (part 2)

---

Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Events.cs

Previously the symbol showing two lines on the GridSplitter was being exposed to the UI Automation Tree with a value outside the valid unicode range.
This removes the textblock containing the symbol from the UIA tree as it's not needed. The whole GridSplitter shows up in the tree. The symbol is just a nice visual extra on the control.
Bugfix 
Accessibility Insights for Windows (& Axe.Windows) reports an issue with the GridSplitter when used in any app.
No issue now reported.
This is a change to how a symbol is exposed to the UIA Tree. No visual or functional differences are included with this change.

GridSplitter accessibility issue fix

---

Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj

The System.ValueTuple NuGet library isn't supported from C++ WinRT apps, but the Notifications library seemingly doesn't need it anyways. It was seemingly added for no reason with the ToastContentBuilder code: https://github.com/windows-toolkit/WindowsCommunityToolkit/commit/9c38f71016e4ff33558937f69ed07fc2669bdc23
Nothing in the code uses Tuple, so not sure why it was added... Trying to remove it and seeing if there's any behavioral changes.
Bugfix
Cannot install Notifications library on C++ UWP apps, NuGet fails to install it
Should be able to install on C++ UWP apps (and use it)

Fix Notifications library for C++ apps

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs

When using InAppNotification and running the Show()/Dismiss()/Show() sequence "too fast", we never see the last notification.
- Bugfix
When running the following code in the `InAppNotification` sample page, we are not seeing the last notification:
```csharp
SampleController.Current.RegisterNewCommand("Show hide show", (sender, args) =>
{
_exampleInAppNotification?.Show("Notification 1", 0);
_exampleInAppNotification?.Dismiss();
_exampleInAppNotification?.Show("Notification 2", 0);
});
```
The `InAppNotification` content visibility is driven by two `VisualState`s and the control visibility is controlled using its `Visibility` property.
When going "too fast", we have the following sequence:
- show notification 1 is called
-- control visibility set …

Fix InAppNotification  not working show/hide/show sequence

---

Microsoft.Toolkit.Uwp/Extensions/StringExtensions.cs

- Bugfix
If you don't override the string resources, like the toolkit sample app, our localization methods throw.
We check if we have a resources on the current app on the first call. If not, just catch the exception and ignore it, using the built in resources.

Small fix when Independent loader might throw.

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Loading/LoadingCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Loading/LoadingPage.xaml.cs

- Bugfix
The blur is incorrectly applied to the loading icon on top of the sample page content:
The blur is now applied to the content of the page, with the icon being clearly visible:

Fixed incorrect blur in loading sample

---

Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml

- Bugfix
The GitHub icon is not positioned correctly
GitHub icon is centered
- [N/A] Tested code with current [supported SDKs](../readme.md#supported)
- [N/A] Pull Request has been submitted to the documentation repository [instructions](..\contributing.md#docs). Link: 
- [N/A] Sample in sample app has been added / updated (for bug fixes / features)
- [N/A] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)
- [N/A] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [N/A] Header has been added to all new source files (run …

Fix GitHub icon positioning

---

Microsoft.Toolkit/Diagnostics/Guard.String.cs
Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.String.cs

Some `Guard` APIs were incorrectly using the wrong capitalization for the `WhiteSpace` part, not following the same structure of the actual APIs in the BCL (eg. `string.IsNullOrWhiteSpace`). This PR deprecates them and adds new APIs with the right name.
...I'm sorry 😅
- API rename
- API deprecation

Shameful rename of [IsNullOr]WhiteSpace Guard APIs

---

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.xaml
Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExBase.Members.cs

- Bugfix
The `ImageEx.CornerRadius` property isn't working anymore.
Modifying `ImageEx.CornerRadius` works correctly.
With #3440, we bumped the minimum SDK to 1809 (build 17763), which is the first one with the `CornerRadius` being available in the `Control` class. I suspect building the controls package with that minimum SDK caused an issue with `ImageEx` defining the `CornerRadius` property again (using `new`), so that the XAML `TemplateBinding` ended up failing to find the correct property to bind to. It might also be because setting the property in XAML ended up setting the value for the incorrect duplicate one, so that binding was never update. Regardless, with that minimum version available there's no reason to duplicate that property in …

Fixed ImageEx.CornerRadius property

---

Microsoft.Toolkit.HighPerformance/Streams/MemoryStream.Validate.cs
UnitTests/UnitTests.HighPerformance.Shared/Streams/Test_MemoryStream.cs

- Bugfix
Seeking to the end of a `Stream` from a `Memory<T>` or other types in the `HighPerformance` package throws an exception.
Seeking to the end of the stream is now allowed. This is consistent to other `Stream` types in the BCL.

Fixed MemoryStream seek to end validation

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj

Stop the sample app from always triggering a rebuild, even if no code has been changed.
- Other... Please describe: Change in compilation behavior of the Sample App
VS will always rebuild the sample app when launched for debugging.
Now VS will only rebuild the code if something has changed.
**All unchecked options above are not applicable**

Stop the Sample app needing to be rebuilt even when nothing has changed

---

Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
Windows Community Toolkit.sln

Remove the 'native' target framework that is causing issues on VS 16.8 for now until a long-term solution can be found.
Current theory is 16.8 broke the workaround we were using to address this issue: https://github.com/NuGet/Home/issues/5154
FYI @andrewleader @azchohfi

Temp - Remove 'native' target for Notifications package to unblock CI

---

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs

I took a quick look at the ScrollHeader bug and it was simple enough so:   
The Scrollheader's `StickyHeaderBehavior` adjusts scrolling when focusing an element of the ScrollViewer if it's slightly hidden by the header. This imitates standard ScrollViewer behavior.
However, `ScrollViewer.GotFocus` also triggers if we open a Flyout on a ListItem, but since the scrolling calculation didn't plan for that, it ends up scrolling the list by the height of the Flyout.  
An easy fix for this is to check if the focused element is really part of the list and not just a popup, which can be done by checking if the element has a parent or not.  
- Bugfix
If a Popup/Flyout of any kind is assigned to either the ListView or its items, opening it by right-click …

Fix Sticky ScrollHeader causing unwanted scrolling with Popups on ListItems

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DispatcherQueueHelper/DispatcherQueueHelperPage.xaml.cs
Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs
Microsoft.Toolkit.Uwp.SampleApp/Shell.Search.cs
Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Light.cs
Microsoft.Toolkit.Uwp.UI/Extensions/ScrollViewer/ScrollViewerExtensions.MiddleClickScrolling.cs
Microsoft.Toolkit.Uwp/Extensions/DispatcherQueueExtensions.cs
UnitTests/UnitTests.XamlIslands.UWPApp/XamlIslandsTest_Gaze.cs

- Bugfix
- Refactoring
Some leftover `DispatcherQueue` usages (some causing a build error).
All code is now using `DispatcherQueue` instead.

Removed leftover DispatcherQueue usages

---

Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitView.cs

Sept towards #3578. 
OrbitView uses the Toolkit Animation.Expressions API.
OrbitView uses [ExpressionAnimation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.expressionanimation)

Orbitview remove animation expressions

---

Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.cs

Sept towards #3578.
Remove the `TileControl`'s usage of the `Animations.Expressions` ns and thus the animations package.
`TileControl`'s uses `Animations.Expressions` to build expression animation.
`TileControl`'s uses strings to build expression animation.

TileControl: Remove Animations.Expressions usage

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/JsonObjectSerializer.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/LocalObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/RoamingObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj
Microsoft.Toolkit.Uwp/Properties/Microsoft.Toolkit.Uwp.rd.xml
UnitTests/UnitTests.UWP/Helpers/Test_StorageHelper.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

Change implementation of JsonObjectSerializer to use DataContractJsonSerializer 
Microsoft.Toolkit.Uwp uses JsonSerializer 
Microsoft.Toolkit.Uwp uses DataContractJsonSerializer 

Replace JsonSerializer with DataContractJsonSerializer in Microsoft.Toolkit.Uwp.

---

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.AttachedProperties.cs

- Bugfix
`InAppNotification.KeyFrameDuration` dependency property data type is now the same as the dependency property type.

fix: Invalid InAppNotification.KeyFrameDuration default value data type

---

SmokeTests/SmokeTest.csproj
SmokeTests/SmokeTest.sln
SmokeTests/SmokeTests.proj
build/build.cake

Adjusts SmokeTest project and Cake script to pass in the Version of the Toolkit being built to ensure NuGet restores the proper version when building the SmokeTest projects (and used for analysis later).
- Bugfix
SmokeTests will grab latest from NuGet
SmokeTests will grab version from CI

Fix SmokeTest Projects to Use Version from CI

---

Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml.cs

Forgot to check some scenarios in the original update to #3648 and broke scenarios of pages with code-behind. This PR resolves that and forward-fixes all sample types (XAML only, code-behind, code-behind + XamlRoot).
- Bugfix
If a sample page didn't have a `XamlRoot` defined in it's page it was getting obliterated in the `UpdateXamlRender` call.
Clearly defined what a `SamplePage` was (to be the backing instance of a sample (if one)). Then used that to instead overwrite it's content as intended if there is no `XamlRoot` instead of the entire page itself.
i.e. the bug was that we were replacing the entire page with the rendered XAML and therefore no longer held an instance to call …

Fixes #3673 and resolves issues with some samples not working correctly

---

SmokeTests/SmokeTestAnalysis.ps1
SmokeTests/SmokeTestDownloadNuGetVersion.ps1

Adds some additional metrics for how the smoke test projects impact compiled binary sizes.
Only outputs the loose dll sizes
Also looks at the compiled application size.
There's another script to help in downloading a specific NuGet package version, though the version passing into the SmokeTests has to be disabled manually currently to make most effective use of it.

Additional Smoke Test Scripts

---

Microsoft.Toolkit.HighPerformance/Extensions/ArrayExtensions.2D.cs
Microsoft.Toolkit.HighPerformance/Extensions/ArrayExtensions.3D.cs
Microsoft.Toolkit.HighPerformance/Extensions/BoolExtensions.cs
Microsoft.Toolkit.HighPerformance/Extensions/MemoryExtensions.cs
Microsoft.Toolkit.HighPerformance/Extensions/ReadOnlyMemoryExtensions.cs
Microsoft.Toolkit.HighPerformance/Extensions/ReadOnlySpanExtensions.cs
Microsoft.Toolkit.HighPerformance/Extensions/SpanExtensions.cs
Microsoft.Toolkit.HighPerformance/Helpers/BitHelper.cs
Microsoft.Toolkit.HighPerformance/Helpers/ParallelHelper.ForEach.IInAction2D.cs
Microsoft.Toolkit.HighPerformance/Helpers/ParallelHelper.ForEach.IRefAction2D.cs
Microsoft.Toolkit.HighPerformance/Memory/Memory2D{T}.cs
Microsoft.Toolkit.HighPerformance/Memory/ReadOnlyMemory2D{T}.cs
Microsoft.Toolkit.HighPerformance/Memory/ReadOnlySpan2D{T}.Enumerator.cs
Microsoft.Toolkit.HighPerformance/Memory/ReadOnlySpan2D{T}.cs
Microsoft.Toolkit.HighPerformance/Memory/Span2D{T}.Enumerator.cs
Microsoft.Toolkit.HighPerformance/Memory/Span2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Extensions/Test_ArrayExtensions.2D.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.ForEach.In2D.cs
UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.ForEach.Ref2D.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_Memory2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_ReadOnlyMemory2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_ReadOnlySpan2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_Span2D{T}.cs

- Refactoring
- Improvements
Following the suggestion from @mrlacey for non-breaking changes, this PR moves the new `Span2D<T>` and `Memory2D<T>` types introduced in version 7.0 to the root `Microsoft.Toolkit.HighPerformance` namespace (instead of `.Memory`). This is simpler to use for consumers, it makes sense given that the root namespace already contains some other "primitive" types, and it's also more consistent to how the `Span<T>` and `Memory<T>` types are included in the `System.Memory` package, but are still located in the root `System` namespace.
This PR also includes some minor codegen improvements to some other extensions, while I was at it 😄

Simplified namespaces in HighPerformance package

---

Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs

Smaple.cs LookForTypeByName(string) add assmbiles to search in
- Microsoft.Toolkit.Uwp.UI.Controls -> Microsoft.Toolkit.Uwp.UI.Controls.Core
- Microsoft.Toolkit.Uwp.UI.Controls.Layout
- Microsoft.Toolkit.Uwp.UI.Controls.Media
- Microsoft.Toolkit.Uwp.UI.Controls.Media
- Bugfix

Smaple.cs LookForTypeByName(string) add assmbiles to search for types.

---

Microsoft.Toolkit.Mvvm/ComponentModel/ObservableObject.cs
Microsoft.Toolkit.Mvvm/ComponentModel/ObservableRecipient.cs
Microsoft.Toolkit.Mvvm/ComponentModel/ObservableValidator.cs
Microsoft.Toolkit.Mvvm/DependencyInjection/Ioc.cs
Microsoft.Toolkit.Mvvm/Input/AsyncRelayCommand.cs
Microsoft.Toolkit.Mvvm/Input/AsyncRelayCommand{T}.cs
Microsoft.Toolkit.Mvvm/Input/Interfaces/IAsyncRelayCommand{T}.cs
Microsoft.Toolkit.Mvvm/Input/Interfaces/IRelayCommand{T}.cs
Microsoft.Toolkit.Mvvm/Input/RelayCommand{T}.cs
Microsoft.Toolkit.Mvvm/Messaging/IMessengerExtensions.cs
Microsoft.Toolkit.Mvvm/Messaging/Internals/Microsoft.Collections.Extensions/DictionarySlim{TKey,TValue}.cs
Microsoft.Toolkit.Mvvm/Messaging/Messages/AsyncCollectionRequestMessage{T}.cs
Microsoft.Toolkit.Mvvm/Messaging/Messages/CollectionRequestMessage{T}.cs
Microsoft.Toolkit.Mvvm/Messaging/StrongReferenceMessenger.cs
Microsoft.Toolkit.Mvvm/Messaging/WeakReferenceMessenger.cs
Microsoft.Toolkit.Mvvm/Microsoft.Toolkit.Mvvm.csproj
UnitTests/UnitTests.NetCore/UnitTests.NetCore.csproj
UnitTests/UnitTests.Shared/Mvvm/Test_AsyncRelayCommand{T}.cs
UnitTests/UnitTests.Shared/Mvvm/Test_ObservableValidator.cs
UnitTests/UnitTests.Shared/Mvvm/Test_RelayCommand{T}.cs

This PR is for tracking all changes/fixes/improvements to the `Microsoft.Toolkit.Mvvm` package following the Preview 4.
- Feature
- Improvements
This PR is used to track and implement new features and tweaks for the `Microsoft.Toolkit.Mvvm` package.
See the linked issue for more info, and for a full list of changes included in this PR.

[Feature] Microsoft.Toolkit.Mvvm package (Preview 5)

---

Microsoft.Toolkit.Uwp.UI.Controls.Layout/Expander/Expander.xaml

Fixes #3070
- Style Change
The Expander Header is left aligned
The expander header will stretch to fit it's space. **BREAKING CHANGE**
This is a breaking **style* change. Content that was left aligned will now stretch. This could change how an application looks
Cherry picked from #3096

#3070 Stretch the content of the expander header

---

Microsoft.Toolkit.Mvvm/ComponentModel/ObservableValidator.cs
UnitTests/UnitTests.Shared/Mvvm/Test_ObservableValidator.cs

- Bugfix
- Incorrect loading of display names for validated properties
- Repeated error messages after validation
Fixed the errors above.
Opening as a draft to have the CI run, but I'm still investigating the second issue from the list above.

Bug fixes to ObservableValidator

---

Directory.Build.props
azure-pipelines.yml
build/build.cake

This PR updates NBGV, as well as makes sure 'that nbgv cloud' is called on the Smoke Test step, which was failing the smoke tests sometimes.
- Bugfix 
Sometimes the smoke test tries to restore the wrong version of the nugets.
Now the same version should be properly used on both ADO jobs.

Changed to Cake.GitVersioning and added 'nbgv cloud' on smoke test job.

---

Directory.Build.props
Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.nuspec

Fixes the nuget license/icon file based on #3765, single commit.

Update license and icon based on @kyaa-dost's investigation

---

UnitTests/UnitTests.XamlIslands.UWPApp/UnitTests.XamlIslands.UWPApp.csproj

For some reason this fixes the build errors, it shouldint as its already a transitive dep.
Fixes build issue with `UnitTest.XamlIslands.UWPApp`
- Bugfix

[Bugfix] Include Microsoft.XamlIslands in UnitTest.XamlIslands.UWPApp

---

Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj

- Dependency reduction
The `.Animations` package has a reference on `System.ValueTuple` that we don't actually need or use.
That reference is no longer there. This can possibly bring a small reduction in binary size, but most importantly it will avoid having public APIs leaking to consumers through indirect references that are hard to keep track of.
```diff
- Microsoft.Toolkit.Uwp.UI.Animations Additional Max Footprint: 623,163 bytes
+ Microsoft.Toolkit.Uwp.UI.Animations Additional Max Footprint: 591,830 bytes
Microsoft.Toolkit.Uwp.UI.Animations Additional Min Footprint: 4,099,518 bytes
App Diff: (.exe) = 26,624
App Diff: (.xml) = 2,287
- App Diff: (.appxsym) = 110,360
+ App Diff: (.appxsym) = 110,356
Size Diff: AppxBundleManifest.xml = 25
- …
```

Removed System.ValueTuple package reference from Animations

---

Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs

- Bugfix (sample app)
There is a crash in the items animations when looking for samples. This was unrelated from the actual animation APIs, and the crash was happening because the parent of the `DropShadowPanel` for each item was actually `null` if the items were being swapped by a text change while one was animated, so the animation was being invoked on `null`, resulting in a crash. I've just added two checks to skip the animation out in case the whole list is being refreshed, as the item containers would all be discarded anyway.
The crash is fixed.

Fixed a crash with the items list animations in Sample app

---

Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.Default.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.Factories.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.KeyFrames.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.PropertyBuilders.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.Setup.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/Interfaces/IPropertyAnimationBuilder{T}.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/NormalizedKeyFrameAnimationBuilder{T}.Composition.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/NormalizedKeyFrameAnimationBuilder{T}.Xaml.cs
Microsoft.Toolkit.Uwp.UI.Animations/Builders/TimedKeyFrameAnimationBuilder{T}.Composition.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.cs
Microsoft.Toolkit.Uwp.UI.Animations/Xaml/Abstract/Animation.cs
Microsoft.Toolkit.Uwp.UI.Animations/Xaml/Abstract/Animation{TValue,TKeyFrame}.cs
Microsoft.Toolkit.Uwp.UI.Animations/Xaml/Abstract/CustomAnimation{TValue,TKeyFrame}.cs
Microsoft.Toolkit.Uwp.UI.Animations/Xaml/Abstract/ImplicitAnimation{TValue,TKeyFrame}.cs
Microsoft.Toolkit.Uwp.UI.Animations/Xaml/Default/ClipAnimation.cs
Microsoft.Toolkit.Uwp.UI.Media/Animations/Abstract/EffectAnimation{TEffect,TValue,TKeyFrame}.cs

- Feature
- Improvements
This PR tracks new changes and tweaks for the `Microsoft.Toolkit.Uwp.UI.Animations` package before the 7.0 release.
Changes are done according to feedbacks and requests from developers trying out the Preview 5 release.
This PR contains the following changes:
- All `AnimationBuilder` and XAML animation types now use `AnimationDelayBehavior.SetValueBeforeDelay` by default
- New `DelayBehavior` property available for XAML animation types (ignored when an animation is on the XAML layer)
- New `delayBehavior` parameter available for the explicit `AnimationBuilder` keyframe animation APIs (the more advanced ones)
- New `RepeatOption` parameter now available for all `AnimationBuilder` APIs (default, keyframe, etc.)
Opening as a …

Animations package improvements

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Animations/Activities/InvokeActionsActivityCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Animations/Activities/StartAnimationActivityCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json

No C# examples for the explicit animations.
Added two new C# sample pages with different examples of how to use `AnimationBuilder`.

Added AnimationBuilder C# sample code

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TextBoxMask/TextBoxMask.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TextBoxMask/TextBoxMaskPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TextBoxRegex/TextBoxRegex.bind
Microsoft.Toolkit.Uwp.UI/Extensions/TextBox/SurfaceDialOptions.cs
Microsoft.Toolkit.Uwp.UI/Extensions/TextBox/TextBoxExtensions.Mask.Internals.cs
Microsoft.Toolkit.Uwp.UI/Extensions/TextBox/TextBoxExtensions.Mask.Properties.cs

- Refactoring with API changes
The mask placeholder property is called `PlaceHolder`.
It's now called `MaskPlaceholder` instead.

Changed TextBoxExtensions.PlaceHolder property name

---

UnitTests/UnitTests.UWP/Extensions/Test_PointExtensions.cs
UnitTests/UnitTests.UWP/Extensions/Test_RectExtensions.cs
UnitTests/UnitTests.UWP/Extensions/Test_SizeExtensions.cs

- Unit test fixes
The tests for `Point`/`Rect`/`Size` extensions are skipped, and some are just incorrect anyway and fail even when run.
Fixed those tests to run correctly.

Fixed unit tests for Point/Rect/Size extensions

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/TileControl/TileControl.cs

The LoadCompleted event was never unregistering and firing twice when reloaded across monitors causing an issue with the TaskCompletionSource.
- Bugfix
Would crash when moving between different monitors (of different DPIs?)
No Crash.

Fixes #3629 TileControl crashes when moving monitors

---

Microsoft.Toolkit.Uwp.UI/Extensions/FrameworkElement/FrameworkElementExtensions.LogicalTree.cs

As I was writing the SwitchPresenter docs, I was doing some tests about how it loads/doesn't load content into the VisualTree. I noticed the VisualTree could find the descendants, but our logical helpers could not.
- Bugfix
Can't find the loaded children in the Logical Tree.
If ContentPresenter (like SwitchPresenter) have content which are also Framework Elements (and not data) then we'll continue walking like we would with a ContentControl.
This is important as some templates for controls use ContentPresenter more often than ContentControl in other places as ContentPresenter is lighter-weight than ContentControl.

Add ContentPresenter to Logical Tree helpers

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StringExtensions/StringExtensionsPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StringExtensions/StringExtensionsPage.xaml.cs

StringExtensions: Switch to italic instead of blue, fix bug with bold effect not being applied

---

Microsoft.Toolkit.Uwp.UI.Controls.Layout/GridSplitter/GridSplitter.Events.cs

We had fixed this before but released it directly to a 6.1.1 tree and never merged it back to main. 
I've cherry-picked the commit and re-applied back on top of our latest code so that it's in the proper place.
- Bugfix

Don't have the GridSplitterHandle show in UIA tree

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/Microsoft.Toolkit.Uwp.UI.Controls.Core.csproj
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.csproj
Microsoft.Toolkit.Uwp.UI.Controls.Input/Microsoft.Toolkit.Uwp.UI.Controls.Input.csproj
Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj
Microsoft.Toolkit.Uwp.UI.Controls.Markdown/Microsoft.Toolkit.Uwp.UI.Controls.Markdown.csproj
Microsoft.Toolkit.Uwp.UI.Controls.Media/Microsoft.Toolkit.Uwp.UI.Controls.Media.csproj
Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Microsoft.Toolkit.Uwp.UI.Controls/readme.txt

No description for Controls meta package.
Description for Controls meta package.

Add description for Controls meta package

---

Microsoft.Toolkit.Uwp.UI/Extensions/StringExtensions.cs

Fixed wrong bracket matching in `StringExtensions.ToVectorN(string)` and `StringExtensions.ToQuaternion(string)` methods.
- Bugfix
Sample app crashes.
Sample app does not crash.

Fix wrong bracket matching when parsing Vectors

---

UnitTests/UnitTests.UWP/Extensions/Test_StringExtensions.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

- Unit tests
There are no unit tests for `ToVector2/3/4` and `ToQuaternion` extensions.
Added unit tests for all those extensions.

Added unit tests for Vector2/3/4/Quaternion parsing

---

Microsoft.Toolkit.Uwp.Notifications/Toasts/Compat/ToastNotifierCompat.cs

For unpackaged apps, we were accidently overwriting the Group property on toasts if developers were setting that. Thus, scenarios like #3835 where a progress bar toast is using both group and tag, updating the progress bar didn't work
- Bugfix
Group property gets overwritten
Group property only gets written if developers didn't specify it
Verified via...

Fix notification Group property being overwritten in unpackaged apps

---

Microsoft.Toolkit.Uwp.Notifications/Toasts/Compat/Desktop/Win32AppInfo.cs

- Bugfix
If a desktop app's entry assembly is null, sending a notification throws an exception
It'll correctly fall back to the process name and work.
Customer verified that the fix fixes their problem!

Handle Assembly being null

---

Microsoft.Toolkit.Uwp.UI.Controls.Primitives/WrapPanel/WrapPanel.cs

The `WrapPanel` is not rendering its children as expected if one of them is collapsed.
- Bugfix 
Children after the collapsed one may not be rendered.
All visible children will be displayed
This issue comes from `UpdateRows()` which ignores/skips the collapsed items since they are not part of the final layout. When doing the `Arrange()` pass, we were not accounting this and were trying to arrange the collapsed children. 
I've updated the `Arrange()` method to properly ignore the collapsed items and be sure to only arrange the visible items (the one from our pre-computed rows collection).
I used the following snippet to validate the changes:
```xml
<StackPanel>
<controls:WrapPanel …
```

Fix WrapPanel behavior with collapsed children

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/InAppNotification/InAppNotification.xaml

Fixes #3871
Changes the border from transparent to SystemControlTransientBorderBrush so that changing the BorderThickness property alone can make an impact.

Fixes #3871 - Can't see InAppNotification border

---

Microsoft.Toolkit.Uwp.SampleApp/Properties/Default.rd.xml

- Sample app bugfix
Running the sample in "InvokeActionsActivity" sample page crashes the sample app.
The "InvokeActionsActivity" sample page works correctly.

Fixed crash in InvokeActionsActivity sample page

---

Microsoft.Toolkit.Uwp.DeveloperTools/FocusTracker/FocusTracker.cs
Microsoft.Toolkit.Uwp.SampleApp/App.xaml.cs

Updates the FocusTracker control to use a different API which won't constantly try and spam calls to look for the FocusedElement, unclear if that or the DispatcherQueueTimer were to blame for original issue, but hopefully this should be resolved now, was no longer able to reproduce.
- Bugfix 
FocusTracker was using a DispatcherQueueTimer (updated from DispatcherTimer late in 7.0) to constantly update what the FocusedElement it was tracking was.
Use the new `FocusManager.GotFocus` event added in 1809 (our new min version) to only update the control when the focused element has changed. This should provide a better more stable experience with similar practical results.
Please check if your PR …

Fix for FocusTracker Sample App hang

---

Microsoft.Toolkit.Uwp.Notifications/Toasts/Compat/Desktop/Win32AppInfo.cs
Microsoft.Toolkit.Uwp.Notifications/Toasts/Compat/ToastNotificationManagerCompat.cs

On versions 19042 and older of Windows 10, when an unpackaged desktop app used an AUMID that contained `\` (common occurrence since AUMID is the EXE path unless app has a shortcut with an AUMID set), the notifications settings would consider this as a disabled app and not allow toggling settings.
Fixed this by automatically replacing `\` with `/` in AUMIDs, and using that instead. That change means that apps that were using 7.0.0 and update to 7.0.1 would be treated as "new" apps though, so added some migration logic to at least clean up the old notifications, so that users don't see two apps in Action Center and don't continue to receive scheduled notifications from the old app.
- Bugfix
Current behavior described in #3870
Settings page is now …

Fix notification settings disabled for unpackaged apps on 19042 and older

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml.cs

Create Remote_DOCS compiler directive to make it easier to debug, now Debug mode only uses local packages assets, and can add compiler directive to test remote doc scenarios and caching while in Debug mode still.
Fixes issue where images wouldn't be pulled from packaged assets in offline mode.
Images weren't showing up in released app.
Images are properly cached and retrieved from package if offline.

Fix Remote Doc/Image Caching in Sample App

---

Microsoft.Toolkit.HighPerformance/Extensions/ArrayExtensions.3D.cs
Microsoft.Toolkit.HighPerformance/Memory/Memory2D{T}.cs
Microsoft.Toolkit.HighPerformance/Memory/ReadOnlyMemory2D{T}.cs
Microsoft.Toolkit.Mvvm/Messaging/WeakReferenceMessenger.cs
Microsoft.Toolkit.Uwp.UI.Controls.Primitives/SwitchPresenter/SwitchPresenter.cs
Microsoft.Toolkit.Uwp.UI.Media/Geometry/Utils.cs
Microsoft.Toolkit.Uwp/Extensions/DispatcherQueueTimerExtensions.cs
UnitTests/UnitTests.UWP/PrivateObject.cs

Fix few typos in the code base. Note that only comments are impacted by this change.
N/A
N/A

Fix few typos in comments

---

build/build.cake

InheritDoc fails when there are more than one source xml doc for a specified target.
This is from "Nerdbank.GitVersioning" project and is not an issue here.
The inherit doc step started to fail, this fixes it.
- Bugfix
All branches without this change are failing the inherit doc build step.
Inherit doc build step doesn't fail 

Workaround for "InheritDoc" issue with "Nerdbank.GitVersioning" xml docs

---

Microsoft.Toolkit/Extensions/TaskExtensions.cs
UnitTests/UnitTests.Shared/Extensions/Test_TaskExtensions.cs

- Bugfix
`TaskExtensions.GetResultOrDefault()` incorrectly returns a boxed `VoidTaskResult` when used on `Task.CompletedTask`.
This is because this instance is actually a cached `Task<T>` with some internal type.
For the implementation detail, [see here](https://github.com/dotnet/runtime/blob/19caa608b9d226d0041d5ed1c7b0d5911fb13d2b/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1457-L1462).
This PR adds special handling for `Task.CompletedTask` to ensure that `null` is returned.
There is also a new unit test for the extension in this case.

Fixed TaskExtensions.GetResultOrDefault() for Task.CompletedTask

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DispatcherQueueHelper/DispatcherQueueHelperCode.bind

This will fix the oversight in the documentation after the 7.0 breaking change
Sample app changes
The sample app documentation use the old ExecuteOnUIThreadAsync methos
The sample app documentation use the new EnqueueAsync method

Update ExecuteOnUIThreadAsync to EnqueueAsync

---

Microsoft.Toolkit.Mvvm/Messaging/WeakReferenceMessenger.cs

- Bugfix-ish
The .NET 5 target currently uses the .NET Standard 2.0 code path within `WeakReferenceMessenger`.
Not technically a bug since the implementation does work, but it can be greatly simplified like on .NET Standard 2.1.
This should also make the code add slightly less GC pressure over time due to less additional data structures in use.

Enabled correct WeakReferenceMessenger path on .NET 5

---

Microsoft.Toolkit.Uwp.SampleApp/Models/PropertyDescriptor/PropertyKind.cs
Microsoft.Toolkit.Uwp.UI.Controls.Media/InfiniteCanvas/Commands/InfiniteCanvasCreateTextBoxCommand.cs
Microsoft.Toolkit.Uwp.UI.Controls.Media/InfiniteCanvas/Controls/InfiniteCanvasVirtualDrawingSurface.Commands.cs
Microsoft.Toolkit.Uwp.UI.Controls.Media/InfiniteCanvas/InfiniteCanvas.TextBox.cs
Microsoft.Toolkit.Uwp.UI.Controls.Media/InfiniteCanvas/InfiniteCanvas.cs
Microsoft.Toolkit.Uwp.UI.Controls.Media/InfiniteCanvas/InfiniteCanvas.xaml

User can now input a font size via typed text and not only selection from out provided sizes.
- Feature
You have to enter a font size with text in the textbox, I used the standard font sizes that are given in Microsoft Office PowerPoint (increments from 8 to 96).
User can select the font size themselves now

Infinite Canvas dropdown font selector 2

---

UnitTests/UnitTests.UWP/UI/Controls/Test_WrapPanel_Visibility.cs

Some tests were failing if your resolution was 150% (not 100%).
This fixes the 3 failing tests.
- Bugfix
Tests fail if your display scale is 150%
Tests pass independently from your display scale.

Turned off layout rounding for failing tests

---

Windows Community Toolkit (NET).slnf

- Infrastructure
There is no solution filter or solution available to only work on .NET-based projects. This has two issues:
- It is extremely cumbersome for developers on either other platforms (eg. Linux, iOS) or on Windows but without the necessary UWP SDKs installed to open the solution and contribute, as they'd have lots of projects failing to open, VS showing all sorts of warnings and error windows, etc.
- Even for developers with all needed SDKs, opening the entire solution every time even when just working on a .NET component takes longer to load, makes VS slower due to the higher number of loaded projects, makes build times longer, etc.
There is now a solution filter with just the .NET projects, which makes it super easy to only load up …

Added solution filter for .NET projects

---

Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.cs
UnitTests/UnitTests.UWP/UI/Animations/Test_AnimationBuilderStart.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

- Feature
There is no synchronous overload for `AnimationBuilder.Start` taking a completion callback.
This PR adds a new `AnimationBuilder.Start(UIElement, Action)` overload, with an efficient implementation not using an async state machine to schedule and invoke the callback when the animation group(s) complete.

Added AnimationBuilder.Start(UIElement, Action) overload

---

Microsoft.Toolkit.HighPerformance/Memory/ReadOnlySpan2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_ReadOnlySpan2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_Span2D{T}.cs

- Bugfix
`ReadOnlySpan2D<T>.Slice` has the incorrect ordering for the `height` and `width` parameters, which is inverted with respect to those in `Span2D<T>.Slice`. This is an oversight from a refactor in the original PR, and as a result it also causes the `ReadOnlySpan2D<T>.this[Range, Range]` indexer to fail for `ReadOnlySpan2D<T>`. This PR fixes both issues and adds a new series of tests for the two indexers as well. We probably didn't notice this before since those indexers are not available on UWP 🤔
> **NOTE:** this PR technically introduces a breaking change (swapped parameters in the `.Slice` method, but as that's an issue and not intended, and also because they're in the right order in `Span2D<T>`, it's more of a fix than an actual …

Fixed ReadOnlySpan2D<T>.Slice parameters order

---

Microsoft.Toolkit.Uwp.UI.Animations/Builders/TimedKeyFrameAnimationBuilder{T}.cs

- Bugfix
The `TimedKeyFrame` APIs are using an incorrect expression, resulting in the animation not playing.
Fixed the expression to calculate the normalized timestamp of timed keyframes, so they work fine now 😄

Fixed incorrect timed keyframe expression

---

Microsoft.Toolkit.HighPerformance/Memory/ReadOnlySpan2D{T}.cs
Microsoft.Toolkit.HighPerformance/Memory/Span2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_ReadOnlySpan2D{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Memory/Test_Span2D{T}.cs

- Bugfix
`[ReadOnly]Span2D<T>.TryGetSpan` throws an exception when wrapping a `T[]` instance on legacy frameworks.
`[ReadOnly]Span2D<T>.TryGetSpan` works correctly on legacy frameworks.

Fix [ReadOnly]Span2D<T>.TryGetSpan on legacy frameworks

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Visual Extensions/VisualExtensionsCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Visual Extensions/VisualExtensionsPage.xaml
Microsoft.Toolkit.Uwp.UI/Extensions/VisualExtensions.cs
UnitTests/UnitTests.UWP/UI/Extensions/Test_VisualExtensions.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

- Feature
The `VisualExtensions` class lacks an attached property to set the `"Translation"` property of a UI element.
This PR adds a `VisualExtensions.Translation` attached property.
The behavior and implementation mirrors that of the other extensions.
Here's a GIF that shows both XAML hot-reload and this extension being combined with the animation system 🚀 🚀 🚀
This extension now works just fine, and can be combined with the existing animation APIs to start a translation animation with an implicit starting point just fine. The reason why it wasn't originally working was because I incorrectly assumed that the "Translation" property in question was `Visual.TransformMatrix.Translation`, but turns out that wasn't the case 😄
When setting …

Added VisualExtensions.Translation attached property

---

Microsoft.Toolkit.Uwp.Notifications/Tiles/Builder/TileContentBuilder.cs
UnitTests/UnitTests.Notifications.Shared/TestTileContentBuilder.cs
UnitTests/UnitTests.Notifications.Shared/UnitTests.Notifications.Shared.projitems

- Bugfix
- Unit test added
Issue #3955 
Text on **Wide tile** is correctly set without throwing `NullReferenceException`.

Fixed NRE when setting text on Wide tile only via TileContentBuilder

---

Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionNodes/ExpressionNode.cs
Microsoft.Toolkit.Uwp.UI.Animations/Extensions/System/GuidExtensions.cs
Microsoft.Toolkit.Uwp.UI.Media/Extensions/System/GuidExtensions.cs
Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Effects.Internals.cs
Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Effects.cs
Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Initialization.cs
Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Merge.cs
Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.cs

- Bugfix
Crash with .NET Native, documented in the related issue.
The logic has been changed to not rely on APIs that might have a behavioral change under .NET Native.

Fixed ExpressionNode.EnsureReferenceInfo() crash with .NET Native

---

Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs
UnitTests/UnitTests.UWP/UI/Collection/DataSource.cs
UnitTests/UnitTests.UWP/UI/Collection/Test_IncrementalLoadingCollection.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

Only Increment CurrentPageIndex if Source.GetPagedItemsAsync's task completes with RanToCompletion
- Bugfix
`CurrentPageIndex` is incremented before `GetPagedItemsAsync` completes. If it does not complete or fails it is still incremented.  
`CurrentPageIndex` is only incremented once `GetPagedItemsAsync`'s Task completes with `RanToCompletion.

incremnenralLoading-pageIndex-fix

---

UITests/UITests.App/App.AppService.xaml.cs
UITests/UITests.App/HomePage.xaml
UITests/UITests.App/HomePage.xaml.cs
UITests/UITests.App/MainTestHost.xaml
UITests/UITests.App/MainTestHost.xaml.cs
UITests/UITests.App/UITests.App.csproj
UITests/UITests.Tests.MSTest/UITests.Tests.MSTest.csproj
UITests/UITests.Tests.Shared/Controls/RangeSelectorTest.cs
UITests/UITests.Tests.Shared/Controls/RangeSelectorTestPage.xaml
UITests/UITests.Tests.Shared/Controls/RangeSelectorTestPage.xaml.cs
UITests/UITests.Tests.Shared/Controls/TextBoxMaskTest.cs
UITests/UITests.Tests.Shared/Examples/SimpleTest.cs
UITests/UITests.Tests.Shared/TestAssembly.cs
UITests/UITests.Tests.Shared/UITestBase.cs
UITests/UITests.Tests.TAEF/UITests.Tests.TAEF.csproj
azure-pipelines.yml

After adding a basic test for the `RangeSelector` the UI test began to fail, sometimes other tests than the added one. There was some issues with managing resources both in the TAEF environment and in MSTest. Now those issues and inconsistencies should be ironed out.

Fix issues with mutiple UI Tests

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationCode.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationPage.xaml.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/LocalObjectStorageHelper.cs
Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs
Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj
UnitTests/UnitTests.UWP/Helpers/Test_SystemInformation.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

Doc # [511](https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/pull/511)
Add "PreviousVersionInstalled" to SystemInformation to understand which version the app is updated from, to handle specific migration/changes.
Feature 
SystemInformation doesn't expose the PreviousVersionInstalled property
Expose "PreviousVersionInstalled" property

Add "PreviousVersionInstalled" to SystemInformation

---

Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj

Replaces the use of the hardcoded '16.0' string in the Notification package to use the msbuild variable $(VisualStudioVersion).
- Bugfix
Fails to build on VS2022.
Builds on both VS2019 and VS2022.

Small fix for supporting VS2022.

---

Microsoft.Toolkit.Mvvm/Messaging/WeakReferenceMessenger.cs
UnitTests/UnitTests.Shared/Mvvm/Test_Messenger.cs

Bugfix
The attached message handlers of a WeakReferenceMessenger do not get called anymore correctly for all registered objects after unregistering one of them.
The attached message handlers get called for all registered objects.
There was an issue with the enumerator of the ConditionalWeakTable. The linked list nodes were not iterated correctly when a key gets removed while enumerating. In this case the "Next"-property of the node was set to null and the while loop stopped immediately (without checking the remaining nodes). 
As a fix the next node is now kept as a locale variable so that it does not get lost when removing the key.

Fix register/unregister issues of WeakReferenceMessenger

---

Microsoft.Toolkit.Uwp.SampleApp/Controls/SampleAppMarkdownRenderer.cs

Style could have been null on the check for style.Ignore, moved the
check so it cant be null.
In the SampleApp there are docs that we render that have the markdown syntax
```md
> Hello world
```
And should be rendered as 
> Hello world
The issues is our code that checks for special quotes with special style tags like `[!NOTE]` or `[!TIP]` does not handle there not being one of those style tags at the beginning of the quote and the example code would crash the rendered. This change no longer checks `style.Ignore` if the style tag is not in our dictionary.  
- Bugfix
Markdown quotes that don't start with a style tag cash the sample app.
Markdown quotes that don't start with a style tag don't get checked if there non-existing style's Ignore prop is …

Check style.Ignore if style is not null.

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListDetailsView/ListDetailsView.bind
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.cs

Remove reliance upon hard-coded string
* Refactoring (no functional changes, no api changes)
Retrieves WinUI NavigationView by hard-coded string
FindAscendant for NavigationView with WinUI namespace

Update string reliance on WinUI NavigationView

---

build/build.cake

This adds a parameter to the build.cake file to be able to easily build everything in debug mode.
- Feature
Can only run the build script in Release.
Builds in Release mode by default, but you can run "build.ps1 -configuration debug" to build everything in debug.

Added a parameter for configuration(Debug/Release) on the cake build script

---

build/Find-WindowsSDKVersions.ps1

This fixes a bug in the Windows SDK locator script to make it check for both x64 and x86 registry keys. The ADO build server, as well as some of our machines, are reproducing this odd behavior, and this PR addresses that bug.
- Bugfix
SDK locator script crashing depending if the registry keys that it looks for exists in x64 or x86 land.
SDK locator script checks for both x64 and x86 registry keys, making it more reliable.

Updated Windows SDK locator script to make it more resilient to x86 vs x64 environments.

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListViewExtensions/ListViewExtensionsPage.xaml
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListViewExtensions/ListViewExtensionsPage.xaml.cs
Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.SmoothScrollIntoView.cs

- Bugfix
Currently, `SmoothScrollIntoViewWithIndexAsync` is not truly asynchronous but it will return a `Task`.
SmoothScrollIntoView method should be truly asynchronous. It should wait until the animation completes
~~I have not tested this since I am encountering an issue while building the application locally. Below is the issue I am facing while building (It's **not related to this code change**)~~
~~I will try to solve this issue. In meantime, **can anyone test this PR if possible?** sorry for this inconvenience~~

Changed SmoothScrollIntoView method to be truly asynchronous

---

Microsoft.Toolkit.Mvvm.SourceGenerators/Attributes/NullabilityAttributesGenerator.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/EmbeddedResources/INotifyPropertyChanged.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.csproj
Microsoft.Toolkit.Mvvm/Attributes/NotNullAttribute.cs
Microsoft.Toolkit.Mvvm/Attributes/NotNullIfNotNullAttribute.cs
Microsoft.Toolkit.Mvvm/ComponentModel/ObservableObject.cs
Microsoft.Toolkit.Mvvm/ComponentModel/ObservableRecipient.cs
Microsoft.Toolkit.Mvvm/ComponentModel/ObservableValidator.cs

- Improvements
Some helper methods lack some nullability annotations. Specifically:
- The `SetProperty` methods directly target a backing field don't indicate that if the supplied input value is not null, then the target field will also always be not null once the method returns (as the two aren't equal).
- The `SetPropertyAndNotifyOnCompletion` methods don't indicate that the target `TaskNotifier` instance will always be not null once the method returns (as the field is always immediately initialized as soon as the method is invoked).
- Added `[NotNullIfNotNull]` to mark target fields for `SetProperty`
- Added `[NotNull]` to mark target task notifiers in `SetPropertyAndNotifyOnCompletion`.
Also had to update the source generator project to …

Improved nullability annotations in MVVM Toolkit

---

build/build.cake

- Bugfix 
Build fails if the Platform env variable is set to anything other than AnyCPU.
Forces AnyCPU builds on MSBuild calls.

Forced AnyCPU on builds.

---

Microsoft.Toolkit.Uwp.UI.Controls.Media/Microsoft.Toolkit.Uwp.UI.Controls.Media.csproj

Update winui version
`Microsoft.Toolkit.Uwp.UI.Controls.Media` uses winui 2.5
`Microsoft.Toolkit.Uwp.UI.Controls.Media` uses winui 2.6.1

Controls.Media update winui version

---

UnitTests/UnitTests.HighPerformance.Shared/Enumerables/Test_ReadOnlyRefEnumerable{T}.cs
UnitTests/UnitTests.HighPerformance.Shared/Enumerables/Test_RefEnumerable{T}.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ICommandAttribute.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_INotifyPropertyChangedAttribute.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_IRecipientGenerator.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservableObjectAttribute.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservablePropertyAttribute.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservableRecipientAttribute.cs
UnitTests/UnitTests.Shared/Mvvm/Test_Messenger.cs

- Maintenance
Some HighPerformance/Mvvm unit tests produce warnings when the projects are built.
No more warnings 🙌

Fix warnings in HighPerformance/Mvvm unit tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/win32_controls.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
Contributing.md
License.md
Microsoft.Toolkit.Uwp.SampleApp/ReadMe.md
Microsoft.Toolkit.Win32/ReadMe.md
ReadMe.md

1. Using `MarkdownLint` or similar tools, fix and format the markdown files
* Fix headings
* Fix anchors in headings
* Fix dead links (Fixes #4139)
* Add Code **`** quotes to source texts
* Fix Code snippets with correct file-type tags
* Fix new lines around headings and paragraphs
2. Replace GitHub emoji identifiers (aka **:emoji_id:**) with actual emoji symbols
Markdown files have a lot of issues being reported from tools like `MarkdownLint`. They also use GitHub emoji identifiers.
Fixed and Formatted markdown files with `MarkdownLint`. Replaced GitHub emoji identifiers with actual emojis.
- If you're editing this patch …

Fixup, Format and Update Markdown files

---

Microsoft.Toolkit.Mvvm.SourceGenerators/Attributes/NullabilityAttributesGenerator.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_INotifyPropertyChangedAttribute.cs
UnitTests/UnitTests.NetCore/UnitTests.NetCore.csproj
UnitTests/UnitTests.NetStandard/SampleModelWithINPCAndObservableProperties.cs
UnitTests/UnitTests.NetStandard/UnitTests.NetStandard.csproj
Windows Community Toolkit (NET).slnf
Windows Community Toolkit.sln

- Bugfix
Build error due to unusable attributes when using `[INotifyPropertyChanged]` on .NET Standard 2.0.
No build errors, attributes are generated as expected when needed.

Fixed nullability attributes generation on .NET Standard targets

---

Microsoft.Toolkit.Uwp.DeveloperTools/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.Core/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.Input/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.Layout/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.Markdown/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.Media/VisualStudioToolsManifest.xml
Microsoft.Toolkit.Uwp.UI.Controls.Primitives/VisualStudioToolsManifest.xml

Adds almost all the Controls in the toolkit packages to the Visual Studio Toolbox.
- Bugfix
- Feature
Many controls don't appear in the VS IDE Toolbox.
The Controls now appear in the VS IDE Toolbox.
- If you're editing this patch tree, please `rebase` on latest `HEAD` and then commit, without updating from the latest `HEAD`.
- When merging, please update the commit title to PR title instead of the default `Merge pull request #xxxx from repo/branch`, and commit message to either PR message or messages of individual commits. The `auto-merge` bot does this by default.

Add missing controls to Visual Studio Toolbox

---

Microsoft.Toolkit.Uwp.UI.Controls.Primitives/ConstrainedBox/ConstrainedBox.Properties.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Alignment.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Coerce.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Combined.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Constrict.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Infinity.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

Adds Value Coercion to the properties to ensure they're within a valid range.
Also fixes the issue with MultipleX/Y not triggering layout updates.
Debating whether to add more tests to this PR or not still... 🤔
- Bugfix
Can specify any values for properties.
Will reset/bound properties to expected values if out-of-range.

Add Value Coercion to ConstrainedBox

---

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/ApplicationDataStorageHelper.CacheFolder.cs
Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/ApplicationDataStorageHelper.cs
Microsoft.Toolkit/Helpers/ObjectStorage/IFileStorageHelper.cs
UnitTests/UnitTests.UWP/Helpers/Test_ApplicationDataStorageHelper.cs

- Bugfix
- Feature
There is currently no methods for renaming items via the `IFileStorageHelper` interface.
Also, the `ApplicationDataStorageHelper` needs more tests to validate that the file storage functionality is working as expected.
To support renaming items, I've added a new method `IFileStorageHelper.TryRenameItemAsync`. 
In addition, I've also updated the `IFileStorageHelper.DeleteItemAsync` method to `TryDeleteItemAsync` to match the convention. It seems reasonable to expect that the file intended for deletion does not already exist, so the consumer should be able to handle this gracefully, without exceptions.
Lastly, while adding tests for `ApplicationDataStorageHelper` I discovered that it doesn't handle items in sub-folders very …

Enable item renaming and add tests for ApplicationDataStorageHelper

---

UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Infinity.cs

- Bugfix
Test_ConstrainedBox_AllInfinite_AspectBothFallback  fails on 150% DPI
Test_ConstrainedBox_AllInfinite_AspectBothFallback works on any DPI.

Fix for ConstrainedBox test in high DPI

---

Microsoft.Toolkit.Uwp.UI.Controls.Layout.Design/Controls/ListDetailsView.Metadata.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout.Design/Controls/ListDetailsView.Typedata.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/BackButtonBehavior.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.BackButton.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.Events.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.cs
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.xaml
Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsViewState.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ListDetailsView.cs

- Feature
- Refactoring
The [ListDetailsView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/masterdetailsview) does not take advantage of multiple screens and is not spanning aware.
The new and refactored [ListDetailsView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/masterdetailsview) control is aware of multiple screens.
We archive this by replacing the current `grid`-based layout with the new [Two-pane view](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/two-pane-view) based layout.
- I added additional properties: `DetailsPaneBackground`, `DetailsContentTemplateSelector`, `ListPaneEmptyContent`, `ListPaneEmptyContentTemplate` and `ListPaneItemTemplateSelector`.
Please …

ListDetailsView now uses the Two-Pane View

---

UnitTests/UnitTests.UWP/UI/Collection/Test_IncrementalLoadingCollection.cs

Tests different values for `itemsPerPage` in the IncrementalLoadingCollection ctor.

Test IncrementalLoadingCollection itemsPerPage ctor param 

---

Microsoft.Toolkit.Uwp.UI.Controls.Input.Design/Controls/RichSuggestBox.Metadata.cs
Microsoft.Toolkit.Uwp.UI.Controls.Input.Design/Controls/RichSuggestBox.Typedata.cs
Microsoft.Toolkit.Uwp.UI.Controls.Input.Design/Microsoft.Toolkit.Uwp.UI.Controls.Input.DesignTools.csproj

Adding design metadata for `RichSuggestBox`.
- Other... Improve Visual Studio design tool integration
No metadata for `RichSuggestBox` control.
Design metadata is added for `RichSuggestBox`

Add design metadata for RichSuggestBox

---

Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridComboBoxColumn.cs

This implementation fixes the need to click a ComboBox in a DataGridComboBoxColumn 3 times before the DropDown opens.
- Bugfix 
The current behavior is that in order to expand a ComboBox DropDown, the cell must first be clicked once to be highlighted, then the ComboBox must be clicked twice more before the DropDown expands.
For more information, see: [#3161](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/3161)
The new behavior is that after the ComboBox is clicked once to be highlighted, the next click expands the DropDown.
Supersedes #4209

Improving ComboBoxColumn behavior to prevent triple click behavior

---

Microsoft.Toolkit.Uwp.UI.Controls.Input/TokenizingTextBox/TokenizingTextBox.xaml

- Bugfix
Header rendered inside the TokenizingTextBox
Header now renders above the TokenizingTextBox input area.
Also took the liberty to add the properties for the header presenter that are also present for the TextBox header presenter.

Fix TokenizingTextBox header to behave like normal text control headers

---

UITests/UITests.App/UITests.App.csproj

It seems we forgot to update the winui ref in the `UITest.App` project ( The added winui ref was prob in a PR when the winui update PR merged.) The mixed versions causes warning is visual studio and could mess with out tests env. 
Remove the explicit winui ref in `UITest.App`.
- Bugfix

UITests: Remove ref to incorrect version of winui

---

UnitTests/UnitTests.SourceGenerators/Test_SourceGeneratorsDiagnostics.cs
UnitTests/UnitTests.SourceGenerators/UnitTests.SourceGenerators.csproj
build/build.cake

The unit tests for the MVVM Toolkit source generator are broken and also don't run in the CI.
Fixed the unit tests and enabled them in the CI.

Fix and enable MVVM Toolkit source generator unit tests

---

Microsoft.Toolkit.Mvvm.SourceGenerators/AnalyzerReleases.Unshipped.md
Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/ObservablePropertyGenerator.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/ObservableValidatorValidateAllPropertiesGenerator.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/TransitiveMembersGenerator.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/Diagnostics/DiagnosticDescriptors.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/Input/ICommandGenerator.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/Messaging/IMessengerRegisterAllGenerator.cs
UnitTests/UnitTests.SourceGenerators/Test_SourceGeneratorsDiagnostics.cs

- Improved UX
Hard to diagnose errors when using source generators in the MVVM Toolkit with an older C# version.
A new diagnostic message telling users to upgrade their C# language version when using the source generator features.

Add C# language version diagnostic

---

Microsoft.Toolkit.Uwp.UI/Shadows/AttachedDropShadow.cs
Microsoft.Toolkit.Uwp.UI/Shadows/AttachedShadowElementContext.cs

We weren't updating the shadow visual if the parent element's visibility changed or layout was effected by other elements.
- Bugfix
In some scenarios the shadow wouldn't be updated by the changes to the parent element.
Shadow is now updated in more scenarios (though maybe not all). We should properly handle `Visibility`, `Scale`, and some changes due to Layout updates.
Note: I tried with `Canvas` from the implicit animation sample and it seems Canvas moving an object doesn't call `LayoutUpdated` on that element... wonder if that's a framework bug ([this was the closest open one I could find](https://github.com/microsoft/microsoft-ui-xaml/issues/2900))? Otherwise, not sure how we detect that in the element...
@zateutsch you …

Fix #4214 - Update AttachedDropShadow visual on layout/visibility

---

Microsoft.Toolkit.Uwp.UI.Animations/Expressions/CompositionExtensions.cs
Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionNodes/ExpressionNode.cs

- Bugfix 
This is a fix that prevents name collisions when nodes/subtrees are reused to build more than one expression string. It is not completely clear to me if reusing nodes/subtrees to build multiple expression strings is a explicitly supported scenario, but the docs don't warn against it and it is imo desirable to:
- Avoid having to rebuild the same tree of nodes over and over when animating collections of elements
- Avoid having to rebuild the same tree of nodes for animating properties that share an "animation subtree"
- Stay in the realm of ReferenceNodes in our animation classes, rather than pass them the whole InteractionTracker/PropertySet (giving them "write access") just so they can call GetReference() as many times as they need.
As …

Clear ReferenceNode ParamNames before serializing each expression string to avoid collisions

---

Microsoft.Toolkit.Uwp.UI/Helpers/ThemeListener.cs
UnitTests/UnitTests.XamlIslands.UWPApp/XamlIslandsTest_ThemeListener_Threading.cs

Applying changes discussed in https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/3253#issuecomment-740261646.
- Bugfix
Changes to the high contrast theme are propagated on the original synchronization context.
The event handler now dispatches on the current dispatcher queue.

Added DispatcherQueue dispatching for high contrast theme change

---

Microsoft.Toolkit.Mvvm/ComponentModel/Attributes/AlsoNotifyChangeForAttribute.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservablePropertyAttribute.cs

- Bugfix
The `[AlsoNotifyChangeFor]` attribute can't be used multiple types, and a constructor is missing `params`.
Fixed the issues mentioned above.

Fixed [AlsoNotifyChangeFor] attribute definition

---

Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/ObservablePropertyGenerator.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ICommandAttribute.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservablePropertyAttribute.cs

- Bugfix
Compilation fails If the Microsoft MVVM Toolkit source generator attribute `[ObservableProperty]` is in a `#region` block.
The generated code is now correct when regions are used.

Fixed generated properties within regions

---

Microsoft.Toolkit.Uwp.UI.Controls.Primitives/ConstrainedBox/AspectRatio.cs
Microsoft.Toolkit.Uwp.UI.Controls.Primitives/ConstrainedBox/ConstrainedBox.Properties.cs
Microsoft.Toolkit.Uwp.UI.Controls.Primitives/ConstrainedBox/ConstrainedBox.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.Alignment.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ConstrainedBox.AspectRatio.cs

- Bugfix
The `AspectRatio.ConvertToAspectRatio(string)` method used for parsing is using `Convert.ToDouble`, which by default uses the current culture for parsing. This causes a crash when trying to parse a number using `'.'` as decimal separator on cultures that instead use `','` as decimal separator (eg. French, Italian). Furthermore, the parsing behavior is not consistent with eg. the various `Vector2/3/4` and `Quaternion` parsing APIs in the `StringExtensions` class in `Microsoft.Toolkit.Uwp.UI`.
Updated the parsing logic in `AspectRatio.ConvertToAspectRatio(string)` to be consistent with other parsing APIs.
The parsing is now done using `CultureInfo.InvariantCulture`, which fixes the crash reported in the linked issue.
Please check if your …

Fixed culture sensitivity when parsing AspectRatio components

---

Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/ObservablePropertyGenerator.cs
Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/ObservableValidatorValidateAllPropertiesGenerator.cs
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservablePropertyAttribute.cs

- Bugfix
> "If you annotate a field with `ObservableProperty` along with validation attributes, the generated source code for the `ValidateAllProperties` method doesn't include all the properties."
The generated code for `ValidateAllProperties` is now correct.

Fixed ValidateAllProperties generation for generated properties

---

UITests/UITests.Tests.Shared/Controls/GridSplitterTest.cs
UITests/UITests.Tests.Shared/Controls/RangeSelectorTest.cs
UITests/UITests.Tests.Shared/Controls/RichSuggestBoxTest.cs
UITests/UITests.Tests.Shared/UITestBase.cs
UnitTests/UnitTests.HighPerformance.UWP/UnitTests.HighPerformance.UWP.csproj
UnitTests/UnitTests.NetCore/Mvvm/Test_ObservablePropertyAttribute.cs
UnitTests/UnitTests.Notifications.UWP/UnitTestApp.xaml.cs
UnitTests/UnitTests.Shared/.editorconfig

Fix most warnings from the projects! Only warnings left are MVVM from source generators.
- Refactoring (no functional changes)
- Build/CI changes
Build produces so many warnings. It is a source of developer's frustration and shame! 😢
Build now produces less impactful or no warnings at all. Happy CI, Happy Dev! 😎
Please check if your PR fulfils the following requirements:
- If you're editing this patch tree, please `rebase` on latest `HEAD` and then commit, without updating from the latest `HEAD`.
- When merging, please update the commit title to PR title instead of the default `Merge pull request #xxxx from repo/branch`, and commit message to either PR message or messages of individual commits. The `auto-merge` bot does this by default.

Fix most build warnings from the projects

---

Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.cs
UnitTests/UnitTests.UWP/UI/Controls/Test_ListDetailsView_UI.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

Makes sure that the details of the list details view is get un-selected when the SelectedIndex is updated directly.
> Note: This does not completely fix #3546, which would need to unfocus the details when the user clicks another item in the list. See #4222 
- Bugfix

ListDetailsView unfocus content on SelectedIndex changed.

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationXaml.bind
Microsoft.Toolkit.Uwp.UI.Controls.Core/InAppNotification/Styles/MSEdgeNotificationStyle.xaml

Bugfix
The 'X' inside the Dismiss button, becomes off-center and generally unreadable when user sets Windows text display to 225%
The 'X' inside the Dismiss button is legible at Windows text display setting of 225%

Upgraded Dismiss button to be legible at 225% text display setting

---

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
SmokeTests/SmokeTest.csproj
UITests/UITests.Tests.TAEF/UITests.App.dependencies.Debug.txt
UITests/UITests.Tests.TAEF/UITests.App.dependencies.Release.txt
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
build/Windows.Toolkit.UWP.Controls.targets

WinUI 2.7 just shipped yesterday with mostly bug fixes, so integrating it here before we ship.

Update to WinUI 2.7

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Shadows/AttachedShadowCompositionXaml.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json

Minor update to the shadow example to show a bit of the differences in the shadow types and update to where the docs should land.

Update AttachedShadow example and future doc links

---

Microsoft.Toolkit.Uwp.UI.Animations/Xaml/Abstract/ShadowAnimation{TValue,TKeyFrame}.cs

- Bugfix
Trying to animate shadows on unloaded events causes a crash.
Animations on shadows that are no longer available are just skipped.

Fixed crashes for shadow animations on unloaded items

---

Microsoft.Toolkit.Uwp/Extensions/DispatcherQueueTimerExtensions.cs

The audience is misled into thinking the proper way to initialize a `DispatcherQueueTimer `is by using `new `.  The PR corrects the code example to show the proper way to initialize a `DispatcherQueueTimer`.  XML doc to be auto-generated with this updated code.
Bugfix
The audience is misled into thinking the proper way to initialize a `DispatcherQueueTimer `is by using `new `. 
The PR corrects the code example to show the proper way to initialize a `DispatcherQueueTimer`.

Modify DispatcherQueueTimer source for XML docs output

---

Microsoft.Toolkit.Uwp.UI.Controls.Input/RadialGauge/RadialGauge.cs

Due to a typo or a merge conflict, the ScaleTickBrush of the RadialGauge control currently gets the color of the ScaleBrush instead of its own.
- Bugfix
The ScaleTickBrush property accidently gets its value from the ScaleBrush value in XAML or Resource Dictionary.
The ScaleTickBrush gets its value from the corresponding XAML setting or Resource Dictionary.
- [ x] Tested code with current [supported SDKs](../#supported)
- [ x] Contains **NO** breaking changes

Fix Radial Gauge ScaleTickBrush color assignment

---

Microsoft.Toolkit.Mvvm/Messaging/Internals/System/Gen2GcCallback.cs
Microsoft.Toolkit.Mvvm/Messaging/WeakReferenceMessenger.cs

Port of https://github.com/CommunityToolkit/dotnet/commit/e2b336184f51fcd755f3151222ff948176ee954c.
Didn't really see any other commits already in https://github.com/CommunityToolkit/dotnet that would meet the hotfix bar for 7.1.2, so I think it's just this one hotfix we need on top of the other stuff that's already here on `main`, eg. the animation fix.
- https://github.com/CommunityToolkit/dotnet/issues/14
- https://github.com/CommunityToolkit/dotnet/issues/12
- Bugfix
The app domain cannot be loaded on .NET Framework when using `WeakReferenceMessenger`.
Auto trimming is disabled when running on .NET Framework, which solves the issue.

Fix app domain unloading issue on .NET Framework

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Animations/Behaviors/BlurBehaviorXaml.bind
Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Animations/Behaviors/SaturationBehaviorXaml.bind

Bugfix
Excessive XAML namespace declarations come along for the ride when user selects either `BlurBehavior` or `SaturationBehavior` sample pages are selected & loaded.
Tidied up XAML namespace declarations for both `BlurBehavior` and `SaturationBehavior`.

Remove excessive namespace declarations

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/MetadataControl/MetadataControl.xaml

Feature
We can not change the `AutomationProperties.AccessibilityView` of the inner `TextBlock` of the `MetadataControl`, that causes some accessibility issue.
We can change it by setting `AutomationProperties.AccessibilityView` of the `MetadataControl`

Support AccessibilityView in MetadataControl

---

Microsoft.Toolkit.Uwp.UI.Controls.Input/RadialGauge/RadialGauge.cs

This change adds support for Opacity in the brushes for the Radial Gauge elements that are drawn with the Composition API: Ticks, ScaleTicks, and Needle.
To support transparency, apply the Opacity of the resource Brush to the Composition Visuals.
- Feature
Only the XAML elements (Scale, Trail, and the texts) currently support Opacity in their Brushes. Composition API elements (Ticks, ScaleTicks, and Needle) do not support transparency.
All UI elements now react in a similar way to a resource Brush with Opacity.
- [*] Tested code with current UWP and WinUI 3 versions.
- [*] Contains **NO** breaking changes

Improved opacity support in Radial Gauge

---

Microsoft.Toolkit.Uwp.UI.Media/Extensions/UIElementExtensions.cs
Microsoft.Toolkit.Uwp.UI.Media/Extensions/Windows.UI.Composition/CompositionObjectExtensions.cs
Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.cs

- Optimization
All `Visual` objects created through our pipeline system are kept in sync with target objects through an expression animation.
We're now just using [Visual.RelativeSizeAdjustment](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.visual.relativesizeadjustment) to achieve the same without the animation overhead.
I did test this in the sample app, but still adding the testing required tag as I'd like more validation on this.
I'm wondering whether there's a way to also optimize this bit here by removing the animation:
https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/4a09bf04531fb24e20dd8f42b18c0460f22d3ef3/Microsoft.Toolkit.Uwp.UI/Extensions/VisualExtensions.cs#L502-L511
Haven't yet figured out a …

Optimize Visual size sync through RelativeSizeAdjustment over expression animations

---

Microsoft.Toolkit.Uwp.SampleApp/Pages/About.xaml

Bugfix
Fix for [issue 4432](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4432) where release notes text was overlapping with dates on About page of Sample App.
Added text trimming to TextBlock where release note name was bound. Will display ellipses if text exceeds width limit of 150.

Resolve issue #4432 with release note text overlap

---

ReadMe.md

- Use an emoji for Contributors' title
Rest of the titles have emojis, why not this? So, I used Champion Cup (`🏆`) emoji.
- Don't use inline HTML in markdown
The format to represent image with a link is supported by most markdown parsers: `[![alt-text](image-link)](info-link)`.
- ReadMe content changes (_refactor and fixes_)
My markdown linter reports issues with in-line HTML.
Made sure that we convert the in-line HTML to markdown format.
**Squash merge** if possible.

Fix linter issues with ReadMe

---

Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPickerButton.cs
UITests/UITests.Tests.Shared/Controls/ColorPickerButtonTest.cs
UITests/UITests.Tests.Shared/Controls/ColorPickerButtonTestPage.xaml
UITests/UITests.Tests.Shared/Controls/ColorPickerButtonTestPage.xaml.cs

Update internal ColorPicker Color when ColorPickerButton SelectedColor changes
Bugfix 
When ColorPickerButton.SelectedColor Property changes, the changed color is not the one in the colorpicker when the user clicks on the ColorPickerButton
SelectedColor gets propagated to the internal colorpicker to fix this bug.
I am unfamiliar with all the testing infrastructure you have in place, so I just created little sample app for myself with the following two snippets. Should I add those somewhere? 
```xaml
<StackPanel>
<controls:ColorPickerButton SelectedColor="{x:Bind TheColor, Mode=TwoWay}" />
<Button Click="Button_Click">Set color to red</Button>
</StackPanel>
```
```cs
private Color …
```

Fix ColorPickerButton SelectedColor bug 

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/InAppNotification/InAppNotification.cs

Fixes #4423 
Bugfix
When the Closing event is cancelled, subsequent calls to Dismiss() no longer work as expected.
Fixed an issue where InAppNotification couldn't be dismissed programmatically after cancelling the closing event.

Fixed InAppNotification not dismissing programmatically after cancelling closing event

---

Microsoft.Toolkit.Uwp.UI.Behaviors/Animations/StopAnimationAction.cs

Fixed bug that was making AnimationProperty or TargetObjectProperty unavailable to assign via xaml, because DependencyProperty ownerType was wrong.
- Bugfix
- Currently, it throws an Exception.
- Exception is no longer thrown.

Fixed DependencyProperty assign exception.

---

Microsoft.Toolkit.Uwp.SampleApp/Data/DataGridDataSource.cs

Fixes #4475
Use `CultureInfo.InvariantCulture.DateTimeFormat` as `IFormatProvider` for `DateTimeOffset.Parse` when loading data source for the DataGrid sample to prevent crashing caused by regional settings.
Bugfix
The sample crashes immediately when navigated to the DataGrid sample.
Not crash.

Fix DataGrid crash in Sample App

---

UnitTests/UnitTests.Notifications.NetCore/UnitTests.Notifications.NetCore.csproj

CI fails due to no .NET Core 2.1 SDK installed.
CI builds and runs correctly.

Bump Notifications test project to .NET Core 3.1

---

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Shadows/AttachedShadowWin2DXaml.bind
Microsoft.Toolkit.Uwp.UI.Media/Enums/InnerContentClipMode.cs
Microsoft.Toolkit.Uwp.UI.Media/Shadows/AttachedCardShadow.cs
Microsoft.Toolkit.Uwp.UI/Shadows/AttachedShadowElementContext.cs

This PR adds the option to clip inner content from shadows using `CompositionMaskBrush`, which may improve performance over the default `CompositionGeometricClip` method.
- Feature
`AttachedCardShadow` only clips its inner content using `CompositionGeometricClip`, which can have poor framerates when several shadows are on screen at a time.
Added the option to clip inner shadow content using `CompositionMaskBrush`, which improves performance over `CompositionGeometricClip` when several shadows are on screen at a time, but looks slightly worse as the boundary of the inner clipped are lacks anti aliasing.
An `InnerContentClipMode` enum was added, as well as an `AttachedCardShadow.InnerContentClipMode` property, making it …

Clip inner content from AttachedCardShadow using CompositionMaskBrush

---

UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs

- Adding unit tests
There aren't any unit tests for toast scenario XML properties (like alarm, reminder, etc)
Added a unit test to test all toast scenarios. No functional change, just adding a test.
- x] Tests for the changes have been added (for bug fixes / features) (if applicable)

Add tests for toast scenario

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/RadialProgressBar/RadialProgressBar.xaml
Microsoft.Toolkit.Uwp.UI.Controls.Input/RadialGauge/RadialGauge.xaml

Adds a FlowDirection override to the RadialGauge default style. This is because RTL cultures still read gauges clockwise.
The flow direction can still be explicitly overridden if desired for whatever reason.
Bugfix
RadialProgressBar and RadialGauge directions unnecessarily inversed in RTL context.
RadialProgressBar and RadialGauge directions no longer inversed unless FlowDirection is explicitly set.

Added FlowDirection override to RadialProgressBar and RadialGauge default style

---

Microsoft.Toolkit.Uwp.UI.Controls.Layout/Carousel/Carousel.cs

Fixes the scroller direction of carousel items in RTL Flow Direction
Bugfix 
In RTL flow direction right key/gamepad presses scroll the carousel in the inverted direction
Flow Direction is checked before position increment or decrement on left/right key/gamepad presses.

Fixed left/right key input for Carousel in RTL Flow Direction

---

Microsoft.Toolkit.Uwp.UI.Behaviors/Headers/StickyHeaderBehavior.cs

Fixes the summary and owner type on `StickyHeaderBehavior.HeaderElementProperty`.
- Bugfix 

Fixed StickyHeaderBehavior HeaderElementProperty owner type / summary

---

Microsoft.Toolkit.Uwp.UI/Shadows/AttachedDropShadow.cs

Fix AttachedDropShadow size changes abnormally.
What kind of change does this PR introduce?  
Bugfix
The mask does not update even if the size of the element that owns the AttachedDropShadow changes.
If the size of the element that owns the AttachedDropShadow changes, the mask will be updated.

Fix AttachedDropShadow size changes abnormally

---

Microsoft.Toolkit.Uwp.UI/Shadows/AttachedShadowBase.cs

Adding a null reference check to AttachedDropShadow crash issue
Fixes the sudden crash of sample app when we add Xaml code 
Bugfix 
Sample app changes 
Sample app Crash when we add Xaml Code
Fixes the Crash
Based off latest main branch of toolkit
Tested code with current [supported SDKs](../#supported)
Sample in sample app has been added / updated (for bug fixes / features)

AttachedDropShadowCrashFix

---

Microsoft.Toolkit.Uwp.UI.Controls.Core/RotatorTile/RotatorTile.cs
Microsoft.Toolkit.Uwp.UI.Controls.Input/RadialGauge/RadialGauge.cs
Microsoft.Toolkit.Uwp.UI.Controls.Input/TokenizingTextBox/InterspersedObservableCollection.cs
Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs
Microsoft.Toolkit.Uwp.UI/Triggers/FullScreenModeStateTrigger.cs
Microsoft.Toolkit.Uwp.UI/Triggers/IsNullOrEmptyStateTrigger.cs
Microsoft.Toolkit.Uwp.UI/Triggers/NetworkConnectionStateTrigger.cs
Microsoft.Toolkit.Uwp.UI/Triggers/UserInteractionModeStateTrigger.cs

See issue for details, minor clean-ups/optimizations. And see https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/issues/262#issuecomment-912522699 for WeakEventListener pattern.
- Bugfix
- Keyboard handlers registered each time the control is loaded
- Lambda handlers for Keyboard registration not static
- Didn't unregister events in RadialGauge before registering
- WeakEventListener pattern's not followed
- Keyboard handlers only registered once for the control
- Keyboard handler Lambda's static
- Events unregistered before registered
- use new C# static lambda to help properly implement WeakEventListener patterns

RadialGauge and WeakEventListener optimizations

---

Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPicker.xaml
Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorToSelectedValueConverter.cs

Fixes #4721
- Bugfix
The current `SelectedValue` binding throws a Binding Failure error because it tries to return a null `Color` property (due to `BindingMode=TwoWay`) that has a value type
Added a helper converter that will ignore null values in `ConvertBack`, replacing them with `DependencyProperty.UnsetValue`
- [x Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)

fix: Fix color picker button binding failure issue

---

Microsoft.Toolkit.Uwp.UI/Converters/TaskResultConverter.cs
UnitTests/UnitTests.UWP/Converters/Test_TaskResultConverter.cs

Adds better testing around real-world `x:Bind` and converter scenarios for `TaskResultConverter`, also related to the nature of how this interacts with the MVVM Toolkit behavior (which would mimic most real-world app behavior as well).
Fixes the converter to better handle a wider variety of scenarios.
- Bugfix
The TaskResultConverter will return `UnsetValue` when the expected `Task` has not been initialized yet (and is `null`).
The documentation specified the `default` value would be returned, but this was not true for value types.
`TaskResultConverter` now will return the default value (null or otherwise for value types) whether a task is set or not.
It'll also passthru non-task values as a no-op.
Please check if …

TaskResultConverter returns default value when task not set
