Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs
=> ImageEx loadedstate

build/default.ps1
=> Allows AppVeyor to use generated NuGet packages in internal feed

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs
Alternative proposal for fixing #220.
=> More flexible ImageEx source (Uri) parsing.

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewPage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs, Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.xaml
SelectionMode, SelectionChanged, SelectedItem, SelectedItems and
IsItemClickEnabled and SelectedIndex properties are now working as intended for
AdaptiveGridView and connected to the base GridView.
Fixes #159
=> SelectionMode support implemented for AdaptiveGridView.

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
=> Fixes #237

build/default.ps1
Missed a GitVersion call on previous commit
=> Ensures GitVersion does not attempt to make a "git fetch"

Microsoft.Toolkit.Uwp.SampleApp/Controls/PropertyControl.xaml.cs
=> Really nasty bug due to DataContextChanged called many times with same value

Microsoft.Toolkit.Uwp.SampleApp/Data/PhotosDataSource.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/HamburgerMenu/HamburgerMenuPage.xaml.cs
=> Fixes #238

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugeCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugePage.xaml, Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs, Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.xaml
=> Added StepSize and IsInteractive to RadialGauge.

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Offset.cs
Sometimes it's the little things that matter :wink: 
Fixes #206.
=> Add null-conditional check for Offset.StartAnimation()

Microsoft.Toolkit.Uwp.SampleApp/Controls/PropertyControl.xaml, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml
=> ScrollViewer support for property grid.

Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
Introduces more flexibility for upcoming work / features.
Have maintained existing RequestAsync method signature to prevent breaking changes and wrapped new implementation.
=> Made Facebook service RequestAsync generic

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ImageEx/ImageExPage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.xaml
=> Fix crashes when using ImageEx with VisualStates

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs, Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs, Microsoft.Toolkit.Uwp.UI.Controls/RotatorTile/RotatorTile.cs
=> Remove sealed keyword from controls

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SlidableListItem/SlidableListItemCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SlidableListItem/SlidableListItemPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SlidableListItem/SlidableListItemPage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs
Fixes #327 
I've also updated the sample app to use `CommandParameter` for the delete action, but I had to remove the event so just let me know if you want the sample app to be reverted and just keep the `SlidableListItem` changes.
=> Added CommandParameter support to SlidableListItem

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
=> Build action for ToastCodeJavascript.bind is fixed.

readme.md
Show dev and master branch AppVeyor build badges
=> Show dev and master branch AppVeyor build badges

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml
It did not reopened after a click outside of the menu to close it.
=> [HamburgerMenu] Changed binding to fix an re-open issue in Overlay-mode

Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
Added a function, GetPhotoByPhotoIdAsync(),which retrieves a single facebook photo (returns a FacebookPhoto object).
=> Added a function to retrieve a single facebook photo

Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBaseExtensions.cs, Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
* Fixed namespace for HyperlinkExtensions
* Fixed Depedency Property, public method and private method order in HyperlinkExtensions
* Added ListViewBaseExtensions
Documentation pushed as well.
=> Extension classes

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Twitter Service/TwitterPage.xaml.cs
Fix for https://github.com/Microsoft/UWPCommunityToolkit/issues/394
=> logout user from sample app if invalid or expired token

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
=> BladeControl documentation update

Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.cs
=> fix for itemclick firing when swiping item

Microsoft.Toolkit.Uwp.UI.Controls/BladeControl/BladeControl.xaml
=> disable vertical scrolling in bladecontrol

Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs
OMG, I switched left and right...
=> Radial Gauge: fixed typo in XML documentation.

docs/Nuget-Packages.md, docs/animations/Blur.md, docs/animations/Fade.md, docs/animations/FadeHeader.md, docs/animations/Offset.md, docs/animations/Rotate.md, docs/animations/Scale.md, docs/controls/HamburgerMenu.md, docs/controls/HeaderedTextBlock.md
=> Fixes typos

appveyor.yml
Add initial AppVeyor.yml based on current config
=> Appveyor.yml

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs
ensure single threaded access to SetSource using semaphore
#448
=> Image Source related

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GridSplitter/GridSplitter.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GridSplitter/GridSplitterPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
Adding HorizontalAlignment to splitter sampe page and adding Actual Width in Shell #436
=> Adding HorizontalAlignment to splitter sampe page and adding Actual Width in Shell

docs/helpers/ImageCache.md
Update Image cache documentation to reflect current design.
addressing issue #463
=> ImageCache documentation

Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.cs
Fixing GridSplitter Sibling Row issue #474
=> Fixing GridSplitter Sibling Row issue

appveyor.yml, build/SignClientSettings.json, build/default.ps1, contributing.md, readme.md
New MyGet feed:
https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json
https://dotnet.myget.org/gallery/uwpcommunitytoolkit
=> Adds support for MyGet feed and Authenticode signing during build

Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.cs, Microsoft.Toolkit.Uwp.UI.Controls/HeaderedTextBlock/HeaderedTextBlock.xaml
Addressing #408
Replace TextBlock used for Header with ContentPresenter
Expose HeaderTemplate instead of HeaderStyle
=> Expose HeaderTemplate in HeaderedTextBlock

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs
=> ImageEx: Remove _isImageLoading and revert to using SemaphoreSlim

Microsoft.Toolkit.Uwp.SampleApp/Models/Samples.cs
Make sure the samples are always sorted so they are easy to find.
Fixes #512
=> Sort the samples

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
#524 Check if key exists in BaseObjectStorageHelper.Save method to add/set value in settings.
=> Check if key exist in Save method.

Microsoft.Toolkit.Uwp.UI/Extensions/WebViewExtensions.cs, Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj, docs/helpers/WebViewExtensions.md
Add attached property to enable binding Html content
=> WebViewExtensions

Microsoft.Toolkit.Uwp.UI/Extensions/WebViewExtensions.cs
Ensure that input values are check and not null before webview is called
=> WebViewExtensions null check

Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs
=> Unseal DropShadowPanel

Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.Properties.cs
=> Unseal partial class for properties

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Options.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml
=> Fix a bug with selectedItem when the HamburgerMenu was not yet templated

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Cached file was not being read
Count zero length files as out of date.
=> ImageCache fix

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GridSplitter/GridSplitterPage.xaml
This issue was due to grid splitter parent grid has padding not margin.
fixing issue #549
=> Grid splitter star fixed size issue

docs/animations/Blur.md, docs/animations/Fade.md, docs/animations/Offset.md, docs/animations/Rotate.md, docs/animations/Scale.md
=> Updating Animation Documentation

docs/helpers/BackgroundTaskHelper.md
=> Add back in documentation for background task helper

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewPage.xaml, Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
Hi guys!
I noticed crash with OneRowModeEnabled in AdaptiveGridView in my project.
So I found and fixed this issue
Please look
=> fix ununhandled error with one row mode in AdaptiveGridView

Microsoft.Toolkit.Uwp.SampleApp/Package.appxmanifest, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MasterDetailsView/MasterDetailsViewPage.xaml
Better alignment for detail view
=> New version number for sample App

Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Blur.cs
=> Blur trapping fix

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PullToRefreshListView/PullToRefreshListViewPage.xaml
Added AutomationProperties.Name in the DataTemplate item in the UWP sample project.
=> Accessibility PullToRefreshListView control

Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Blur.cs
@deltakosh @shenchauhan please approve and merge before merging to master
=> fixed logic error in Blur animation

Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeView.Events.cs
The BladeOpened and BladeClosed events should not be static.
=> Events should not be static

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs, Microsoft.Toolkit.Uwp.UI/Cache/InMemoryStorage.cs
Addressing #632 
A couple of things. Instead of doing a directly based GetItemAsync or iterating through files comparing filenames, I have created a dictionary and doing a dictionary lookup.
=> Add RemoveAsync to CacheBase

Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs
Code simplification
IncrementalLoadingCollection instantiate source using Activator.CreateInstance
Addressing #616
=> IncrementalLoadingCollection instantiate source using Activator.CreateInstance

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs, Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/IObjectStorageHelper.cs, docs/helpers/ObjectStorage.md
Add support for ApplicationDataCompositeValue.
=> Issue #570

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.xaml
=> Adds support for DataTemplateSelectors to MasterDetailsView

Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.xaml
=> Allow for two-way binding in HamburgerMenu

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
=> Fix horizontal alignment of the GridViewItems.

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs, Microsoft.Toolkit.Uwp.UI/Cache/FileCache.cs, Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs
Implement GetFileFromCacheAsync addressing #639
Typo correction in comments and documentation
=> Cache tweaks

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PrintHelper/PrintHelperPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PrintHelper/PrintHelperPage.xaml.cs, Microsoft.Toolkit.Uwp/Helpers/PrintHelper/PrintHelper.cs, docs/helpers/PrintHelper.md
=> Simplify PrintHelper usage when container already contains controls

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs, Microsoft.Toolkit.Uwp/Helpers/HttpHelper/HttpHelper.cs, Microsoft.Toolkit.Uwp/Helpers/StreamHelper.cs, UnitTests/Helpers/Test_StreamHelper.cs
Addressing #650 
Add support for passing CancellationToken to ImageCache.
=> CancellationToken support to ImageCache PreCacheAsync

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs, Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.xaml
Changed to a more moderate (to me) animation and allowed overriding it by changing using Style.
#679
=> MasterDetailsView: changed to storyboard animation

Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Common/ArgumentValidator.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Common/XmlWriterHelper.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Microsoft.Toolkit.Uwp.Notifications.Shared.projitems, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/Elements/Element_Toast.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/Elements/Element_ToastAction.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/Elements/Element_ToastHeader.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/Elements/IElement_ToastActivatable.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastActivationOptions.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastButton.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastCommon.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastContent.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastContextMenuItem.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.Shared/Toasts/ToastHeader.cs, Notifications/Microsoft.Toolkit.Uwp.Notifications.UWP/Microsoft.Toolkit.Uwp.Notifications.UWP.csproj, Notifications/Microsoft.Toolkit.Uwp.Notifications.WinRT/Microsoft.Toolkit.Uwp.Notifications.WinRT.csproj, UnitTests/UnitTests.Notifications.Shared/Test_Toast_Xml.cs, UnitTests/UnitTests.Notifications.UWP/UnitTests.Notifications.UWP.csproj
Added new toast notification features for Creators Update
=> New toast features for Creators Update

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs
Removed the useless composition codes in MasterDetailsView after changing the animations to Storyboard animation.
=> Removed useless composition codes.

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs
Do not try to get the SystemNavigationManager in design mode
=> Design mode fixes for MasterDetailsview

build/Microsoft.Toolkit.Uwp.Notifications.JavaScript.nuspec, build/Microsoft.Toolkit.Uwp.Notifications.nuspec, build/Microsoft.Toolkit.Uwp.Services.nuspec, build/Microsoft.Toolkit.Uwp.UI.Animations.nuspec, build/Microsoft.Toolkit.Uwp.UI.Controls.nuspec, build/Microsoft.Toolkit.Uwp.UI.nuspec, build/Microsoft.Toolkit.Uwp.nuspec
=> Correct NuGet UWP Community Toolkit Icon for NuGet

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SlidableListItem/SlidableListItemPage.xaml, Microsoft.Toolkit.Uwp.UI.Controls/SlidableListItem/SlidableListItem.xaml
Added AutomationProperties.Name in the DataTemplate item in the UWP sample project.
Added IsTabStop and TabIndex in the control xaml file.
=> Accessibility SlidableListItem control 

Microsoft.Toolkit.Uwp/Helpers/StorageFileHelper.cs, UnitTests/Helpers/Test_StorageFileHelper.cs, docs/helpers/StorageFiles.md
Linked to #692 
Ping @ThisWillDoIt
=> Add filename validation in Storage Helper

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
=> Fixes layout issue with AdaptiveGridView

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs, Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs, Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs, Microsoft.Toolkit.Uwp/Helpers/StreamHelper.cs
Use CancellationToken rather than lock
Bug fix StreamHelper where cancellation token wasn't being passed
Throw FileNotFound if stream size is 0
#728
=> ImageEx + ImageCache tweaks

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MasterDetailsView/MasterDetailsViewCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ReorderGridAnimation/ReorderGridPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json, Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/Light.cs, Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Light.cs, Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs, UnitTests/Helpers/Test_StreamHelper.cs
=> Add POCO code sample for MasterDetailsView

UnitTests/Helpers/Test_StorageFileHelper.cs
Added illegal path characters to the failing test for illegal characters.
Making test pass correctly
#781
=> Test illegal path characters are detected (issue 781)

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
=> Show/Hide the info area when navigation happens to the SamplePicker

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs, Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs
Change IsFileOutOfDate to be overrideable
ImageCache cache cleanup should be based on last access not last modified
=> Change IsFileOutOfDate to be overrideable

Microsoft.Toolkit.Uwp.SampleApp/Pages/SamplePicker.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MosaicControl/MosaicControlPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs, Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.cs, readme.md
Better UI for badges on mobile
=> Fixed warnings & better UI for badges on mobile

Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
=> Pull to refresh fixes

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
I noticed that some Github links were broken in the SampleApp so I fixed them.
I don't know if the link has to point to the file or the parent folder.
=> Fix Github link in SampleApp

docs/helpers/ListViewBaseExtensions.md, readme.md
Added documentation page for ListViewBaseExtensions
Added link to Readme
=> Documentation for ListViewBaseExtensions and link to readme.md

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs
Update summary tag of ItemClickCommand to state that the IsItemClickEnabled property **must** be true.
Fixed #840
=> Update summary tag of ItemClickCommand

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Translator Service/MicrosoftTranslatorCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Translator Service/MicrosoftTranslatorPage.xaml.cs, Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/ITranslatorService.cs, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftTranslator/TranslatorService.cs, docs/services/MicrosoftTranslator.md
made service a singleton
enabled subscription key and language to be initialized in in initializeasync overloads
added a provider property
updated samplepage
updated docs
=> ensuring translator service shares a consistent api with other services

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/OneDrive Service/OneDriveCode.bind, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveService.cs, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageItem.cs, build/Microsoft.Toolkit.Uwp.Services.nuspec, docs/services/OneDrive.md
https://github.com/Microsoft/UWPCommunityToolkit/issues/851
https://github.com/Microsoft/UWPCommunityToolkit/issues/850
https://github.com/Microsoft/UWPCommunityToolkit/issues/849
https://github.com/Microsoft/UWPCommunityToolkit/issues/848
=> OneDrive - nuspec, docs, new root folders, new datemodified property

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml
=> fix(expander): change Horizontal and Vertical alignment to TemplateBinding

Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveItemExtension.cs, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageItem.cs, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveThumbnailSet.cs
=> Add support for ThumbnailSet in OneDrive SDK

Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeView.cs
=> Fixed scrolling animation issue for Bladeview on mobile

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollHeader/ScrollHeaderCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollHeader/ScrollHeaderPage.xaml, Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs, Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs, Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj, Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj, Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs, Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeaderMode.cs, docs/controls/ScrollHeader.md
=> Move ScrollHeader properties to enum to avoid conflicts

Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageItem.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.HamburgerButton.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Options.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/MenuItems/HamburgerMenuGlyphItem.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/MenuItems/HamburgerMenuImageItem.cs, Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs
This is a PR to fix some typos in comments of
- HamburgerMenu
- OneDriveStorageItem
- ImageEx
=> Fix typos in comments

Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.xaml
=> fix(expander): add template binding to Background property

Microsoft.Toolkit.Uwp.UI.Animations/AnimationSet.cs
=> AnimationSet fix 

Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs
=> Attach behaviors according to Mode while initializing

Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
Included converters from PR #462
=> Missing converters from PR #462

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MarkdownTextBlock/InitialContent.md, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MarkdownTextBlock/MarkdownTextBlock.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MarkdownTextBlock/MarkdownTextBlockPage.xaml, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveService.cs, Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageFile.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Display/XamlRenderer.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Helpers/Common.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.xaml, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Blocks/CodeBlock.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Inlines/HyperlinkInline.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Inlines/ImageInline.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/MarkdownDocument.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/MarkdownInline.cs, Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj, Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
=> Markdown control improvements: Github code style, images, link foreground color

githubresources/content/links.md
Telerik UI for UWP was recently made available as open source. It offers 20+ UI controls for developers. These include Chart, DataForm, ListView, Grid, and more.
=> Added UI for UWP

Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.xaml
=> DropShadowPanel IsTabStop property should be False.

Microsoft.Toolkit.Uwp.UI.Controls/PullToRefreshListView/PullToRefreshListView.cs
=> fixes for 935 and 934 - PullToRefreshListView

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Display/MarkdownTable.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Blocks/TableBlock.cs
=> Fix Table support for markdown

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.cs
revert to source uri comparision as wrong images are being reported with current binaries
=> ImageEx LoadImageAsync changes

Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs
-Added Refresh method to the collection as per #885 
-Changed LoadMoreItemsAsync(uint) to run continuations on the caller thread context
-Removed UI thread sync code in LoadMoreItemsAsync(uint, CancellationToken)
-Removed unused "usings"
=> Add Refresh method to IncrementalLoadCollection

Microsoft.Toolkit.Uwp.SampleApp/Models/Samples.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/BladeView/BladePage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs, Microsoft.Toolkit.Uwp.Samples.BackgroundTasks/Microsoft.Toolkit.Uwp.Samples.BackgroundTasks.csproj, Microsoft.Toolkit.Uwp.Samples.BackgroundTasks/Microsoft.Toolkit.Uwp.Samples.BackgroundTasks.ruleset, Microsoft.Toolkit.Uwp.Samples.BackgroundTasks/Properties/AssemblyInfo.cs, Microsoft.Toolkit.Uwp.Samples.BackgroundTasks/project.json
=> Fix hamburger selected item not synced when using back button in sample app

Microsoft.Toolkit.Uwp.SampleApp/App.xaml, Microsoft.Toolkit.Uwp.SampleApp/Controls/CodeRenderer/CodeRenderer.cs
=> Add Copy button to code samples

Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs
Move IsSupported check before accessing compositor.
=> DropShadowPanel prevent unhandled exception

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
=> Fix issue with AdaptiveGridView scrollbars

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Source.cs
Compare ImageEx source before consuming it to prevent reload
Address #1016
=> ImageEx - Prevent reload

Microsoft.Toolkit.Uwp.UI/AdvancedCollectionView/AdvancedCollectionView.cs, UnitTests/UI/Test_AdvancedCollectionView.cs, docs/helpers/AdvancedCollectionView.md
The fix reasons should be self-explainable.
=> tiny fix on AdvancedCollectionView; #914

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs, Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.xaml
Allow a CommandBar to be set on the master and details section. 
Fixes #893
=> Add a CommandBar for the master and details section. 

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/CarouselPanel.cs
Temporary work on inertia to keep the control as smooth as possible
=> Carousel Control

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DropShadowPanel/DropShadowPanelPage.xaml, Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.xaml
Add Vertical and Horizontal alignments to the DropShadowPanel to properly align the shadow with the content
Fixes #1072
=> Fix the Drop shadow alignment

Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
Code simplification. No need to check for key existence. Should use indexer directly.
=> Settings value persistence simplificaiton

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Inlines/MarkdownLinkInline.cs
=> Fix bug with closing parenthesis inside urls

Microsoft.Toolkit.Uwp/Helpers/Network/ConnectionInformation.cs
Ensure that the connection profile has one or more network names before trying to add those
Addresses #1112
=> ConnectionInformation tweak

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
=> Fix MarkdownTextBlock ImageStretch

Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBaseExtensions.cs, docs/helpers/ListViewBaseExtensions.md
Extended a ListView control with an AlternateRowColor property.
=> AlternateRowColor and AlternateRowItemTemplate property for ListViewBaseExtensions

Microsoft.Toolkit.Uwp.SampleApp/App.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/HamburgerMenu/HamburgerMenuPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml
=> fix(HamburgerMenu): fix use of search in the sample page

Microsoft.Toolkit.Uwp.UI/Extensions/HyperlinkExtensions.cs, Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBaseExtensions.cs, Microsoft.Toolkit.Uwp.UI/Extensions/WebViewExtensions.cs
Renamed the dependency object to the object it extends from issue #1142
=> Remove dependency object as parameter on attached properties #1142

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Loading/LoadingPage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/Loading/Loading.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/Loading/Loading.cs, Microsoft.Toolkit.Uwp.UI.Controls/Loading/Loading.xaml
Default loading control to hidden
Fixes #1133
=> Hide Loading control when initialatizes

Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.xaml
=> Hide ScrollHeaders vertical scrollbar

docs/helpers/ImageCache.md
=> Updated ImageCache file path

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DropShadowPanel/DropShadowPanelPage.xaml, Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.Members.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExBase.Members.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageExBase.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.Members.cs, Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.cs
Expose GetAlphaMask for both ImageEx and RoundImageEx
Modify UpdateShadowMask method to support ImageEx and RoundImageEx
Addressing #1178 
I am not happy about async void for UpdateShadowMask. Open to suggestions.
=> DropShadow support for ImageEx and RoundImageEx

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/HamburgerMenu/HamburgerMenuCode.bind
ButtonTemplate and OptionTemplate are non-existing and thus confusing
for anyone reading the sample of the Hamburger menu.
=> Use page defined item templates

Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
The QuickReturnHeader was not scrolling smoothly when using touch, as reported in issue #1050. There was a visible lag caused by the fact that the header position was updated manually on an event handler and not purely through expression animation.
The expression animation has been improved to allow 100% smooth scrolling. There is still code needed in the event handler, but it will not influence scrolling anymore.
=> QuickReturnHeaderBehavior: Improve expression animation to allow smooth scrolling

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Parse/Inlines/ImageInline.cs
=> MarkdownTextblock: fixed issue in image not returning the correct ending position

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/OrbitView/OrbitViewPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/OrbitView/OrbitViewPage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitView.cs, Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitViewDataItem.cs, Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitViewItem.cs, Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitViewItemClickedEventArgs.cs
Few changes to OrbitView to clean up before 1.5 to match standard control functionality
=> Orbit view cleanup

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
=> feat(samples): navigate to sample page if user choose suggestion in search bar

docs/controls/TextBoxMask.md
The documentation is not in line with reality.
=> TextBoxMasks in TextBoxMask

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Graph Service/MicrosoftGraphCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Graph Service/MicrosoftGraphPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Graph Service/MicrosoftGraphPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Microsoft Graph Service/MicrosoftGraphSource.cs, Microsoft.Toolkit.Uwp.Services/Microsoft.Toolkit.Uwp.Services.csproj, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/Events/MicrosoftGraphEventFields.cs, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/Events/MicrosoftGraphServiceEvent.cs, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/MicrosoftGraphCoreService.cs, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/MicrosoftGraphEnums.cs, Microsoft.Toolkit.Uwp.Services/Services/MicrosoftGraph/User/MicrosoftGraphUserService.cs, docs/services/MicrosoftGraph.md
In addition to the **messages** and **user profile**, Microsoft Graph service can now retrieve **calendar events**.
=> Retrieve calendar events with Microsoft Graph service.

Microsoft.Toolkit.Uwp/Helpers/ScreenUnit.cs, Microsoft.Toolkit.Uwp/Helpers/ScreenUnitHelper.cs, Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj, UnitTests/Helpers/Test_ScreenUnitHelper.cs, UnitTests/UnitTests.csproj
Linked to #1242 
ping @nmetulev
=> feat(helpers): add screen unit helper

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/RoundImageEx.xaml
Provide default value for HorizontalAlignment and VerticalAlignment in RoundImageEx.xaml.
Address #1373
=> RoundImageEx Default alignment value.

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Facebook Service/FacebookPage.xaml.cs, Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
details in here:  https://github.com/Microsoft/UWPCommunityToolkit/issues/1316
=> fixes to Facebook service following FB graph changes in v2.9

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
=> Adaptivegridview panel margin fix

docs/helpers/Converters.md
List all converters and provide examples of other core converter scenarios.
=> Resolves #1167: Update Converter Docs

Microsoft.Toolkit.Uwp.SampleApp/Controls/CodeRenderer/CodeRenderer.cs, Microsoft.Toolkit.Uwp.SampleApp/Controls/PropertyControl.xaml.cs
=> Sample app fixes

Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs
ItemsPanelRoot was null and throwing Exception in OnApplyTemplate.
=> Fix x:Bind Issue with ScrollHeader and TargetListViewBase

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Expander/ExpanderXaml.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RotatorTile/RotatorTileCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Saturation/SaturationBehaviorXaml.bind, Microsoft.Toolkit.Uwp.UI.Controls/Expander/Expander.cs, Microsoft.Toolkit.Uwp.UI.Controls/RotatorTile/RotatorTile.cs
Add more info to doc string.
Clean-up sample to side-step issue #1411
=> Update RotatorTile Sample to show Delay/RandomDuration properties

Microsoft.Toolkit.Uwp.SampleApp/App.xaml, Microsoft.Toolkit.Uwp.SampleApp/Pages/About.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
=> Fixed some navigation issues with Xbox

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs, Microsoft.Toolkit.Uwp.UI/Cache/FileCache.cs, Microsoft.Toolkit.Uwp.UI/Cache/ImageCache.cs
Cachebase stream initialisation rework to improve speed and prevent artefacts on image
=> Cachebase stream initialisation rework

Microsoft.Toolkit.Uwp.UI.Controls/Menu/MenuItem.cs
=> Fixing IsEnabled menu show on hover and on requesting menu from keyboard 

build/default.ps1
Update to latest sign client version
=> update to latest sign client

Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json, Microsoft.Toolkit.Uwp.UI.Controls/TextToolbar/Symbols/Symbol.cs, Microsoft.Toolkit.Uwp.UI/Extensions/Tree/LogicalTree.cs
=> SampleApp bug fixes

Microsoft.Toolkit.Uwp.Connectivity/BluetoothLEHelper/BluetoothLEHelper.cs, Microsoft.Toolkit.Uwp.Connectivity/BluetoothLEHelper/ObservableBluetoothLEDevice.cs
This change fixes a few bugs in the Bluetooth LE framework and adds support for querying device signal strength.
=> Port Bluetooth LE fixes and signal strength to UWP Community Toolkit

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Expander/ExpanderPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Expander/ExpanderXaml.bind
fix #1481 
@nmetulev We could plan to push an update for the sample app.
=> fix(SampleApp): add scrollviewer for expander sample page

Microsoft.Toolkit.Uwp.UI.Controls/ControlHelpers.Composition.cs, Microsoft.Toolkit.Uwp.UI.Controls/ControlHelpers.DesignTime.cs, Microsoft.Toolkit.Uwp.UI.Controls/ControlHelpers.Math.cs, Microsoft.Toolkit.Uwp.UI.Controls/DropShadowPanel/DropShadowPanel.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs, Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.cs
This improves what the designer can render at design time when running in a version of Windows and Visual Studio that supports that.
=> Use DesignMode.DesignMode2Enabled to enhance designer experience 

Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
=> Fix for sample app on Anniversary Update

docs/extensions/ViewExtensions.md
=> Fix issue with documentation

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, contributing.md, readme.md
=> updated the contributing guidelines and added templates for issues and PRs

Microsoft.Toolkit.Uwp.Services/Services/OneDrive/OneDriveStorageItem.cs
Issue: #
Bug fix.
```
[x ] Bugfix
[ ] Feature
```
NullReferenceException when trying to login to OneDrive service with OnlineId auth.
Folder list is returned.
```
[ ] Yes
[x] No
```
N/A
=> fix to nullreferenceexception

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RotatorTile/RotatorTileCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RotatorTile/RotatorTilePage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls/RotatorTile/RotatorTile.cs
=> RotatorTile - Add support for Down and Right as Directions

appveyor.yml
```
[ ] Bugfix
[ ] Feature
[x] Build or CI related changes
```
AppVeyor build is failing due to expired signing client key
Updated to use new signing client key
```
[ ] Yes
[x] No
```
=> Update appveyor with new signing client key

build/StyleXaml.bat, build/UpdateHeaders.bat, build/build.cake
```
[ ] Bugfix
[ ] Feature
[x] Build or CI related changes
```
You have to open Powershell in the Build Folder, and enter "./Build.ps1 -target=UpdateHeaders" or "./Build.ps1 -target=StyleXaml".
Added two double click and run .bat files to automate this task, as an ease of life for lazy developers :)
```
[ ] Yes
[x] No
```
=> Batch files to Run StyleXaml or UpdateHeaders Tasks.

build/build.ps1
```
[ ] Bugfix
[ ] Feature
[x] Build or CI related changes
```
AppVeyor builds are no longer building due to a TLS issue. See https://github.com/cake-build/resources/issues/39
=> fix for appveyor builds failing

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MasterDetailsView/MasterDetailsView.bind
Issue: #1473 #893
Improve the MasterDetailsView sample by showing a quick (non-functional) command bar sample
```
[ ] Bugfix
[ ] Feature
```
There is no sample for using the command bar(s) in the MasterDetailsView and there have been a few questions about it
The MasterDetailsView sample now includes a sample of using the command bar(s)
```
[ ] Yes
[x] No
```
=> Update MasterDetailsView sample to include CommandBar

Microsoft.Toolkit.Uwp.UI/Cache/CacheBase.cs
Issue: #1605 
```
[x] Bugfix
[ ] Feature
```
Its currently deleting all the files rather than expired files. 
```
[ ] Yes
[x] No
```
=> Delete desired files only for CacheBase.RemoveExpiredAsync

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
Add Focus on Xaml Pivot Item Selection
Add Tracking for Internal Monaco Editor Exceptions
=> Update Monaco.Editor to 0.4.0

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapPanel/WrapPanel.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapPanel/WrapPanelPage.xaml.cs, Microsoft.Toolkit.Uwp.UI.Controls.Design/WrapPanelMetadata.cs, Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/WrapPanel.cs, docs/controls/WrapPanel.md
Issue: #
https://github.com/Microsoft/UWPCommunityToolkit/issues/1611
```
[x] Feature
```
- [n/a] Tests for the changes have been added (for bug fixes / features) (if applicable)
Adds HorizontalSpacing and VerticalSpacing properties to WrapPanel, with updated samples and docs.
```
[ ] Yes
[x] No
```
=> WrapPanel spacing

docs/helpers/AppPinManager.md
AppPinManager link broken - issue has fixed
Issue: #
#1590 
[X] Bugfix
[ ] Feature
```
Link has broken 
valid link has updated
```
[ ] Yes
[X] No
```
=> AppPinManager document link

Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
Issue: #1676 
```
[x] Bugfix
```
Notifications library does not throw an exception
```
[ ] Yes
[x] No
```
=> Notifications - added System.Xml.ReaderWriter 4.3.0 as reference

docs/helpers/NetworkHelper.md
Issue: #
```
[ ] Bugfix
[ ] Feature
```
Namespace is Microsoft.Toolkit.Uwp which is not correct anymore.
Also, URL to source code is https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp/Helpers/Network/NetworkHelper.cs which leads to 404 error page.
Changed namespace to Microsoft.Toolkit.Uwp.Connectivity
Changed source code URL to https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.Connectivity/Network/NetworkHelper.cs …
=> Updated namespace and URL address to source code

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Loading/LoadingCode.bind
Issue: #1711
```
[ ] Bugfix
[ ] Feature
```
Sample changes the opacity of the entire control.
Sample now changes the opacity of the background
```
[ ] Yes
[x] No
```
=> Change Loading sample to change background opacity

.github/PULL_REQUEST_TEMPLATE.md, Microsoft.Toolkit.Uwp.SampleApp/readme.md, contributing.md
```
```
Added new Thumbnail style guides and templates to assist developer creating new icon for samples.
=> Added thumbnail style guide and templates

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Carousel/CarouselCode.bind
Issue: #1763
```
[x] Bugfix
```
SelectedIndex does not update properly
Sample now gets updated properly
```
[x] No
```
=> Fix Carousel sample page SelectedIndex binding

Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs, docs/helpers/SystemInformation.md
Issue: https://github.com/Microsoft/UWPCommunityToolkit/issues/1754
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> SystemInformation docs update

Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs, Microsoft.Toolkit.Uwp.UI/Extensions/Visual/VisualEx.cs
Issue: #1685
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
=> Fixed VisualEx crash when using language other than en-US 

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.cs, Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.xaml
Issue: #1744 
```
[x] Bugfix
```
App crashes when using carousel across multiple windows
App does not crash.
```
[ ] Yes
[x] No
```
=> Fix for Carousel crash under multi-window

Microsoft.Toolkit.Uwp.UI.Controls/ImageEx/ImageEx.xaml
Issue: #1731 
```
[x] Bugfix
[ ] Feature
```
ImageEx does not use TemplateBindings of BorderBrush and BorderThickness
ImageEx now uses TemplateBindings of BorderBrush and BorderThickness
```
[ ] Yes
[x] No
```
=> TemplateBinding BorderThickness & BorderBrush

Microsoft.Toolkit.Uwp.UI.Controls/Loading/Loading.Properties.cs, docs/controls/Loading.md
Issue: #1711
As noted by @ScottIsAFool , the docs are not correct.
Updated docs
=> Update Loading docs

Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Methods.cs
Issue: #1830
- Bugfix
The MarkdownTextBlock does not clear it's content when it's Text is empty or whitespace
The MarkdownTextBlock will clear it's content
=> Markdown empty text

Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml, Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
Samples do not indicate when an API has been deprecated
The sample page of deprecated APIs shows a message at the top when a control is deprecated
=> Added warning for depricated APIs in sample app

docs/controls/AdaptiveGridView.md
-Improved AdaptiveGridView docs, adding more information about OneRowMode, adding information about AspectRatio maintenance.
-Added gifs for AspectRatio and OneRowMode.
```
[ ] Yes
[x] No
```
=> AdaptiveGridView improved docs (Aspect Ratio and OneRowMode)

Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs
Issue: #1803 
- Bugfix
Will still flicker in some cases.
Should be stable.
=> Hopefully final AdaptiveGridView DPI fix.

docs/controls/AdaptiveGridView.md
Bugfix
Images don't load for Adaptive Grid View sample.
Images load for Adaptive Grid View sample.
=> Fixed issue where Images for Adaptive Grid View did not load in the sample app, due to an undocumented bug.

docs/controls/InAppNotification.md
Bugfix
Fix mistakes in the docs file of InAppNotification.
=> fix(InAppNotification): fix error in docs

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.cs
Summary docs have a few issues.
Fixing updates from summary docs
=> Carousel updates

UnitTests/UnitTestApp.xaml.cs, UnitTests/UnitTests.Notifications.UWP/UnitTestApp.xaml.cs
No need for them to be internal and it's breaking build
Issue: #
(https://github.com/Microsoft/UWPCommunityToolkit-design-assets)
=> Make unit test apps public

UnitTests/Converters/Test_AdaptiveHeightValueConverter.cs
Fix unit test to account for the fact that the AdaptiveGridView no longer has a default ItemContainerStyle
Issue: #
- Fix unit test
Unit test is failing
Unit test works
=> Fix unit test for AdaptiveHeightValueConverter

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RangeSelector/RangeSelectorCode.bind, Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs
Issue: #1615
- Bugfix
- Feature
The default StepFrequency is 0.01 which is hard to get normal values from
StepFrequency defaults to 1
=> Change default StepFrequency

Microsoft.Toolkit.Uwp.UI/Extensions/NavigationView/NavigationViewExtensions.cs
Issue: #1905
- Bugfix
We would sometimes in error set the SelectedItem to null due to an issue with comparing to the com object from the MenuItems list.
Now we do a safer check and avoid resetting the item if its the same, and if we gave a valid index avoid setting to null if we do fail.
=> Fix for NavigationView SelectedIndex Bug #1905

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs
Issue: #1910
- Bugfix
If you change either command bar after the template has loaded it will not properly show because the view gets the wrong command bars and panels
Get and show the proper panel
=> Properly show the command bars

Microsoft.Toolkit.Services/Services/Bing/BingLanguage.cs
Issue: #1912 
- Removing obsolete enum value for Moldavian language
=> Removing Moldavian language from Bing service

Microsoft.Toolkit.Uwp.UI/Extensions/Visual/VisualExtensions.cs
=> always take InvariantCulture when parsing floats

Microsoft.Toolkit.Uwp.Input.Gaze/GazePointer.cpp, Microsoft.Toolkit.Uwp.Input.Gaze/GazePointer.h, Microsoft.Toolkit.Uwp.Input.Gaze/GazePointerEventArgs.h, Microsoft.Toolkit.Uwp.Input.Gaze/GazeTargetItem.cpp, Microsoft.Toolkit.Uwp.Input.Gaze/GazeTargetItem.h
=> Made time int64 and cleaned some truncations.

Microsoft.Toolkit.Uwp.Input.Gaze/GazeCursor.cpp, Microsoft.Toolkit.Uwp.Input.Gaze/GazeCursor.h, Microsoft.Toolkit.Uwp.Input.Gaze/GazePointer.cpp, Microsoft.Toolkit.Uwp.Input.Gaze/GazePointer.h
=> Only show cursor when gaze has entered view.

.vsts-ci.yml
=> Adds a VSTS Build definition

Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.h, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GazeInteraction/GazeInteractionXaml.bind
=> Changed times from relative to start of gaze to relative to previous state

GazeInputTest/MainPage.xaml, GazeInputTest/MainPage.xaml.cs, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.h
=> Added indicator of device availablility.

GazeInputTest/MainPage.xaml.cs, Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellProgressEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeTargetItem.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/StateChangedEventArgs.h, docs/gaze/Gaze.md
=> More renames and doc updates

GazeInputTest/MainPage.xaml.cs, Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellProgressEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cpp
=> Fixed delay before dwell to use right property and simplified reporting of progress,

Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellInvokedRoutedEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellProgressEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellProgressState.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeCursor.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeElement.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeFeedbackPopupFactory.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeHistoryItem.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeSettingsHelper.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeSettingsHelper.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeStats.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeTargetItem.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/IGazeFilter.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/Interaction.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/OneEuroFilter.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/PointerState.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/StateChangedEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/pch.h
=> First step to clean up access of members.

Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellInvokedRoutedEventArgs.cpp, Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellInvokedRoutedEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/DwellProgressEventArgs.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeCursor.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeElement.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeHistoryItem.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeInput.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointerProxy.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeStats.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazeTargetItem.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/IGazeFilter.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/Interaction.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/OneEuroFilter.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/PointerState.h, Microsoft.Toolkit.Uwp.Input.GazeInteraction/StateChangedEventArgs.h
=> Slimming of header files

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/GazeInteraction/GazeInteractionXaml.bind
=> Adjusted ranges of property sliders

.vsts-pr.yml
=> update vsts scripts

Microsoft.Toolkit.Win32.UI.Controls/Microsoft.Toolkit.Win32.UI.Controls.csproj, UWP Community Toolkit.sln.GhostDoc.xml, build/Microsoft.Toolkit.Uwp.Input.GazeInteraction.nuspec, docs/breadcrumb/toc.yml, docs/controls/PullToRefreshListview.md, docs/docfx.json, docs/gaze/GazeInteractionLibrary.md
=> renamed UWP Community Toolkit to Windows Community Toolkit Part 2

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StringExtensions/StringExtensionsPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StringExtensions/StringExtensionsPage.xaml.cs
Issue: #2073
Page in sample app was very basic
Made more interactive and faster to see more of what's possible
PR based on separate discussion with @michael-hawker
=> Enhance StringExtensions page in Sample app

Microsoft.Toolkit.Win32.UI.Controls/Interop/OSVersionHelper.cs, Microsoft.Toolkit.Win32.UI.Controls/Interop/Win32/NativeMethods.cs, Microsoft.Toolkit.Win32.UI.Controls/Interop/Win32/OSVERSIONINFOEX.cs, Microsoft.Toolkit.Win32.UI.Controls/Interop/Win32/ProductType.cs
Issue: #2095 
- Bugfix
See #2095 
See #2095 
=> Fix for OSVERSIONINFOEX

Microsoft.Toolkit.Uwp.UI.Controls.Graph/PeoplePicker/PeoplePicker.Events.cs, Microsoft.Toolkit.Uwp.UI.Controls.Graph/PeoplePicker/PeoplePicker.Properties.cs, Microsoft.Toolkit.Uwp.UI.Controls.Graph/SharePointFileList/DriveItemIconConverter.cs
=> hotfix and optimization

docs/controls/ImageEx.md, docs/developer-tools/AlignmentGrid.md, docs/extensions/StringExtensions.md, docs/helpers/BackgroundTaskHelper.md, docs/helpers/SystemInformation.md, docs/parsers/RSSParser.md
Issue: #
Other... Please describe: Minor spelling and grammar fixes in the docs.
=> Minor spelling and grammar fixes in the project's documentation

Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer.csproj
- Bugfix
Project referencing PlatformSpecificAnalyzer can't build in release mode.
Project referencing PlatformSpecificAnalyzer can build in release mode.
=> Fix for PlatformSepecificAnalyzer in release mode

Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/Controls/InfiniteCanvasVirtualDrawingSurface.Render.cs, Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.cs, Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.xaml, docs/controls/InfiniteCanvas.md
Issue: #
Fixing #2160
- Bugfix 
=> Fixing Auto problem and canvasWidth Height problem

Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphAuthenticationHelper.cs
=> lead the user to re-sign in if the required scopes/permissions are changed

readme.md
Issue: #
Adding Infinite Canvas to home page
Documentation
=> Adding infinte canvas to read me

.vsts-pr.yml
=> no auto trigger for pr's

.vsts-ci.yml, .vsts-pr.yml
Issue: #
Removes the Windows SDK install step that's not currently needed.
=> Remove WinSDK install step

build/build.cake
Issue: #2202
Previously when performing an incremental build, the InheritDoc step would fail when parsing documentation after discovering the GazeInput native DLLs. 
InheritDoc version 1.1.1.1 no longer fails when it encounters such native DLL.
=> Update InheritDoc version

Directory.Build.targets
Issue: #
Adds the commit hash, like
`[assembly: AssemblyMetadata("CommitHash", "6b39b825472df4efa3e27c6ccaf9ac7f03f059ea")]`
To each assembly.
=> Adds CommitHash assembly metadata

Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphService.cs, Microsoft.Toolkit.Uwp.UI.Controls.Graph/AadLogin/AadLogin.cs
=> update IsAuthenticated after logout complete

contributing.md
I include the section of the accessibility guideline in contributing.md to let the community know about the basic accessibility functions, and thus, keep them in mind at the time to create new controls (or apply changes in an existing one).
Issue: #2276 
It is necessary a section that indicates the basic guidelines to ensure accessibility 
A new section which indicates the basic accessibility guidelines
=> [contributing.md] Including accessibility guideline

build/Install-WindowsSdkISO.ps1
Issue: #2314
Managed applications and DLLs in the Windows SDK may fail because they are test or delay signed.
During hosted build, StrongName is disabled for public key token `31bf3856ad364e35`, which is used by Windows SDK.
Script also updated for formatting and to ensure proper idempotency
Resolves #2314
=> Enable Install-WindowsSDKISO.ps1 to suppress strong naming

license.md
Issue: #
Correct typo in license.md
=> Correct typo in license.md

Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Properties/AssemblyInfo.cs, Microsoft.Toolkit.Uwp.UI.Controls.Graph/Properties/AssemblyInfo.cs, Microsoft.Toolkit.Uwp.UI.Controls/Properties/AssemblyInfo.cs
- Bugfix
Using the DataGrid in release mode causes an exception
No exception
=> DataGrid fix for release mode

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
Issue: #2421 
The StaggeredPanel's current description is:
`Allows items to be displayed with a specified header.`
Which seems that was copied from the HeaderedContentControl
The StaggeredPanel's description was changed to:
`The StaggeredPanel allows for layout of items in a column approach where an item will be added to whichever column has used the least amount of space.`
=> Modify StaggeredPanel description text

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Forms.UI.Controls/Microsoft.Toolkit.Forms.UI.Controls.csproj, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Sample.Forms.WebView/Form1.Designer.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Sample.Forms.WebView/Form1.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Sample.Forms.WebView/Program.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/Microsoft.Toolkit.Wpf.UI.Controls.csproj, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/Properties/AssemblyInfo.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/WebView/Compatible/IWebViewCompatibleAdapter.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/WebView/Compatible/WebBaseCompatibilityAdapter.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/WebView/Compatible/WebBrowserCompatibilityAdapter.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/WebView/Compatible/WebViewCompatibilityAdapter.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Wpf.UI.Controls/WebView/Compatible/WebViewCompatible.cs
Fixes for some feedback items left on #2453
=> PR Feedback

azure-pipelines.yml
Issue: #
Rename .azure-pipelines.yml to azure-pipelines.yml to match convention
=> rename to match convention

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.XamlHost/MetadataProviderDiscovery.cs, Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.XamlHost/XamlApplication.cs
Issue: #2456
- Bugfix
When loading types from frameworks (e.g. unit test), type loading throws exceptions for types unresolvable.
Type graph is resolved to the extent that types are available and emits only types from assemblies that can be successfully resolved. 
CC @ryalanms
=> Add more robust type loading system for Xaml Islands

Microsoft.Toolkit.Win32/Microsoft.Toolkit.Win32.UI.XamlHost/MetadataProviderDiscovery.cs
Issue: #2456
- Bugfix
When attempting to load an EXE or DLL that cannot be loaded by the CLR (most common case is the item is NATIVE, not CLR, or that the item is for a different bitness), a `BadImageFormatException` may occur. The exception is unhandled and causes bex.
Since the `MetadataProviderDiscovery` class is best-effort, catch the exception and continue processing the types and assemblies.
CC @lhak
=> Xaml Islands: Handle native DLL load attempt

Directory.Build.props, azure-pipelines.yml
Issue: #
Currently targeting 17758
Update to Windows SDK 17763
=> Update to SDK 17763

Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.cs
=> Reseting the scrollviewer again width/height to auto

Microsoft.Toolkit/Extensions/ArrayExtensions.cs, Microsoft.Toolkit/Extensions/StringExtensions.cs, docs/extensions/ArrayExtensions.md, docs/extensions/StringExtensions.md
Issue: N/A
Documentation content changes
Improved XML documentation of the `ArrayExtensions` and `StringExtensions` classes and updated their markdown docs counterparts.
should be more concise, easier to understand, and closer to the phrasing of the .NET Framework.
needs squashing
please LMK of any problems and what you think!
=> Update docs of ArrayExtensions, StringExtensions

Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Issue: #2452
- Bugfix
PDB issues with Portable PDBs
No issues as using Full PDBs.
=> Updated ColorCode

readme.md
=> Grammatical error fixed

Microsoft.Toolkit.Uwp.UI.Controls.Graph/AadLogin/AadLogin.Events.cs, Microsoft.Toolkit.Uwp.UI.Controls.Graph/AadLogin/AadLogin.cs
Issue: #2443 
- Bugfix
* The SignOutCompleted event is fired when sign out is completed.
* The obsolete SignInFailed event and SignOut method are removed
=> AadLogin: fixed signoutcompleted event, removed obsolete event and method

Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs, Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs, Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitView.cs, Microsoft.Toolkit.Uwp.UI.Controls/RadialProgressBar/RadialProgressBar.cs, Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.cs
Issue: https://twitter.com/scottisafool/status/1052134918036307968
- Bugfix
Several controls are sealed:
- InAppNotification
- MarkdownTextBlock
- OrbitView
- RadialProgressBar
- TileControl
Controls are not be sealed. 
=> Removing sealed from sealed controls

Microsoft.Toolkit.Services/Services/OneDrive/Platform/Uwp/OneDriveStorageFolderPlatform.cs
Issue: #2429 
- Bugfix
When trying to upload a file larger that 4MB, the service throws a "Resource could not be found" error.
The service successfully uploads the file.
=> OneDrive Service - Large file upload fix

Microsoft.Toolkit.Uwp.SampleApp/Controls/XamlCodeEditor.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
- Bugfix
Errors no longer show text in Sample App.
Errors show text in Sample App again.
=> Rev Monaco Editor version in Sample App to fix highlighting errors

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugeCode.bind, Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs
Issue: #2599
- Bugfix
Issues with hot the Value is set and arrow keys are not respected
The Value will now only change when it's within the StepSize. The arrow keys now respect the current StepSize
=> Radial gauge value step size

Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphEnums.cs
Issue: https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/pull/139
Documentation content changes
/cc @nmetulev
=> typo: wich -> which

Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.Properties.cs
Issue: https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/pull/153
=> typo: dependancy -> dependency

Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml.cs
Issue: #1740 #2387 
Bugfix
Links do not open.
Links redirect to docs.microsoft.com
=> Sample App - Redirect links to Microsoft Docs

Microsoft.Toolkit.Uwp.UI.Controls/RemoteDevicePicker/RemoteDevicePicker.cs, Microsoft.Toolkit.Uwp.UI.Controls/RemoteDevicePicker/RemoteDevicePicker.xaml
Issue: #2126
Bugfix
Check for null templated pieces in case removed from style.
=> Compatibility + Null checks for RemoteDevicePicker

Microsoft.Toolkit.Uwp.SampleApp/Data/DataGridDataSource.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DataGrid/DataGridCode.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DataGrid/DataGridPage.xaml.cs
Closes #2116
Column once sorted can't be unsorted.
Column's in sample app for DataGrid can now go between sorting one way, to other, and then back to no sorting.
=> Show how to do tri-state sorting in DataGrid Sample

Microsoft.Toolkit.Uwp.SampleApp/Package.appxmanifest, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json, Microsoft.Toolkit.Uwp.SampleApp/landingPageLinks.json
Update for 5.1 release, update What's New, fix some doc links, add Lottie docs.
=> Update Sample App in prep for 5.1 release

readme.md
Issue: #2807
Documentation content changes
No information about Lottie-Windows that is under the Toolkit umbrella of projects and was releasedin 5.1.0.
Update readme for landing page of the repo with links to Lottie-Windows related info. 
=> Add Lottie links to Readme

Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/WrapPanel.cs
Issue: #2804 and #2837
- Bugfix 
This PR fixes two issues in the `WrapPanel` control:
• The control would incorrectly wrap before it's needed, if the spacing property is not 0
• The control would incorrectly add the spacing for collapsed elements
The `WrapPanel` now correctly wraps to a new line/column, and properly hides collapsed items
=> WrapPanel control bug fixes (issues #2804 and #2837)

build/Install-WindowsSdkISO.ps1
Replacing iso download url to a new url
=> Updated SDK ISO url in build script

Microsoft.Toolkit.Parsers/Microsoft.Toolkit.Parsers.csproj, Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj, Microsoft.Toolkit.Uwp.Connectivity/Microsoft.Toolkit.Uwp.Connectivity.csproj, Microsoft.Toolkit.Uwp.DeveloperTools/Microsoft.Toolkit.Uwp.DeveloperTools.csproj, Microsoft.Toolkit.Uwp.Notifications.JavaScript/Microsoft.Toolkit.Uwp.Notifications.JavaScript.csproj, Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj, Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer.csproj, Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj, Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Graph/Microsoft.Toolkit.Uwp.UI.Controls.Graph.csproj, Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj, Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj, Microsoft.Toolkit/Microsoft.Toolkit.csproj
Issue: #2725 
Poor packages description
The packages have information about their APIs.
=> Improve packages description

Microsoft.Toolkit.Uwp.UI.Controls/Carousel/CarouselPanel.cs
Issue: #2829 
- Bugfix 
Carousel animation bug when SelectedIndex changes quickly.
I fixed this bug.
=> Fix carousel animation bug when SelectedIndex changes quickly.

Microsoft.Toolkit.Uwp/Helpers/PrintHelper/PrintHelper.cs
Issue: #2627
Bugfix
In Dark Theme since Text foreground is Light/White, it does not show up on the print preview/print pdf
Fixed this 
=> Print Helper - Fix ElementTheme on Dark Mode

build/Microsoft.Toolkit.Uwp.Input.GazeInteraction.nuspec
Issue: #
2915
- Bugfix 
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2915 
nuspec definition file has been updated to include .pdb file for dll
- [ x] Contains **NO** breaking changes
=> Added pdb's to the gazeinteraction nuget package

Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphService.cs
Issue: (none)
- Documentation content changes (well, documentation comment)
No behavior change
It's just a spelling fix ¯\\_(ツ)_/¯
=> Fix spelling mistake

GazeInputTest/GazeInputTest.csproj, Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj, UnitTests/UnitTests.Notifications.UWP/UnitTests.Notifications.UWP.csproj, UnitTests/UnitTests.Notifications.WinRT/UnitTests.Notifications.WinRT.csproj, UnitTests/UnitTests.csproj
- Bugfix
Clean clone will fail to build.
No pfx needed anymore for building the toolkit.
=> Fix possible cert/pfx errors.

.github/ISSUE_TEMPLATE/bug_report.md
**What kind of change does this PR introduce?**
Bug Emoji in the WCT Template
Bug Emoji does not match with the Fabric tool bot
Bug Emoji matches with the bot
=> Bug Emoji 

azure-pipelines.yml
Attempt to fix build issue by recent Dev Ops change.
=> Install .NET Core 3 as part of build

Microsoft.Toolkit.Uwp.UI.Controls/StaggeredPanel/StaggeredPanel.cs
Issue: #3002
- Bugfix
Setting the HorizontalAlignment to Right or Center does not properly layout the items
Items are properly laid out
=> Fix StaggeredPanel horizontal alignment

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxXaml.bind, Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.cs, Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.xaml, Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.xaml
Styling update.
- [x ] Contains **NO** breaking changes
=> Updated TokenizingTextBox and TokenizingTextBoxItem styling.

readme.md
=> UserVoice is no longer being used.

Directory.Build.props, GazeInputTest/GazeInputTest.csproj, Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj, Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml.cs, Microsoft.Toolkit.Uwp.Samples.BackgroundTasks/Microsoft.Toolkit.Uwp.Samples.BackgroundTasks.csproj, UnitTests/UnitTests.Notifications.UWP/UnitTests.Notifications.UWP.csproj, UnitTests/UnitTests.Notifications.WinRT/UnitTests.Notifications.WinRT.csproj, UnitTests/UnitTests.csproj, azure-pipelines.yml
=> Updated Target and Min version for 7.x release.

contributing.md
Minor fix to contributing.md file.
=> Fix broken link in contributing.md

azure-pipelines.yml, build/build.cake
Yaml Build is one single big step
Yaml Build was splitted into build, tests and packaging. Easier to detect issues on build process.
=> Splitted build, tests and packaging into individual yaml steps.

.github/PULL_REQUEST_TEMPLATE.md
Consistency, spelling error fix
What kind of change does this PR 
=> small modifications to PR template

CODE_OF_CONDUCT.md, readme.md
No code of conduct was in the repo
=> Code of conduct

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj, Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj, Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
Upgrade Microsoft.Xaml.Behaviors.Uwp.Managed package
Context is recorded here: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3008
Upgrading project dependencies.
Microsoft.Xaml.Behaviors.Uwp.Managed v1.1.0:
* Microsoft.Toolkit.Uwp.SampleApp.csproj
* Microsoft.Toolkit.Uwp.UI.csproj
* Microsoft.Toolkit.Uwp.UI.Animations.csproj
Microsoft.Xaml.Behaviors.Uwp.Managed v2.0.1
* Microsoft.Toolkit.Uwp.SampleApp.csproj
* Microsoft.Toolkit.Uwp.UI.csproj
* Microsoft.Toolkit.Uwp.UI.Animations.csproj
=> Upgrade Microsoft.Xaml.Behaviors.Uwp.Managed package

Microsoft.Toolkit.Uwp.SampleApp/readme.md
Doc typo:
Obviously wrong class used in example code, as no code uses that, and the header right above uses the correct class name.
Fix typo in documentation 
=> Example code was using the wrong class

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewPage.xaml.cs
fix a minor issue with a build failure on SampleApp in Release mode
Bugfix
Build failure in release mode X64 for SampleApp
fix a minor issue with a build failure on SampleApp in Release mode
=> simple fix for Release build 'warnings as errors' failure

readme.md
Outdated packages list
Packages list in sync with the docs repo
=> Synced packages list with docs repo

UnitTests/UnitTests.NetCore/UnitTests.NetCore.csproj
- Bugfix
Some .NET Core 2.1 unit tests for the base package fail when run locally.
All tests run correctly when executed locally.
=> Fixed local errors in .NET Core 2.1 unit tests

Microsoft.Toolkit.Uwp.UI.Controls/Strings/en-US/Resources.resw
Minor typo in `GridSplitter`'s default `AutomationProperties.Name`
- Bugfix
defaults to `GridSpliter`
defaults to `GridSplitter`
=> Correct default AutomationProperties.Name for GridSplitter

Microsoft.Toolkit.HighPerformance/Microsoft.Toolkit.HighPerformance.csproj, Microsoft.Toolkit.Uwp.SampleApp/readme.md, Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Some documents in the repo have spelling errors. 
Spelling Error fix in the documents. 
=> Fix spelling errors in .csproj and documentation files

Microsoft.Toolkit/Diagnostics/ThrowHelper.Generic.cs, Microsoft.Toolkit/Diagnostics/ThrowHelper.cs, UnitTests/UnitTests.Shared/Diagnostics/Test_ThrowHelper.cs
- Feature 
New generic overloads for all `ThrowHelper` APIs, see linked issue for more details.
=> Generic throw helper

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AutoFocusBehavior/AutoFocusBehaviorPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AutoFocusBehavior/AutoFocusBehaviorPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AutoFocusBehavior/AutoFocusBehaviorXaml.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/FocusBehavior/FocusBehaviorPage.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/FocusBehavior/FocusBehaviorPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/FocusBehavior/FocusBehaviorXaml.bind, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json, Microsoft.Toolkit.Uwp.UI/Behaviors/AutoFocusBehavior.cs, Microsoft.Toolkit.Uwp.UI/Behaviors/FocusBehavior.cs
This PR adds two behaviors to automatically set the focus when a page/control is loaded.
- Feature
- `AutoFocusBehavior` will set the focus to its attached control when it loads.
- `FocusBehavior` which set the focus to the first control accepting the focus from its `Targets` list.
The order of `FocusBehavior.Targets` is the order in which the focus should be set. `FocusBehavior` will try to set the focus on the first control, if it accepts it, we're done otherwise, `FocusBehavior` will try with the second control and so on. It contains a `FocusEngagementTimeout` to not wait forever for controls that will never be loaded.
It allows us to write this kind of XAML:
```xaml
<interactivity:Interaction.Behaviors>
<behaviors:FocusBehavior> …
```
=> Add FocusBehavior and AutoFocusBehavior

UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
=> Remove duplicate NuGet reference

Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Fallow up to #3637 
Applying https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3637#discussion_r552277725
=> Fix spacing in csproj

nuget.config
=> Remove MyGet Package Source and Update with Azure Source

nuget.config
Following new guidance on best practices, this shouldn't effect anything, so if the CI runs we should be all good.
=> Update nuget.config for best practices

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/CanvasPathGeometry/CanvasPathGeometryPage.xaml.cs
Fix ref to DispatcherQueueTimerExtensions namespace
- Bugfix
=> Fix smaple: using new namesapce for DispatcherQueueTimerExtensions

Microsoft.Toolkit.Uwp.UI.Animations/Extensions/StoryboardAnimations.cs
- Bugfix
The `Storyboard.BeginAsync` is never removing the handler.
The handler is removed when the event is raised.
=> Added removal for Storyboard completion handler

Microsoft.Toolkit.Uwp.DeveloperTools/FocusTracker/FocusTracker.cs, Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cs, Microsoft.Toolkit.Uwp.UI.Animations/ConnectedAnimations/ConnectedAnimationHelper.cs, Microsoft.Toolkit.Uwp.UI.Behaviors/Focus/FocusBehavior.cs, Microsoft.Toolkit.Uwp.UI.Controls.Core/RotatorTile/RotatorTile.cs, Microsoft.Toolkit.Uwp.UI.Controls.Core/TileControl/TileControl.cs, Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.cs, Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPicker.cs, Microsoft.Toolkit.Uwp.UI.Controls.Input/TokenizingTextBox/TokenizingTextBox.Selection.cs, Microsoft.Toolkit.Uwp.UI.Controls.Input/TokenizingTextBox/TokenizingTextBox.cs, Microsoft.Toolkit.Uwp.UI.Controls.Layout/BladeView/BladeView.cs, Microsoft.Toolkit.Uwp.UI.Controls.Markdown/MarkdownTextBlock/MarkdownTextBlock.Methods.cs, Microsoft.Toolkit.Uwp.UI.Media/Brushes/XamlCompositionBrush.cs, Microsoft.Toolkit.Uwp.UI/Triggers/NetworkConnectionStateTrigger.cs
Some classes were still using CoreDispatcher.
- Bugfix 
Some classes are not working properly on Xaml Islands
We don't use the old Dispatcher anymore. Everything is using DispatcherQueue and/or DispatcherQueueTimer.
=> Using DispatcherQueue instead of CoreDispatcher

build/build.cake
An extra dot was excluding the execution of UnitTests.NetCore.csproj tests on CI.
- Bugfix 
All tests are run, except UnitTests.NetCore.csproj
All tests are run, including UnitTests.NetCore.csproj
=> Fixed issue with pipeline not running UnitTests.NetCore tests.

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListViewExtensions/ListViewExtensionsCode.bind, Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.cs
- Bugfix 
ListViewExtensions sample is broken.
ListViewExtensions sample app works.
=> Fixed ListViewExtensionsCode.bind file.

Microsoft.Toolkit.Diagnostics/Microsoft.Toolkit.Diagnostics.csproj, Microsoft.Toolkit.HighPerformance/Microsoft.Toolkit.HighPerformance.csproj, Microsoft.Toolkit.Mvvm/Microsoft.Toolkit.Mvvm.csproj, Microsoft.Toolkit.Uwp.Connectivity/Microsoft.Toolkit.Uwp.Connectivity.csproj, Microsoft.Toolkit.Uwp.DeveloperTools/Microsoft.Toolkit.Uwp.DeveloperTools.csproj, Microsoft.Toolkit.Uwp.Input.GazeInteraction/Microsoft.Toolkit.Uwp.Input.GazeInteraction.csproj, Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj, Microsoft.Toolkit.Uwp.UI.Behaviors/Microsoft.Toolkit.Uwp.UI.Behaviors.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Core/Microsoft.Toolkit.Uwp.UI.Controls.Core.csproj, Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Input/Microsoft.Toolkit.Uwp.UI.Controls.Input.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Markdown/Microsoft.Toolkit.Uwp.UI.Controls.Markdown.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Media/Microsoft.Toolkit.Uwp.UI.Controls.Media.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Primitives/Microsoft.Toolkit.Uwp.UI.Controls.Primitives.csproj, Microsoft.Toolkit.Uwp.UI.Media/Microsoft.Toolkit.Uwp.UI.Media.csproj, Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj, Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj, Microsoft.Toolkit/Microsoft.Toolkit.csproj
Optimize the tags in our packages for better searchablity on nuget.org.
1. [x] Separate tags by semicolons.
2. [x] Include ~"Windows Community Toolkit"~, "Windows", "Community", "Toolkit" and "WCT" and tags across all packages.
3. [ ] ~Make sure each package has all the tags it needs for its controls/components and for multi word tags that they have split out tags present.~
- Bugfix
Our packages dont show up as much at the top of nuget.com for certain searches.
More often our packages show up at the top of nuget.com for certain searches.
=> Fix Package tags to better SEO on Nuget

.github/ISSUE_TEMPLATE/feature_request.md, Microsoft.Toolkit.Uwp.UI.Controls.Core/TabbedCommandBar/TabbedCommandBar.cs, Microsoft.Toolkit.Uwp.UI.Controls.Core/TabbedCommandBar/TabbedCommandBar.xaml, Microsoft.Toolkit.Uwp.UI.Controls.Core/TabbedCommandBar/TabbedCommandBarItem.cs
Replaces certain referecnes to ribbon with TabbedCommandBar
- Bugfix
=> Replace remaning references to ribbon to TabbedCommandBar

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
Update `ScrollHeader` sample docs to `/docs/behaviors/HeaderBehaviors.md`
- Bugfix
=> Update ScrollHeader sample docs to /docs/behaviors/HeaderBehaviors.md

Microsoft.Toolkit.HighPerformance/Memory/Internals/ThrowHelper.cs, Microsoft.Toolkit.HighPerformance/Memory/ReadOnlySpan2D{T}.cs, Microsoft.Toolkit.HighPerformance/Memory/Span2D{T}.cs
Reported in https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/issues/491
Incorrect exception message in `Span2D<T>.CopyTo(Span2D<T>)`.
- Bugfix
=> Fixed exception message and docs for Span2D<T>.CopyTo(Span2D<T>)

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Mouse/MouseCursorPage.bind
This will fix the oversight in the documentation after the 7.0 breaking change
Sample app changes
The sample app documentation use the old Mouse property
The sample app documentation use the new FrameworkElementExtensions methodproperty
=> Update Mouse to FrameworkElementExtensions

Microsoft.Toolkit.Uwp.UI.Controls.Media/Microsoft.Toolkit.Uwp.UI.Controls.Media.csproj, UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
=> Update System.Text.Json version for Controls.Media package

Directory.Build.props, Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.nuspec, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MarkdownTextBlock/InitialContent.md, Microsoft.Toolkit.Uwp.SampleApp/readme.md, Microsoft.Toolkit.Uwp.UI.Controls.Core.Design/Common/MetadataRegistrationBase.cs, Microsoft.Toolkit.Uwp.UI.Controls.Layout.Design/Common/MetadataRegistrationBase.cs, Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj, azure-pipelines.yml, readme.md, version.json
Should be all places we need to update for branch change
=> Update for new branch name

ReadMe.md
=> Update Readme (test CI)

Microsoft.Toolkit.Uwp.Connectivity/Network/ConnectionInformation.cs
=> Fix typo in ConnectionInformation class.

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxPage.xaml.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxXaml.bind, Microsoft.Toolkit.Uwp.UI.Behaviors/Microsoft.Toolkit.Uwp.UI.Behaviors.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Core/Microsoft.Toolkit.Uwp.UI.Controls.Core.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Input/Microsoft.Toolkit.Uwp.UI.Controls.Input.csproj, Microsoft.Toolkit.Uwp.UI.Controls.Primitives/Microsoft.Toolkit.Uwp.UI.Controls.Primitives.csproj, Microsoft.Toolkit.Uwp.UI.Media/Microsoft.Toolkit.Uwp.UI.Media.csproj, Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj, Microsoft.Toolkit.Uwp/Microsoft.Toolkit.Uwp.csproj, Windows Community Toolkit.sln, build/Windows.Toolkit.Common.targets
Cleans up sample for #4248 (though underlying issue remains to be figured out later).
Fixes a sample and cleans-up a few items we missed in our nuget packages. Just need to validate output from CI, but should be fairly straight-forward.
TTB Sample was binding to the internal collection instead of showing binding to a developer provided collection.
Some new features were missing from the NuGet package info.
Fixed! 🎉
=> Various 7.1 Clean-up Fixes

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
=> Fix samples.json values.

Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
=> samples.json: Fix Graph doc url

Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj, Microsoft.Toolkit.Uwp.SampleApp/Properties/AssemblyInfo.cs, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListDetailsView/ListDetailsView.bind, Microsoft.Toolkit.Uwp.SampleApp/landingPageLinks.json
Small adjustments made when getting 7.1 sample app ready.
=> Small Sample updates 7.1

Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.Factories.cs
Fixed order of `Delay` and `Duration` parameters in a call to `CreateDoubleAnimation` inside of `XamlTransformDoubleAnimationFactory.GetAnimation`.
- Bugfix
Delay parameter sets duration and vice versa.
Delay parameter sets delay and duration parameter sets duration.
=> Fixed parameter order

Microsoft.Toolkit.Uwp.UI.Animations/Builders/AnimationBuilder.cs
Fixes a broken code example in the documentation for the AnimationBuilder.Create() method.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.ui.animations.animationbuilder?view=win-comm-toolkit-dotnet-7.0
=> Fixed broken example code in AnimationBuilder.Create docs

Microsoft.Toolkit.Uwp.SampleApp/Pages/About.xaml, Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json, ReadMe.md
Outdated info
Adds updated info and better SEO for Windows 11
=> Update Readme and add mention of Windows 11 and WinUI 3

Microsoft.Toolkit.Uwp.Connectivity/BluetoothLEHelper/ObservableGattCharacteristics.cs
=> Properly attach / detach events when ObservableGattCharacteristics.Characteristic is changed

azure-pipelines.yml
=> Update NuGet Version in build pipeline

Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPickerSlider.cs
Reopen of #4732 (already approved, just building CI again before merge, original branch was deleted)
- Bugfix
=> ColorPicker Slider Circle Accessibility Fix

ReadMe.md
Updated preview links in repo readme.
n/a
=> Updated readme links to preview repos
